/**
 * Autogenerated by Thrift Compiler (0.14.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.aishu.wf.core.thrift.sharemgnt;

@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked", "unused"})
@javax.annotation.Generated(value = "Autogenerated by Thrift Compiler (0.14.2)", date = "2023-06-06")
public class ncTUsrmUserInfo implements org.apache.thrift.TBase<ncTUsrmUserInfo, ncTUsrmUserInfo._Fields>, java.io.Serializable, Cloneable, Comparable<ncTUsrmUserInfo> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("ncTUsrmUserInfo");

  private static final org.apache.thrift.protocol.TField LOGIN_NAME_FIELD_DESC = new org.apache.thrift.protocol.TField("loginName", org.apache.thrift.protocol.TType.STRING, (short)1);
  private static final org.apache.thrift.protocol.TField DISPLAY_NAME_FIELD_DESC = new org.apache.thrift.protocol.TField("displayName", org.apache.thrift.protocol.TType.STRING, (short)2);
  private static final org.apache.thrift.protocol.TField EMAIL_FIELD_DESC = new org.apache.thrift.protocol.TField("email", org.apache.thrift.protocol.TType.STRING, (short)3);
  private static final org.apache.thrift.protocol.TField SPACE_FIELD_DESC = new org.apache.thrift.protocol.TField("space", org.apache.thrift.protocol.TType.I64, (short)4);
  private static final org.apache.thrift.protocol.TField USER_TYPE_FIELD_DESC = new org.apache.thrift.protocol.TField("userType", org.apache.thrift.protocol.TType.I32, (short)5);
  private static final org.apache.thrift.protocol.TField DEPARTMENT_IDS_FIELD_DESC = new org.apache.thrift.protocol.TField("departmentIds", org.apache.thrift.protocol.TType.LIST, (short)6);
  private static final org.apache.thrift.protocol.TField DEPARTMENT_NAMES_FIELD_DESC = new org.apache.thrift.protocol.TField("departmentNames", org.apache.thrift.protocol.TType.LIST, (short)7);
  private static final org.apache.thrift.protocol.TField STATUS_FIELD_DESC = new org.apache.thrift.protocol.TField("status", org.apache.thrift.protocol.TType.I32, (short)8);
  private static final org.apache.thrift.protocol.TField USED_SIZE_FIELD_DESC = new org.apache.thrift.protocol.TField("usedSize", org.apache.thrift.protocol.TType.I64, (short)9);
  private static final org.apache.thrift.protocol.TField PRIORITY_FIELD_DESC = new org.apache.thrift.protocol.TField("priority", org.apache.thrift.protocol.TType.I32, (short)10);
  private static final org.apache.thrift.protocol.TField CSF_LEVEL_FIELD_DESC = new org.apache.thrift.protocol.TField("csfLevel", org.apache.thrift.protocol.TType.I32, (short)11);
  private static final org.apache.thrift.protocol.TField PWD_CONTROL_FIELD_DESC = new org.apache.thrift.protocol.TField("pwdControl", org.apache.thrift.protocol.TType.BOOL, (short)12);
  private static final org.apache.thrift.protocol.TField OSS_INFO_FIELD_DESC = new org.apache.thrift.protocol.TField("ossInfo", org.apache.thrift.protocol.TType.STRUCT, (short)13);
  private static final org.apache.thrift.protocol.TField LIMIT_SPACE_INFO_FIELD_DESC = new org.apache.thrift.protocol.TField("limitSpaceInfo", org.apache.thrift.protocol.TType.STRUCT, (short)14);
  private static final org.apache.thrift.protocol.TField CREATE_TIME_FIELD_DESC = new org.apache.thrift.protocol.TField("createTime", org.apache.thrift.protocol.TType.I64, (short)15);
  private static final org.apache.thrift.protocol.TField FREEZE_STATUS_FIELD_DESC = new org.apache.thrift.protocol.TField("freezeStatus", org.apache.thrift.protocol.TType.BOOL, (short)16);
  private static final org.apache.thrift.protocol.TField TEL_NUMBER_FIELD_DESC = new org.apache.thrift.protocol.TField("telNumber", org.apache.thrift.protocol.TType.STRING, (short)17);
  private static final org.apache.thrift.protocol.TField ROLES_FIELD_DESC = new org.apache.thrift.protocol.TField("roles", org.apache.thrift.protocol.TType.LIST, (short)18);
  private static final org.apache.thrift.protocol.TField EXPIRE_TIME_FIELD_DESC = new org.apache.thrift.protocol.TField("expireTime", org.apache.thrift.protocol.TType.I32, (short)19);
  private static final org.apache.thrift.protocol.TField REMARK_FIELD_DESC = new org.apache.thrift.protocol.TField("remark", org.apache.thrift.protocol.TType.STRING, (short)20);
  private static final org.apache.thrift.protocol.TField IDCARD_NUMBER_FIELD_DESC = new org.apache.thrift.protocol.TField("idcardNumber", org.apache.thrift.protocol.TType.STRING, (short)21);

  private static final org.apache.thrift.scheme.SchemeFactory STANDARD_SCHEME_FACTORY = new ncTUsrmUserInfoStandardSchemeFactory();
  private static final org.apache.thrift.scheme.SchemeFactory TUPLE_SCHEME_FACTORY = new ncTUsrmUserInfoTupleSchemeFactory();

  public @org.apache.thrift.annotation.Nullable java.lang.String loginName; // required
  public @org.apache.thrift.annotation.Nullable java.lang.String displayName; // optional
  public @org.apache.thrift.annotation.Nullable java.lang.String email; // optional
  public long space; // optional
  public @org.apache.thrift.annotation.Nullable ncTUsrmUserType userType; // optional
  public @org.apache.thrift.annotation.Nullable java.util.List<java.lang.String> departmentIds; // required
  public @org.apache.thrift.annotation.Nullable java.util.List<java.lang.String> departmentNames; // optional
  public @org.apache.thrift.annotation.Nullable ncTUsrmUserStatus status; // optional
  public long usedSize; // optional
  public int priority; // optional
  public int csfLevel; // optional
  public boolean pwdControl; // required
  public @org.apache.thrift.annotation.Nullable ncTUsrmOSSInfo ossInfo; // optional
  public @org.apache.thrift.annotation.Nullable ncTLimitSpaceInfo limitSpaceInfo; // optional
  public long createTime; // optional
  public boolean freezeStatus; // optional
  public @org.apache.thrift.annotation.Nullable java.lang.String telNumber; // optional
  public @org.apache.thrift.annotation.Nullable java.util.List<ncTRoleInfo> roles; // optional
  public int expireTime; // optional
  public @org.apache.thrift.annotation.Nullable java.lang.String remark; // optional
  public @org.apache.thrift.annotation.Nullable java.lang.String idcardNumber; // optional

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    LOGIN_NAME((short)1, "loginName"),
    DISPLAY_NAME((short)2, "displayName"),
    EMAIL((short)3, "email"),
    SPACE((short)4, "space"),
    USER_TYPE((short)5, "userType"),
    DEPARTMENT_IDS((short)6, "departmentIds"),
    DEPARTMENT_NAMES((short)7, "departmentNames"),
    STATUS((short)8, "status"),
    USED_SIZE((short)9, "usedSize"),
    PRIORITY((short)10, "priority"),
    CSF_LEVEL((short)11, "csfLevel"),
    PWD_CONTROL((short)12, "pwdControl"),
    OSS_INFO((short)13, "ossInfo"),
    LIMIT_SPACE_INFO((short)14, "limitSpaceInfo"),
    CREATE_TIME((short)15, "createTime"),
    FREEZE_STATUS((short)16, "freezeStatus"),
    TEL_NUMBER((short)17, "telNumber"),
    ROLES((short)18, "roles"),
    EXPIRE_TIME((short)19, "expireTime"),
    REMARK((short)20, "remark"),
    IDCARD_NUMBER((short)21, "idcardNumber");

    private static final java.util.Map<java.lang.String, _Fields> byName = new java.util.HashMap<java.lang.String, _Fields>();

    static {
      for (_Fields field : java.util.EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    @org.apache.thrift.annotation.Nullable
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // LOGIN_NAME
          return LOGIN_NAME;
        case 2: // DISPLAY_NAME
          return DISPLAY_NAME;
        case 3: // EMAIL
          return EMAIL;
        case 4: // SPACE
          return SPACE;
        case 5: // USER_TYPE
          return USER_TYPE;
        case 6: // DEPARTMENT_IDS
          return DEPARTMENT_IDS;
        case 7: // DEPARTMENT_NAMES
          return DEPARTMENT_NAMES;
        case 8: // STATUS
          return STATUS;
        case 9: // USED_SIZE
          return USED_SIZE;
        case 10: // PRIORITY
          return PRIORITY;
        case 11: // CSF_LEVEL
          return CSF_LEVEL;
        case 12: // PWD_CONTROL
          return PWD_CONTROL;
        case 13: // OSS_INFO
          return OSS_INFO;
        case 14: // LIMIT_SPACE_INFO
          return LIMIT_SPACE_INFO;
        case 15: // CREATE_TIME
          return CREATE_TIME;
        case 16: // FREEZE_STATUS
          return FREEZE_STATUS;
        case 17: // TEL_NUMBER
          return TEL_NUMBER;
        case 18: // ROLES
          return ROLES;
        case 19: // EXPIRE_TIME
          return EXPIRE_TIME;
        case 20: // REMARK
          return REMARK;
        case 21: // IDCARD_NUMBER
          return IDCARD_NUMBER;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new java.lang.IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    @org.apache.thrift.annotation.Nullable
    public static _Fields findByName(java.lang.String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final java.lang.String _fieldName;

    _Fields(short thriftId, java.lang.String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public java.lang.String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  private static final int __SPACE_ISSET_ID = 0;
  private static final int __USEDSIZE_ISSET_ID = 1;
  private static final int __PRIORITY_ISSET_ID = 2;
  private static final int __CSFLEVEL_ISSET_ID = 3;
  private static final int __PWDCONTROL_ISSET_ID = 4;
  private static final int __CREATETIME_ISSET_ID = 5;
  private static final int __FREEZESTATUS_ISSET_ID = 6;
  private static final int __EXPIRETIME_ISSET_ID = 7;
  private byte __isset_bitfield = 0;
  private static final _Fields optionals[] = {_Fields.DISPLAY_NAME,_Fields.EMAIL,_Fields.SPACE,_Fields.USER_TYPE,_Fields.DEPARTMENT_NAMES,_Fields.STATUS,_Fields.USED_SIZE,_Fields.PRIORITY,_Fields.CSF_LEVEL,_Fields.OSS_INFO,_Fields.LIMIT_SPACE_INFO,_Fields.CREATE_TIME,_Fields.FREEZE_STATUS,_Fields.TEL_NUMBER,_Fields.ROLES,_Fields.EXPIRE_TIME,_Fields.REMARK,_Fields.IDCARD_NUMBER};
  public static final java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new java.util.EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.LOGIN_NAME, new org.apache.thrift.meta_data.FieldMetaData("loginName", org.apache.thrift.TFieldRequirementType.REQUIRED, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.DISPLAY_NAME, new org.apache.thrift.meta_data.FieldMetaData("displayName", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.EMAIL, new org.apache.thrift.meta_data.FieldMetaData("email", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.SPACE, new org.apache.thrift.meta_data.FieldMetaData("space", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I64)));
    tmpMap.put(_Fields.USER_TYPE, new org.apache.thrift.meta_data.FieldMetaData("userType", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.ENUM        , "ncTUsrmUserType")));
    tmpMap.put(_Fields.DEPARTMENT_IDS, new org.apache.thrift.meta_data.FieldMetaData("departmentIds", org.apache.thrift.TFieldRequirementType.REQUIRED, 
        new org.apache.thrift.meta_data.ListMetaData(org.apache.thrift.protocol.TType.LIST, 
            new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING))));
    tmpMap.put(_Fields.DEPARTMENT_NAMES, new org.apache.thrift.meta_data.FieldMetaData("departmentNames", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.ListMetaData(org.apache.thrift.protocol.TType.LIST, 
            new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING))));
    tmpMap.put(_Fields.STATUS, new org.apache.thrift.meta_data.FieldMetaData("status", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.ENUM        , "ncTUsrmUserStatus")));
    tmpMap.put(_Fields.USED_SIZE, new org.apache.thrift.meta_data.FieldMetaData("usedSize", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I64)));
    tmpMap.put(_Fields.PRIORITY, new org.apache.thrift.meta_data.FieldMetaData("priority", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I32)));
    tmpMap.put(_Fields.CSF_LEVEL, new org.apache.thrift.meta_data.FieldMetaData("csfLevel", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I32)));
    tmpMap.put(_Fields.PWD_CONTROL, new org.apache.thrift.meta_data.FieldMetaData("pwdControl", org.apache.thrift.TFieldRequirementType.REQUIRED, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.BOOL)));
    tmpMap.put(_Fields.OSS_INFO, new org.apache.thrift.meta_data.FieldMetaData("ossInfo", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.StructMetaData(org.apache.thrift.protocol.TType.STRUCT, ncTUsrmOSSInfo.class)));
    tmpMap.put(_Fields.LIMIT_SPACE_INFO, new org.apache.thrift.meta_data.FieldMetaData("limitSpaceInfo", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRUCT        , "ncTLimitSpaceInfo")));
    tmpMap.put(_Fields.CREATE_TIME, new org.apache.thrift.meta_data.FieldMetaData("createTime", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I64)));
    tmpMap.put(_Fields.FREEZE_STATUS, new org.apache.thrift.meta_data.FieldMetaData("freezeStatus", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.BOOL)));
    tmpMap.put(_Fields.TEL_NUMBER, new org.apache.thrift.meta_data.FieldMetaData("telNumber", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.ROLES, new org.apache.thrift.meta_data.FieldMetaData("roles", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.ListMetaData(org.apache.thrift.protocol.TType.LIST, 
            new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRUCT            , "ncTRoleInfo"))));
    tmpMap.put(_Fields.EXPIRE_TIME, new org.apache.thrift.meta_data.FieldMetaData("expireTime", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I32)));
    tmpMap.put(_Fields.REMARK, new org.apache.thrift.meta_data.FieldMetaData("remark", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.IDCARD_NUMBER, new org.apache.thrift.meta_data.FieldMetaData("idcardNumber", org.apache.thrift.TFieldRequirementType.OPTIONAL, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    metaDataMap = java.util.Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(ncTUsrmUserInfo.class, metaDataMap);
  }

  public ncTUsrmUserInfo() {
  }

  public ncTUsrmUserInfo(
    java.lang.String loginName,
    java.util.List<java.lang.String> departmentIds,
    boolean pwdControl)
  {
    this();
    this.loginName = loginName;
    this.departmentIds = departmentIds;
    this.pwdControl = pwdControl;
    setPwdControlIsSet(true);
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public ncTUsrmUserInfo(ncTUsrmUserInfo other) {
    __isset_bitfield = other.__isset_bitfield;
    if (other.isSetLoginName()) {
      this.loginName = other.loginName;
    }
    if (other.isSetDisplayName()) {
      this.displayName = other.displayName;
    }
    if (other.isSetEmail()) {
      this.email = other.email;
    }
    this.space = other.space;
    if (other.isSetUserType()) {
      this.userType = other.userType;
    }
    if (other.isSetDepartmentIds()) {
      java.util.List<java.lang.String> __this__departmentIds = new java.util.ArrayList<java.lang.String>(other.departmentIds);
      this.departmentIds = __this__departmentIds;
    }
    if (other.isSetDepartmentNames()) {
      java.util.List<java.lang.String> __this__departmentNames = new java.util.ArrayList<java.lang.String>(other.departmentNames);
      this.departmentNames = __this__departmentNames;
    }
    if (other.isSetStatus()) {
      this.status = other.status;
    }
    this.usedSize = other.usedSize;
    this.priority = other.priority;
    this.csfLevel = other.csfLevel;
    this.pwdControl = other.pwdControl;
    if (other.isSetOssInfo()) {
      this.ossInfo = new ncTUsrmOSSInfo(other.ossInfo);
    }
    if (other.isSetLimitSpaceInfo()) {
      this.limitSpaceInfo = new ncTLimitSpaceInfo(other.limitSpaceInfo);
    }
    this.createTime = other.createTime;
    this.freezeStatus = other.freezeStatus;
    if (other.isSetTelNumber()) {
      this.telNumber = other.telNumber;
    }
    if (other.isSetRoles()) {
      java.util.List<ncTRoleInfo> __this__roles = new java.util.ArrayList<ncTRoleInfo>(other.roles.size());
      for (ncTRoleInfo other_element : other.roles) {
        __this__roles.add(new ncTRoleInfo(other_element));
      }
      this.roles = __this__roles;
    }
    this.expireTime = other.expireTime;
    if (other.isSetRemark()) {
      this.remark = other.remark;
    }
    if (other.isSetIdcardNumber()) {
      this.idcardNumber = other.idcardNumber;
    }
  }

  public ncTUsrmUserInfo deepCopy() {
    return new ncTUsrmUserInfo(this);
  }

  @Override
  public void clear() {
    this.loginName = null;
    this.displayName = null;
    this.email = null;
    setSpaceIsSet(false);
    this.space = 0;
    this.userType = null;
    this.departmentIds = null;
    this.departmentNames = null;
    this.status = null;
    setUsedSizeIsSet(false);
    this.usedSize = 0;
    setPriorityIsSet(false);
    this.priority = 0;
    setCsfLevelIsSet(false);
    this.csfLevel = 0;
    setPwdControlIsSet(false);
    this.pwdControl = false;
    this.ossInfo = null;
    this.limitSpaceInfo = null;
    setCreateTimeIsSet(false);
    this.createTime = 0;
    setFreezeStatusIsSet(false);
    this.freezeStatus = false;
    this.telNumber = null;
    this.roles = null;
    setExpireTimeIsSet(false);
    this.expireTime = 0;
    this.remark = null;
    this.idcardNumber = null;
  }

  @org.apache.thrift.annotation.Nullable
  public java.lang.String getLoginName() {
    return this.loginName;
  }

  public ncTUsrmUserInfo setLoginName(@org.apache.thrift.annotation.Nullable java.lang.String loginName) {
    this.loginName = loginName;
    return this;
  }

  public void unsetLoginName() {
    this.loginName = null;
  }

  /** Returns true if field loginName is set (has been assigned a value) and false otherwise */
  public boolean isSetLoginName() {
    return this.loginName != null;
  }

  public void setLoginNameIsSet(boolean value) {
    if (!value) {
      this.loginName = null;
    }
  }

  @org.apache.thrift.annotation.Nullable
  public java.lang.String getDisplayName() {
    return this.displayName;
  }

  public ncTUsrmUserInfo setDisplayName(@org.apache.thrift.annotation.Nullable java.lang.String displayName) {
    this.displayName = displayName;
    return this;
  }

  public void unsetDisplayName() {
    this.displayName = null;
  }

  /** Returns true if field displayName is set (has been assigned a value) and false otherwise */
  public boolean isSetDisplayName() {
    return this.displayName != null;
  }

  public void setDisplayNameIsSet(boolean value) {
    if (!value) {
      this.displayName = null;
    }
  }

  @org.apache.thrift.annotation.Nullable
  public java.lang.String getEmail() {
    return this.email;
  }

  public ncTUsrmUserInfo setEmail(@org.apache.thrift.annotation.Nullable java.lang.String email) {
    this.email = email;
    return this;
  }

  public void unsetEmail() {
    this.email = null;
  }

  /** Returns true if field email is set (has been assigned a value) and false otherwise */
  public boolean isSetEmail() {
    return this.email != null;
  }

  public void setEmailIsSet(boolean value) {
    if (!value) {
      this.email = null;
    }
  }

  public long getSpace() {
    return this.space;
  }

  public ncTUsrmUserInfo setSpace(long space) {
    this.space = space;
    setSpaceIsSet(true);
    return this;
  }

  public void unsetSpace() {
    __isset_bitfield = org.apache.thrift.EncodingUtils.clearBit(__isset_bitfield, __SPACE_ISSET_ID);
  }

  /** Returns true if field space is set (has been assigned a value) and false otherwise */
  public boolean isSetSpace() {
    return org.apache.thrift.EncodingUtils.testBit(__isset_bitfield, __SPACE_ISSET_ID);
  }

  public void setSpaceIsSet(boolean value) {
    __isset_bitfield = org.apache.thrift.EncodingUtils.setBit(__isset_bitfield, __SPACE_ISSET_ID, value);
  }

  @org.apache.thrift.annotation.Nullable
  public ncTUsrmUserType getUserType() {
    return this.userType;
  }

  public ncTUsrmUserInfo setUserType(@org.apache.thrift.annotation.Nullable ncTUsrmUserType userType) {
    this.userType = userType;
    return this;
  }

  public void unsetUserType() {
    this.userType = null;
  }

  /** Returns true if field userType is set (has been assigned a value) and false otherwise */
  public boolean isSetUserType() {
    return this.userType != null;
  }

  public void setUserTypeIsSet(boolean value) {
    if (!value) {
      this.userType = null;
    }
  }

  public int getDepartmentIdsSize() {
    return (this.departmentIds == null) ? 0 : this.departmentIds.size();
  }

  @org.apache.thrift.annotation.Nullable
  public java.util.Iterator<java.lang.String> getDepartmentIdsIterator() {
    return (this.departmentIds == null) ? null : this.departmentIds.iterator();
  }

  public void addToDepartmentIds(java.lang.String elem) {
    if (this.departmentIds == null) {
      this.departmentIds = new java.util.ArrayList<java.lang.String>();
    }
    this.departmentIds.add(elem);
  }

  @org.apache.thrift.annotation.Nullable
  public java.util.List<java.lang.String> getDepartmentIds() {
    return this.departmentIds;
  }

  public ncTUsrmUserInfo setDepartmentIds(@org.apache.thrift.annotation.Nullable java.util.List<java.lang.String> departmentIds) {
    this.departmentIds = departmentIds;
    return this;
  }

  public void unsetDepartmentIds() {
    this.departmentIds = null;
  }

  /** Returns true if field departmentIds is set (has been assigned a value) and false otherwise */
  public boolean isSetDepartmentIds() {
    return this.departmentIds != null;
  }

  public void setDepartmentIdsIsSet(boolean value) {
    if (!value) {
      this.departmentIds = null;
    }
  }

  public int getDepartmentNamesSize() {
    return (this.departmentNames == null) ? 0 : this.departmentNames.size();
  }

  @org.apache.thrift.annotation.Nullable
  public java.util.Iterator<java.lang.String> getDepartmentNamesIterator() {
    return (this.departmentNames == null) ? null : this.departmentNames.iterator();
  }

  public void addToDepartmentNames(java.lang.String elem) {
    if (this.departmentNames == null) {
      this.departmentNames = new java.util.ArrayList<java.lang.String>();
    }
    this.departmentNames.add(elem);
  }

  @org.apache.thrift.annotation.Nullable
  public java.util.List<java.lang.String> getDepartmentNames() {
    return this.departmentNames;
  }

  public ncTUsrmUserInfo setDepartmentNames(@org.apache.thrift.annotation.Nullable java.util.List<java.lang.String> departmentNames) {
    this.departmentNames = departmentNames;
    return this;
  }

  public void unsetDepartmentNames() {
    this.departmentNames = null;
  }

  /** Returns true if field departmentNames is set (has been assigned a value) and false otherwise */
  public boolean isSetDepartmentNames() {
    return this.departmentNames != null;
  }

  public void setDepartmentNamesIsSet(boolean value) {
    if (!value) {
      this.departmentNames = null;
    }
  }

  @org.apache.thrift.annotation.Nullable
  public ncTUsrmUserStatus getStatus() {
    return this.status;
  }

  public ncTUsrmUserInfo setStatus(@org.apache.thrift.annotation.Nullable ncTUsrmUserStatus status) {
    this.status = status;
    return this;
  }

  public void unsetStatus() {
    this.status = null;
  }

  /** Returns true if field status is set (has been assigned a value) and false otherwise */
  public boolean isSetStatus() {
    return this.status != null;
  }

  public void setStatusIsSet(boolean value) {
    if (!value) {
      this.status = null;
    }
  }

  public long getUsedSize() {
    return this.usedSize;
  }

  public ncTUsrmUserInfo setUsedSize(long usedSize) {
    this.usedSize = usedSize;
    setUsedSizeIsSet(true);
    return this;
  }

  public void unsetUsedSize() {
    __isset_bitfield = org.apache.thrift.EncodingUtils.clearBit(__isset_bitfield, __USEDSIZE_ISSET_ID);
  }

  /** Returns true if field usedSize is set (has been assigned a value) and false otherwise */
  public boolean isSetUsedSize() {
    return org.apache.thrift.EncodingUtils.testBit(__isset_bitfield, __USEDSIZE_ISSET_ID);
  }

  public void setUsedSizeIsSet(boolean value) {
    __isset_bitfield = org.apache.thrift.EncodingUtils.setBit(__isset_bitfield, __USEDSIZE_ISSET_ID, value);
  }

  public int getPriority() {
    return this.priority;
  }

  public ncTUsrmUserInfo setPriority(int priority) {
    this.priority = priority;
    setPriorityIsSet(true);
    return this;
  }

  public void unsetPriority() {
    __isset_bitfield = org.apache.thrift.EncodingUtils.clearBit(__isset_bitfield, __PRIORITY_ISSET_ID);
  }

  /** Returns true if field priority is set (has been assigned a value) and false otherwise */
  public boolean isSetPriority() {
    return org.apache.thrift.EncodingUtils.testBit(__isset_bitfield, __PRIORITY_ISSET_ID);
  }

  public void setPriorityIsSet(boolean value) {
    __isset_bitfield = org.apache.thrift.EncodingUtils.setBit(__isset_bitfield, __PRIORITY_ISSET_ID, value);
  }

  public int getCsfLevel() {
    return this.csfLevel;
  }

  public ncTUsrmUserInfo setCsfLevel(int csfLevel) {
    this.csfLevel = csfLevel;
    setCsfLevelIsSet(true);
    return this;
  }

  public void unsetCsfLevel() {
    __isset_bitfield = org.apache.thrift.EncodingUtils.clearBit(__isset_bitfield, __CSFLEVEL_ISSET_ID);
  }

  /** Returns true if field csfLevel is set (has been assigned a value) and false otherwise */
  public boolean isSetCsfLevel() {
    return org.apache.thrift.EncodingUtils.testBit(__isset_bitfield, __CSFLEVEL_ISSET_ID);
  }

  public void setCsfLevelIsSet(boolean value) {
    __isset_bitfield = org.apache.thrift.EncodingUtils.setBit(__isset_bitfield, __CSFLEVEL_ISSET_ID, value);
  }

  public boolean isPwdControl() {
    return this.pwdControl;
  }

  public ncTUsrmUserInfo setPwdControl(boolean pwdControl) {
    this.pwdControl = pwdControl;
    setPwdControlIsSet(true);
    return this;
  }

  public void unsetPwdControl() {
    __isset_bitfield = org.apache.thrift.EncodingUtils.clearBit(__isset_bitfield, __PWDCONTROL_ISSET_ID);
  }

  /** Returns true if field pwdControl is set (has been assigned a value) and false otherwise */
  public boolean isSetPwdControl() {
    return org.apache.thrift.EncodingUtils.testBit(__isset_bitfield, __PWDCONTROL_ISSET_ID);
  }

  public void setPwdControlIsSet(boolean value) {
    __isset_bitfield = org.apache.thrift.EncodingUtils.setBit(__isset_bitfield, __PWDCONTROL_ISSET_ID, value);
  }

  @org.apache.thrift.annotation.Nullable
  public ncTUsrmOSSInfo getOssInfo() {
    return this.ossInfo;
  }

  public ncTUsrmUserInfo setOssInfo(@org.apache.thrift.annotation.Nullable ncTUsrmOSSInfo ossInfo) {
    this.ossInfo = ossInfo;
    return this;
  }

  public void unsetOssInfo() {
    this.ossInfo = null;
  }

  /** Returns true if field ossInfo is set (has been assigned a value) and false otherwise */
  public boolean isSetOssInfo() {
    return this.ossInfo != null;
  }

  public void setOssInfoIsSet(boolean value) {
    if (!value) {
      this.ossInfo = null;
    }
  }

  @org.apache.thrift.annotation.Nullable
  public ncTLimitSpaceInfo getLimitSpaceInfo() {
    return this.limitSpaceInfo;
  }

  public ncTUsrmUserInfo setLimitSpaceInfo(@org.apache.thrift.annotation.Nullable ncTLimitSpaceInfo limitSpaceInfo) {
    this.limitSpaceInfo = limitSpaceInfo;
    return this;
  }

  public void unsetLimitSpaceInfo() {
    this.limitSpaceInfo = null;
  }

  /** Returns true if field limitSpaceInfo is set (has been assigned a value) and false otherwise */
  public boolean isSetLimitSpaceInfo() {
    return this.limitSpaceInfo != null;
  }

  public void setLimitSpaceInfoIsSet(boolean value) {
    if (!value) {
      this.limitSpaceInfo = null;
    }
  }

  public long getCreateTime() {
    return this.createTime;
  }

  public ncTUsrmUserInfo setCreateTime(long createTime) {
    this.createTime = createTime;
    setCreateTimeIsSet(true);
    return this;
  }

  public void unsetCreateTime() {
    __isset_bitfield = org.apache.thrift.EncodingUtils.clearBit(__isset_bitfield, __CREATETIME_ISSET_ID);
  }

  /** Returns true if field createTime is set (has been assigned a value) and false otherwise */
  public boolean isSetCreateTime() {
    return org.apache.thrift.EncodingUtils.testBit(__isset_bitfield, __CREATETIME_ISSET_ID);
  }

  public void setCreateTimeIsSet(boolean value) {
    __isset_bitfield = org.apache.thrift.EncodingUtils.setBit(__isset_bitfield, __CREATETIME_ISSET_ID, value);
  }

  public boolean isFreezeStatus() {
    return this.freezeStatus;
  }

  public ncTUsrmUserInfo setFreezeStatus(boolean freezeStatus) {
    this.freezeStatus = freezeStatus;
    setFreezeStatusIsSet(true);
    return this;
  }

  public void unsetFreezeStatus() {
    __isset_bitfield = org.apache.thrift.EncodingUtils.clearBit(__isset_bitfield, __FREEZESTATUS_ISSET_ID);
  }

  /** Returns true if field freezeStatus is set (has been assigned a value) and false otherwise */
  public boolean isSetFreezeStatus() {
    return org.apache.thrift.EncodingUtils.testBit(__isset_bitfield, __FREEZESTATUS_ISSET_ID);
  }

  public void setFreezeStatusIsSet(boolean value) {
    __isset_bitfield = org.apache.thrift.EncodingUtils.setBit(__isset_bitfield, __FREEZESTATUS_ISSET_ID, value);
  }

  @org.apache.thrift.annotation.Nullable
  public java.lang.String getTelNumber() {
    return this.telNumber;
  }

  public ncTUsrmUserInfo setTelNumber(@org.apache.thrift.annotation.Nullable java.lang.String telNumber) {
    this.telNumber = telNumber;
    return this;
  }

  public void unsetTelNumber() {
    this.telNumber = null;
  }

  /** Returns true if field telNumber is set (has been assigned a value) and false otherwise */
  public boolean isSetTelNumber() {
    return this.telNumber != null;
  }

  public void setTelNumberIsSet(boolean value) {
    if (!value) {
      this.telNumber = null;
    }
  }

  public int getRolesSize() {
    return (this.roles == null) ? 0 : this.roles.size();
  }

  @org.apache.thrift.annotation.Nullable
  public java.util.Iterator<ncTRoleInfo> getRolesIterator() {
    return (this.roles == null) ? null : this.roles.iterator();
  }

  public void addToRoles(ncTRoleInfo elem) {
    if (this.roles == null) {
      this.roles = new java.util.ArrayList<ncTRoleInfo>();
    }
    this.roles.add(elem);
  }

  @org.apache.thrift.annotation.Nullable
  public java.util.List<ncTRoleInfo> getRoles() {
    return this.roles;
  }

  public ncTUsrmUserInfo setRoles(@org.apache.thrift.annotation.Nullable java.util.List<ncTRoleInfo> roles) {
    this.roles = roles;
    return this;
  }

  public void unsetRoles() {
    this.roles = null;
  }

  /** Returns true if field roles is set (has been assigned a value) and false otherwise */
  public boolean isSetRoles() {
    return this.roles != null;
  }

  public void setRolesIsSet(boolean value) {
    if (!value) {
      this.roles = null;
    }
  }

  public int getExpireTime() {
    return this.expireTime;
  }

  public ncTUsrmUserInfo setExpireTime(int expireTime) {
    this.expireTime = expireTime;
    setExpireTimeIsSet(true);
    return this;
  }

  public void unsetExpireTime() {
    __isset_bitfield = org.apache.thrift.EncodingUtils.clearBit(__isset_bitfield, __EXPIRETIME_ISSET_ID);
  }

  /** Returns true if field expireTime is set (has been assigned a value) and false otherwise */
  public boolean isSetExpireTime() {
    return org.apache.thrift.EncodingUtils.testBit(__isset_bitfield, __EXPIRETIME_ISSET_ID);
  }

  public void setExpireTimeIsSet(boolean value) {
    __isset_bitfield = org.apache.thrift.EncodingUtils.setBit(__isset_bitfield, __EXPIRETIME_ISSET_ID, value);
  }

  @org.apache.thrift.annotation.Nullable
  public java.lang.String getRemark() {
    return this.remark;
  }

  public ncTUsrmUserInfo setRemark(@org.apache.thrift.annotation.Nullable java.lang.String remark) {
    this.remark = remark;
    return this;
  }

  public void unsetRemark() {
    this.remark = null;
  }

  /** Returns true if field remark is set (has been assigned a value) and false otherwise */
  public boolean isSetRemark() {
    return this.remark != null;
  }

  public void setRemarkIsSet(boolean value) {
    if (!value) {
      this.remark = null;
    }
  }

  @org.apache.thrift.annotation.Nullable
  public java.lang.String getIdcardNumber() {
    return this.idcardNumber;
  }

  public ncTUsrmUserInfo setIdcardNumber(@org.apache.thrift.annotation.Nullable java.lang.String idcardNumber) {
    this.idcardNumber = idcardNumber;
    return this;
  }

  public void unsetIdcardNumber() {
    this.idcardNumber = null;
  }

  /** Returns true if field idcardNumber is set (has been assigned a value) and false otherwise */
  public boolean isSetIdcardNumber() {
    return this.idcardNumber != null;
  }

  public void setIdcardNumberIsSet(boolean value) {
    if (!value) {
      this.idcardNumber = null;
    }
  }

  public void setFieldValue(_Fields field, @org.apache.thrift.annotation.Nullable java.lang.Object value) {
    switch (field) {
    case LOGIN_NAME:
      if (value == null) {
        unsetLoginName();
      } else {
        setLoginName((java.lang.String)value);
      }
      break;

    case DISPLAY_NAME:
      if (value == null) {
        unsetDisplayName();
      } else {
        setDisplayName((java.lang.String)value);
      }
      break;

    case EMAIL:
      if (value == null) {
        unsetEmail();
      } else {
        setEmail((java.lang.String)value);
      }
      break;

    case SPACE:
      if (value == null) {
        unsetSpace();
      } else {
        setSpace((java.lang.Long)value);
      }
      break;

    case USER_TYPE:
      if (value == null) {
        unsetUserType();
      } else {
        setUserType((ncTUsrmUserType)value);
      }
      break;

    case DEPARTMENT_IDS:
      if (value == null) {
        unsetDepartmentIds();
      } else {
        setDepartmentIds((java.util.List<java.lang.String>)value);
      }
      break;

    case DEPARTMENT_NAMES:
      if (value == null) {
        unsetDepartmentNames();
      } else {
        setDepartmentNames((java.util.List<java.lang.String>)value);
      }
      break;

    case STATUS:
      if (value == null) {
        unsetStatus();
      } else {
        setStatus((ncTUsrmUserStatus)value);
      }
      break;

    case USED_SIZE:
      if (value == null) {
        unsetUsedSize();
      } else {
        setUsedSize((java.lang.Long)value);
      }
      break;

    case PRIORITY:
      if (value == null) {
        unsetPriority();
      } else {
        setPriority((java.lang.Integer)value);
      }
      break;

    case CSF_LEVEL:
      if (value == null) {
        unsetCsfLevel();
      } else {
        setCsfLevel((java.lang.Integer)value);
      }
      break;

    case PWD_CONTROL:
      if (value == null) {
        unsetPwdControl();
      } else {
        setPwdControl((java.lang.Boolean)value);
      }
      break;

    case OSS_INFO:
      if (value == null) {
        unsetOssInfo();
      } else {
        setOssInfo((ncTUsrmOSSInfo)value);
      }
      break;

    case LIMIT_SPACE_INFO:
      if (value == null) {
        unsetLimitSpaceInfo();
      } else {
        setLimitSpaceInfo((ncTLimitSpaceInfo)value);
      }
      break;

    case CREATE_TIME:
      if (value == null) {
        unsetCreateTime();
      } else {
        setCreateTime((java.lang.Long)value);
      }
      break;

    case FREEZE_STATUS:
      if (value == null) {
        unsetFreezeStatus();
      } else {
        setFreezeStatus((java.lang.Boolean)value);
      }
      break;

    case TEL_NUMBER:
      if (value == null) {
        unsetTelNumber();
      } else {
        setTelNumber((java.lang.String)value);
      }
      break;

    case ROLES:
      if (value == null) {
        unsetRoles();
      } else {
        setRoles((java.util.List<ncTRoleInfo>)value);
      }
      break;

    case EXPIRE_TIME:
      if (value == null) {
        unsetExpireTime();
      } else {
        setExpireTime((java.lang.Integer)value);
      }
      break;

    case REMARK:
      if (value == null) {
        unsetRemark();
      } else {
        setRemark((java.lang.String)value);
      }
      break;

    case IDCARD_NUMBER:
      if (value == null) {
        unsetIdcardNumber();
      } else {
        setIdcardNumber((java.lang.String)value);
      }
      break;

    }
  }

  @org.apache.thrift.annotation.Nullable
  public java.lang.Object getFieldValue(_Fields field) {
    switch (field) {
    case LOGIN_NAME:
      return getLoginName();

    case DISPLAY_NAME:
      return getDisplayName();

    case EMAIL:
      return getEmail();

    case SPACE:
      return getSpace();

    case USER_TYPE:
      return getUserType();

    case DEPARTMENT_IDS:
      return getDepartmentIds();

    case DEPARTMENT_NAMES:
      return getDepartmentNames();

    case STATUS:
      return getStatus();

    case USED_SIZE:
      return getUsedSize();

    case PRIORITY:
      return getPriority();

    case CSF_LEVEL:
      return getCsfLevel();

    case PWD_CONTROL:
      return isPwdControl();

    case OSS_INFO:
      return getOssInfo();

    case LIMIT_SPACE_INFO:
      return getLimitSpaceInfo();

    case CREATE_TIME:
      return getCreateTime();

    case FREEZE_STATUS:
      return isFreezeStatus();

    case TEL_NUMBER:
      return getTelNumber();

    case ROLES:
      return getRoles();

    case EXPIRE_TIME:
      return getExpireTime();

    case REMARK:
      return getRemark();

    case IDCARD_NUMBER:
      return getIdcardNumber();

    }
    throw new java.lang.IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new java.lang.IllegalArgumentException();
    }

    switch (field) {
    case LOGIN_NAME:
      return isSetLoginName();
    case DISPLAY_NAME:
      return isSetDisplayName();
    case EMAIL:
      return isSetEmail();
    case SPACE:
      return isSetSpace();
    case USER_TYPE:
      return isSetUserType();
    case DEPARTMENT_IDS:
      return isSetDepartmentIds();
    case DEPARTMENT_NAMES:
      return isSetDepartmentNames();
    case STATUS:
      return isSetStatus();
    case USED_SIZE:
      return isSetUsedSize();
    case PRIORITY:
      return isSetPriority();
    case CSF_LEVEL:
      return isSetCsfLevel();
    case PWD_CONTROL:
      return isSetPwdControl();
    case OSS_INFO:
      return isSetOssInfo();
    case LIMIT_SPACE_INFO:
      return isSetLimitSpaceInfo();
    case CREATE_TIME:
      return isSetCreateTime();
    case FREEZE_STATUS:
      return isSetFreezeStatus();
    case TEL_NUMBER:
      return isSetTelNumber();
    case ROLES:
      return isSetRoles();
    case EXPIRE_TIME:
      return isSetExpireTime();
    case REMARK:
      return isSetRemark();
    case IDCARD_NUMBER:
      return isSetIdcardNumber();
    }
    throw new java.lang.IllegalStateException();
  }

  @Override
  public boolean equals(java.lang.Object that) {
    if (that instanceof ncTUsrmUserInfo)
      return this.equals((ncTUsrmUserInfo)that);
    return false;
  }

  public boolean equals(ncTUsrmUserInfo that) {
    if (that == null)
      return false;
    if (this == that)
      return true;

    boolean this_present_loginName = true && this.isSetLoginName();
    boolean that_present_loginName = true && that.isSetLoginName();
    if (this_present_loginName || that_present_loginName) {
      if (!(this_present_loginName && that_present_loginName))
        return false;
      if (!this.loginName.equals(that.loginName))
        return false;
    }

    boolean this_present_displayName = true && this.isSetDisplayName();
    boolean that_present_displayName = true && that.isSetDisplayName();
    if (this_present_displayName || that_present_displayName) {
      if (!(this_present_displayName && that_present_displayName))
        return false;
      if (!this.displayName.equals(that.displayName))
        return false;
    }

    boolean this_present_email = true && this.isSetEmail();
    boolean that_present_email = true && that.isSetEmail();
    if (this_present_email || that_present_email) {
      if (!(this_present_email && that_present_email))
        return false;
      if (!this.email.equals(that.email))
        return false;
    }

    boolean this_present_space = true && this.isSetSpace();
    boolean that_present_space = true && that.isSetSpace();
    if (this_present_space || that_present_space) {
      if (!(this_present_space && that_present_space))
        return false;
      if (this.space != that.space)
        return false;
    }

    boolean this_present_userType = true && this.isSetUserType();
    boolean that_present_userType = true && that.isSetUserType();
    if (this_present_userType || that_present_userType) {
      if (!(this_present_userType && that_present_userType))
        return false;
      if (!this.userType.equals(that.userType))
        return false;
    }

    boolean this_present_departmentIds = true && this.isSetDepartmentIds();
    boolean that_present_departmentIds = true && that.isSetDepartmentIds();
    if (this_present_departmentIds || that_present_departmentIds) {
      if (!(this_present_departmentIds && that_present_departmentIds))
        return false;
      if (!this.departmentIds.equals(that.departmentIds))
        return false;
    }

    boolean this_present_departmentNames = true && this.isSetDepartmentNames();
    boolean that_present_departmentNames = true && that.isSetDepartmentNames();
    if (this_present_departmentNames || that_present_departmentNames) {
      if (!(this_present_departmentNames && that_present_departmentNames))
        return false;
      if (!this.departmentNames.equals(that.departmentNames))
        return false;
    }

    boolean this_present_status = true && this.isSetStatus();
    boolean that_present_status = true && that.isSetStatus();
    if (this_present_status || that_present_status) {
      if (!(this_present_status && that_present_status))
        return false;
      if (!this.status.equals(that.status))
        return false;
    }

    boolean this_present_usedSize = true && this.isSetUsedSize();
    boolean that_present_usedSize = true && that.isSetUsedSize();
    if (this_present_usedSize || that_present_usedSize) {
      if (!(this_present_usedSize && that_present_usedSize))
        return false;
      if (this.usedSize != that.usedSize)
        return false;
    }

    boolean this_present_priority = true && this.isSetPriority();
    boolean that_present_priority = true && that.isSetPriority();
    if (this_present_priority || that_present_priority) {
      if (!(this_present_priority && that_present_priority))
        return false;
      if (this.priority != that.priority)
        return false;
    }

    boolean this_present_csfLevel = true && this.isSetCsfLevel();
    boolean that_present_csfLevel = true && that.isSetCsfLevel();
    if (this_present_csfLevel || that_present_csfLevel) {
      if (!(this_present_csfLevel && that_present_csfLevel))
        return false;
      if (this.csfLevel != that.csfLevel)
        return false;
    }

    boolean this_present_pwdControl = true;
    boolean that_present_pwdControl = true;
    if (this_present_pwdControl || that_present_pwdControl) {
      if (!(this_present_pwdControl && that_present_pwdControl))
        return false;
      if (this.pwdControl != that.pwdControl)
        return false;
    }

    boolean this_present_ossInfo = true && this.isSetOssInfo();
    boolean that_present_ossInfo = true && that.isSetOssInfo();
    if (this_present_ossInfo || that_present_ossInfo) {
      if (!(this_present_ossInfo && that_present_ossInfo))
        return false;
      if (!this.ossInfo.equals(that.ossInfo))
        return false;
    }

    boolean this_present_limitSpaceInfo = true && this.isSetLimitSpaceInfo();
    boolean that_present_limitSpaceInfo = true && that.isSetLimitSpaceInfo();
    if (this_present_limitSpaceInfo || that_present_limitSpaceInfo) {
      if (!(this_present_limitSpaceInfo && that_present_limitSpaceInfo))
        return false;
      if (!this.limitSpaceInfo.equals(that.limitSpaceInfo))
        return false;
    }

    boolean this_present_createTime = true && this.isSetCreateTime();
    boolean that_present_createTime = true && that.isSetCreateTime();
    if (this_present_createTime || that_present_createTime) {
      if (!(this_present_createTime && that_present_createTime))
        return false;
      if (this.createTime != that.createTime)
        return false;
    }

    boolean this_present_freezeStatus = true && this.isSetFreezeStatus();
    boolean that_present_freezeStatus = true && that.isSetFreezeStatus();
    if (this_present_freezeStatus || that_present_freezeStatus) {
      if (!(this_present_freezeStatus && that_present_freezeStatus))
        return false;
      if (this.freezeStatus != that.freezeStatus)
        return false;
    }

    boolean this_present_telNumber = true && this.isSetTelNumber();
    boolean that_present_telNumber = true && that.isSetTelNumber();
    if (this_present_telNumber || that_present_telNumber) {
      if (!(this_present_telNumber && that_present_telNumber))
        return false;
      if (!this.telNumber.equals(that.telNumber))
        return false;
    }

    boolean this_present_roles = true && this.isSetRoles();
    boolean that_present_roles = true && that.isSetRoles();
    if (this_present_roles || that_present_roles) {
      if (!(this_present_roles && that_present_roles))
        return false;
      if (!this.roles.equals(that.roles))
        return false;
    }

    boolean this_present_expireTime = true && this.isSetExpireTime();
    boolean that_present_expireTime = true && that.isSetExpireTime();
    if (this_present_expireTime || that_present_expireTime) {
      if (!(this_present_expireTime && that_present_expireTime))
        return false;
      if (this.expireTime != that.expireTime)
        return false;
    }

    boolean this_present_remark = true && this.isSetRemark();
    boolean that_present_remark = true && that.isSetRemark();
    if (this_present_remark || that_present_remark) {
      if (!(this_present_remark && that_present_remark))
        return false;
      if (!this.remark.equals(that.remark))
        return false;
    }

    boolean this_present_idcardNumber = true && this.isSetIdcardNumber();
    boolean that_present_idcardNumber = true && that.isSetIdcardNumber();
    if (this_present_idcardNumber || that_present_idcardNumber) {
      if (!(this_present_idcardNumber && that_present_idcardNumber))
        return false;
      if (!this.idcardNumber.equals(that.idcardNumber))
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    int hashCode = 1;

    hashCode = hashCode * 8191 + ((isSetLoginName()) ? 131071 : 524287);
    if (isSetLoginName())
      hashCode = hashCode * 8191 + loginName.hashCode();

    hashCode = hashCode * 8191 + ((isSetDisplayName()) ? 131071 : 524287);
    if (isSetDisplayName())
      hashCode = hashCode * 8191 + displayName.hashCode();

    hashCode = hashCode * 8191 + ((isSetEmail()) ? 131071 : 524287);
    if (isSetEmail())
      hashCode = hashCode * 8191 + email.hashCode();

    hashCode = hashCode * 8191 + ((isSetSpace()) ? 131071 : 524287);
    if (isSetSpace())
      hashCode = hashCode * 8191 + org.apache.thrift.TBaseHelper.hashCode(space);

    hashCode = hashCode * 8191 + ((isSetUserType()) ? 131071 : 524287);
    if (isSetUserType())
      hashCode = hashCode * 8191 + userType.getValue();

    hashCode = hashCode * 8191 + ((isSetDepartmentIds()) ? 131071 : 524287);
    if (isSetDepartmentIds())
      hashCode = hashCode * 8191 + departmentIds.hashCode();

    hashCode = hashCode * 8191 + ((isSetDepartmentNames()) ? 131071 : 524287);
    if (isSetDepartmentNames())
      hashCode = hashCode * 8191 + departmentNames.hashCode();

    hashCode = hashCode * 8191 + ((isSetStatus()) ? 131071 : 524287);
    if (isSetStatus())
      hashCode = hashCode * 8191 + status.getValue();

    hashCode = hashCode * 8191 + ((isSetUsedSize()) ? 131071 : 524287);
    if (isSetUsedSize())
      hashCode = hashCode * 8191 + org.apache.thrift.TBaseHelper.hashCode(usedSize);

    hashCode = hashCode * 8191 + ((isSetPriority()) ? 131071 : 524287);
    if (isSetPriority())
      hashCode = hashCode * 8191 + priority;

    hashCode = hashCode * 8191 + ((isSetCsfLevel()) ? 131071 : 524287);
    if (isSetCsfLevel())
      hashCode = hashCode * 8191 + csfLevel;

    hashCode = hashCode * 8191 + ((pwdControl) ? 131071 : 524287);

    hashCode = hashCode * 8191 + ((isSetOssInfo()) ? 131071 : 524287);
    if (isSetOssInfo())
      hashCode = hashCode * 8191 + ossInfo.hashCode();

    hashCode = hashCode * 8191 + ((isSetLimitSpaceInfo()) ? 131071 : 524287);
    if (isSetLimitSpaceInfo())
      hashCode = hashCode * 8191 + limitSpaceInfo.hashCode();

    hashCode = hashCode * 8191 + ((isSetCreateTime()) ? 131071 : 524287);
    if (isSetCreateTime())
      hashCode = hashCode * 8191 + org.apache.thrift.TBaseHelper.hashCode(createTime);

    hashCode = hashCode * 8191 + ((isSetFreezeStatus()) ? 131071 : 524287);
    if (isSetFreezeStatus())
      hashCode = hashCode * 8191 + ((freezeStatus) ? 131071 : 524287);

    hashCode = hashCode * 8191 + ((isSetTelNumber()) ? 131071 : 524287);
    if (isSetTelNumber())
      hashCode = hashCode * 8191 + telNumber.hashCode();

    hashCode = hashCode * 8191 + ((isSetRoles()) ? 131071 : 524287);
    if (isSetRoles())
      hashCode = hashCode * 8191 + roles.hashCode();

    hashCode = hashCode * 8191 + ((isSetExpireTime()) ? 131071 : 524287);
    if (isSetExpireTime())
      hashCode = hashCode * 8191 + expireTime;

    hashCode = hashCode * 8191 + ((isSetRemark()) ? 131071 : 524287);
    if (isSetRemark())
      hashCode = hashCode * 8191 + remark.hashCode();

    hashCode = hashCode * 8191 + ((isSetIdcardNumber()) ? 131071 : 524287);
    if (isSetIdcardNumber())
      hashCode = hashCode * 8191 + idcardNumber.hashCode();

    return hashCode;
  }

  @Override
  public int compareTo(ncTUsrmUserInfo other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = java.lang.Boolean.compare(isSetLoginName(), other.isSetLoginName());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetLoginName()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.loginName, other.loginName);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.compare(isSetDisplayName(), other.isSetDisplayName());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetDisplayName()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.displayName, other.displayName);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.compare(isSetEmail(), other.isSetEmail());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetEmail()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.email, other.email);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.compare(isSetSpace(), other.isSetSpace());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetSpace()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.space, other.space);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.compare(isSetUserType(), other.isSetUserType());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetUserType()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.userType, other.userType);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.compare(isSetDepartmentIds(), other.isSetDepartmentIds());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetDepartmentIds()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.departmentIds, other.departmentIds);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.compare(isSetDepartmentNames(), other.isSetDepartmentNames());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetDepartmentNames()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.departmentNames, other.departmentNames);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.compare(isSetStatus(), other.isSetStatus());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetStatus()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.status, other.status);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.compare(isSetUsedSize(), other.isSetUsedSize());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetUsedSize()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.usedSize, other.usedSize);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.compare(isSetPriority(), other.isSetPriority());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetPriority()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.priority, other.priority);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.compare(isSetCsfLevel(), other.isSetCsfLevel());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetCsfLevel()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.csfLevel, other.csfLevel);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.compare(isSetPwdControl(), other.isSetPwdControl());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetPwdControl()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.pwdControl, other.pwdControl);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.compare(isSetOssInfo(), other.isSetOssInfo());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetOssInfo()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.ossInfo, other.ossInfo);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.compare(isSetLimitSpaceInfo(), other.isSetLimitSpaceInfo());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetLimitSpaceInfo()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.limitSpaceInfo, other.limitSpaceInfo);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.compare(isSetCreateTime(), other.isSetCreateTime());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetCreateTime()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.createTime, other.createTime);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.compare(isSetFreezeStatus(), other.isSetFreezeStatus());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetFreezeStatus()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.freezeStatus, other.freezeStatus);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.compare(isSetTelNumber(), other.isSetTelNumber());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetTelNumber()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.telNumber, other.telNumber);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.compare(isSetRoles(), other.isSetRoles());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetRoles()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.roles, other.roles);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.compare(isSetExpireTime(), other.isSetExpireTime());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetExpireTime()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.expireTime, other.expireTime);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.compare(isSetRemark(), other.isSetRemark());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetRemark()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.remark, other.remark);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.compare(isSetIdcardNumber(), other.isSetIdcardNumber());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetIdcardNumber()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.idcardNumber, other.idcardNumber);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  @org.apache.thrift.annotation.Nullable
  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    scheme(iprot).read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    scheme(oprot).write(oprot, this);
  }

  @Override
  public java.lang.String toString() {
    java.lang.StringBuilder sb = new java.lang.StringBuilder("ncTUsrmUserInfo(");
    boolean first = true;

    sb.append("loginName:");
    if (this.loginName == null) {
      sb.append("null");
    } else {
      sb.append(this.loginName);
    }
    first = false;
    if (isSetDisplayName()) {
      if (!first) sb.append(", ");
      sb.append("displayName:");
      if (this.displayName == null) {
        sb.append("null");
      } else {
        sb.append(this.displayName);
      }
      first = false;
    }
    if (isSetEmail()) {
      if (!first) sb.append(", ");
      sb.append("email:");
      if (this.email == null) {
        sb.append("null");
      } else {
        sb.append(this.email);
      }
      first = false;
    }
    if (isSetSpace()) {
      if (!first) sb.append(", ");
      sb.append("space:");
      sb.append(this.space);
      first = false;
    }
    if (isSetUserType()) {
      if (!first) sb.append(", ");
      sb.append("userType:");
      if (this.userType == null) {
        sb.append("null");
      } else {
        sb.append(this.userType);
      }
      first = false;
    }
    if (!first) sb.append(", ");
    sb.append("departmentIds:");
    if (this.departmentIds == null) {
      sb.append("null");
    } else {
      sb.append(this.departmentIds);
    }
    first = false;
    if (isSetDepartmentNames()) {
      if (!first) sb.append(", ");
      sb.append("departmentNames:");
      if (this.departmentNames == null) {
        sb.append("null");
      } else {
        sb.append(this.departmentNames);
      }
      first = false;
    }
    if (isSetStatus()) {
      if (!first) sb.append(", ");
      sb.append("status:");
      if (this.status == null) {
        sb.append("null");
      } else {
        sb.append(this.status);
      }
      first = false;
    }
    if (isSetUsedSize()) {
      if (!first) sb.append(", ");
      sb.append("usedSize:");
      sb.append(this.usedSize);
      first = false;
    }
    if (isSetPriority()) {
      if (!first) sb.append(", ");
      sb.append("priority:");
      sb.append(this.priority);
      first = false;
    }
    if (isSetCsfLevel()) {
      if (!first) sb.append(", ");
      sb.append("csfLevel:");
      sb.append(this.csfLevel);
      first = false;
    }
    if (!first) sb.append(", ");
    sb.append("pwdControl:");
    sb.append(this.pwdControl);
    first = false;
    if (isSetOssInfo()) {
      if (!first) sb.append(", ");
      sb.append("ossInfo:");
      if (this.ossInfo == null) {
        sb.append("null");
      } else {
        sb.append(this.ossInfo);
      }
      first = false;
    }
    if (isSetLimitSpaceInfo()) {
      if (!first) sb.append(", ");
      sb.append("limitSpaceInfo:");
      if (this.limitSpaceInfo == null) {
        sb.append("null");
      } else {
        sb.append(this.limitSpaceInfo);
      }
      first = false;
    }
    if (isSetCreateTime()) {
      if (!first) sb.append(", ");
      sb.append("createTime:");
      sb.append(this.createTime);
      first = false;
    }
    if (isSetFreezeStatus()) {
      if (!first) sb.append(", ");
      sb.append("freezeStatus:");
      sb.append(this.freezeStatus);
      first = false;
    }
    if (isSetTelNumber()) {
      if (!first) sb.append(", ");
      sb.append("telNumber:");
      if (this.telNumber == null) {
        sb.append("null");
      } else {
        sb.append(this.telNumber);
      }
      first = false;
    }
    if (isSetRoles()) {
      if (!first) sb.append(", ");
      sb.append("roles:");
      if (this.roles == null) {
        sb.append("null");
      } else {
        sb.append(this.roles);
      }
      first = false;
    }
    if (isSetExpireTime()) {
      if (!first) sb.append(", ");
      sb.append("expireTime:");
      sb.append(this.expireTime);
      first = false;
    }
    if (isSetRemark()) {
      if (!first) sb.append(", ");
      sb.append("remark:");
      if (this.remark == null) {
        sb.append("null");
      } else {
        sb.append(this.remark);
      }
      first = false;
    }
    if (isSetIdcardNumber()) {
      if (!first) sb.append(", ");
      sb.append("idcardNumber:");
      if (this.idcardNumber == null) {
        sb.append("null");
      } else {
        sb.append(this.idcardNumber);
      }
      first = false;
    }
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    if (loginName == null) {
      throw new org.apache.thrift.protocol.TProtocolException("Required field 'loginName' was not present! Struct: " + toString());
    }
    if (departmentIds == null) {
      throw new org.apache.thrift.protocol.TProtocolException("Required field 'departmentIds' was not present! Struct: " + toString());
    }
    // alas, we cannot check 'pwdControl' because it's a primitive and you chose the non-beans generator.
    // check for sub-struct validity
    if (ossInfo != null) {
      ossInfo.validate();
    }
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, java.lang.ClassNotFoundException {
    try {
      // it doesn't seem like you should have to do this, but java serialization is wacky, and doesn't call the default constructor.
      __isset_bitfield = 0;
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class ncTUsrmUserInfoStandardSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    public ncTUsrmUserInfoStandardScheme getScheme() {
      return new ncTUsrmUserInfoStandardScheme();
    }
  }

  private static class ncTUsrmUserInfoStandardScheme extends org.apache.thrift.scheme.StandardScheme<ncTUsrmUserInfo> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, ncTUsrmUserInfo struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // LOGIN_NAME
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.loginName = iprot.readString();
              struct.setLoginNameIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 2: // DISPLAY_NAME
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.displayName = iprot.readString();
              struct.setDisplayNameIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 3: // EMAIL
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.email = iprot.readString();
              struct.setEmailIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 4: // SPACE
            if (schemeField.type == org.apache.thrift.protocol.TType.I64) {
              struct.space = iprot.readI64();
              struct.setSpaceIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 5: // USER_TYPE
            if (schemeField.type == org.apache.thrift.protocol.TType.I32) {
              struct.userType = com.aishu.wf.core.thrift.sharemgnt.ncTUsrmUserType.findByValue(iprot.readI32());
              struct.setUserTypeIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 6: // DEPARTMENT_IDS
            if (schemeField.type == org.apache.thrift.protocol.TType.LIST) {
              {
                org.apache.thrift.protocol.TList _list16 = iprot.readListBegin();
                struct.departmentIds = new java.util.ArrayList<java.lang.String>(_list16.size);
                @org.apache.thrift.annotation.Nullable java.lang.String _elem17;
                for (int _i18 = 0; _i18 < _list16.size; ++_i18)
                {
                  _elem17 = iprot.readString();
                  struct.departmentIds.add(_elem17);
                }
                iprot.readListEnd();
              }
              struct.setDepartmentIdsIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 7: // DEPARTMENT_NAMES
            if (schemeField.type == org.apache.thrift.protocol.TType.LIST) {
              {
                org.apache.thrift.protocol.TList _list19 = iprot.readListBegin();
                struct.departmentNames = new java.util.ArrayList<java.lang.String>(_list19.size);
                @org.apache.thrift.annotation.Nullable java.lang.String _elem20;
                for (int _i21 = 0; _i21 < _list19.size; ++_i21)
                {
                  _elem20 = iprot.readString();
                  struct.departmentNames.add(_elem20);
                }
                iprot.readListEnd();
              }
              struct.setDepartmentNamesIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 8: // STATUS
            if (schemeField.type == org.apache.thrift.protocol.TType.I32) {
              struct.status = com.aishu.wf.core.thrift.sharemgnt.ncTUsrmUserStatus.findByValue(iprot.readI32());
              struct.setStatusIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 9: // USED_SIZE
            if (schemeField.type == org.apache.thrift.protocol.TType.I64) {
              struct.usedSize = iprot.readI64();
              struct.setUsedSizeIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 10: // PRIORITY
            if (schemeField.type == org.apache.thrift.protocol.TType.I32) {
              struct.priority = iprot.readI32();
              struct.setPriorityIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 11: // CSF_LEVEL
            if (schemeField.type == org.apache.thrift.protocol.TType.I32) {
              struct.csfLevel = iprot.readI32();
              struct.setCsfLevelIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 12: // PWD_CONTROL
            if (schemeField.type == org.apache.thrift.protocol.TType.BOOL) {
              struct.pwdControl = iprot.readBool();
              struct.setPwdControlIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 13: // OSS_INFO
            if (schemeField.type == org.apache.thrift.protocol.TType.STRUCT) {
              struct.ossInfo = new ncTUsrmOSSInfo();
              struct.ossInfo.read(iprot);
              struct.setOssInfoIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 14: // LIMIT_SPACE_INFO
            if (schemeField.type == org.apache.thrift.protocol.TType.STRUCT) {
              struct.limitSpaceInfo = new ncTLimitSpaceInfo();
              struct.limitSpaceInfo.read(iprot);
              struct.setLimitSpaceInfoIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 15: // CREATE_TIME
            if (schemeField.type == org.apache.thrift.protocol.TType.I64) {
              struct.createTime = iprot.readI64();
              struct.setCreateTimeIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 16: // FREEZE_STATUS
            if (schemeField.type == org.apache.thrift.protocol.TType.BOOL) {
              struct.freezeStatus = iprot.readBool();
              struct.setFreezeStatusIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 17: // TEL_NUMBER
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.telNumber = iprot.readString();
              struct.setTelNumberIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 18: // ROLES
            if (schemeField.type == org.apache.thrift.protocol.TType.LIST) {
              {
                org.apache.thrift.protocol.TList _list22 = iprot.readListBegin();
                struct.roles = new java.util.ArrayList<ncTRoleInfo>(_list22.size);
                @org.apache.thrift.annotation.Nullable ncTRoleInfo _elem23;
                for (int _i24 = 0; _i24 < _list22.size; ++_i24)
                {
                  _elem23 = new ncTRoleInfo();
                  _elem23.read(iprot);
                  struct.roles.add(_elem23);
                }
                iprot.readListEnd();
              }
              struct.setRolesIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 19: // EXPIRE_TIME
            if (schemeField.type == org.apache.thrift.protocol.TType.I32) {
              struct.expireTime = iprot.readI32();
              struct.setExpireTimeIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 20: // REMARK
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.remark = iprot.readString();
              struct.setRemarkIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 21: // IDCARD_NUMBER
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.idcardNumber = iprot.readString();
              struct.setIdcardNumberIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      if (!struct.isSetPwdControl()) {
        throw new org.apache.thrift.protocol.TProtocolException("Required field 'pwdControl' was not found in serialized data! Struct: " + toString());
      }
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, ncTUsrmUserInfo struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      if (struct.loginName != null) {
        oprot.writeFieldBegin(LOGIN_NAME_FIELD_DESC);
        oprot.writeString(struct.loginName);
        oprot.writeFieldEnd();
      }
      if (struct.displayName != null) {
        if (struct.isSetDisplayName()) {
          oprot.writeFieldBegin(DISPLAY_NAME_FIELD_DESC);
          oprot.writeString(struct.displayName);
          oprot.writeFieldEnd();
        }
      }
      if (struct.email != null) {
        if (struct.isSetEmail()) {
          oprot.writeFieldBegin(EMAIL_FIELD_DESC);
          oprot.writeString(struct.email);
          oprot.writeFieldEnd();
        }
      }
      if (struct.isSetSpace()) {
        oprot.writeFieldBegin(SPACE_FIELD_DESC);
        oprot.writeI64(struct.space);
        oprot.writeFieldEnd();
      }
      if (struct.userType != null) {
        if (struct.isSetUserType()) {
          oprot.writeFieldBegin(USER_TYPE_FIELD_DESC);
          oprot.writeI32(struct.userType.getValue());
          oprot.writeFieldEnd();
        }
      }
      if (struct.departmentIds != null) {
        oprot.writeFieldBegin(DEPARTMENT_IDS_FIELD_DESC);
        {
          oprot.writeListBegin(new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.STRING, struct.departmentIds.size()));
          for (java.lang.String _iter25 : struct.departmentIds)
          {
            oprot.writeString(_iter25);
          }
          oprot.writeListEnd();
        }
        oprot.writeFieldEnd();
      }
      if (struct.departmentNames != null) {
        if (struct.isSetDepartmentNames()) {
          oprot.writeFieldBegin(DEPARTMENT_NAMES_FIELD_DESC);
          {
            oprot.writeListBegin(new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.STRING, struct.departmentNames.size()));
            for (java.lang.String _iter26 : struct.departmentNames)
            {
              oprot.writeString(_iter26);
            }
            oprot.writeListEnd();
          }
          oprot.writeFieldEnd();
        }
      }
      if (struct.status != null) {
        if (struct.isSetStatus()) {
          oprot.writeFieldBegin(STATUS_FIELD_DESC);
          oprot.writeI32(struct.status.getValue());
          oprot.writeFieldEnd();
        }
      }
      if (struct.isSetUsedSize()) {
        oprot.writeFieldBegin(USED_SIZE_FIELD_DESC);
        oprot.writeI64(struct.usedSize);
        oprot.writeFieldEnd();
      }
      if (struct.isSetPriority()) {
        oprot.writeFieldBegin(PRIORITY_FIELD_DESC);
        oprot.writeI32(struct.priority);
        oprot.writeFieldEnd();
      }
      if (struct.isSetCsfLevel()) {
        oprot.writeFieldBegin(CSF_LEVEL_FIELD_DESC);
        oprot.writeI32(struct.csfLevel);
        oprot.writeFieldEnd();
      }
      oprot.writeFieldBegin(PWD_CONTROL_FIELD_DESC);
      oprot.writeBool(struct.pwdControl);
      oprot.writeFieldEnd();
      if (struct.ossInfo != null) {
        if (struct.isSetOssInfo()) {
          oprot.writeFieldBegin(OSS_INFO_FIELD_DESC);
          struct.ossInfo.write(oprot);
          oprot.writeFieldEnd();
        }
      }
      if (struct.limitSpaceInfo != null) {
        if (struct.isSetLimitSpaceInfo()) {
          oprot.writeFieldBegin(LIMIT_SPACE_INFO_FIELD_DESC);
          struct.limitSpaceInfo.write(oprot);
          oprot.writeFieldEnd();
        }
      }
      if (struct.isSetCreateTime()) {
        oprot.writeFieldBegin(CREATE_TIME_FIELD_DESC);
        oprot.writeI64(struct.createTime);
        oprot.writeFieldEnd();
      }
      if (struct.isSetFreezeStatus()) {
        oprot.writeFieldBegin(FREEZE_STATUS_FIELD_DESC);
        oprot.writeBool(struct.freezeStatus);
        oprot.writeFieldEnd();
      }
      if (struct.telNumber != null) {
        if (struct.isSetTelNumber()) {
          oprot.writeFieldBegin(TEL_NUMBER_FIELD_DESC);
          oprot.writeString(struct.telNumber);
          oprot.writeFieldEnd();
        }
      }
      if (struct.roles != null) {
        if (struct.isSetRoles()) {
          oprot.writeFieldBegin(ROLES_FIELD_DESC);
          {
            oprot.writeListBegin(new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.STRUCT, struct.roles.size()));
            for (ncTRoleInfo _iter27 : struct.roles)
            {
              _iter27.write(oprot);
            }
            oprot.writeListEnd();
          }
          oprot.writeFieldEnd();
        }
      }
      if (struct.isSetExpireTime()) {
        oprot.writeFieldBegin(EXPIRE_TIME_FIELD_DESC);
        oprot.writeI32(struct.expireTime);
        oprot.writeFieldEnd();
      }
      if (struct.remark != null) {
        if (struct.isSetRemark()) {
          oprot.writeFieldBegin(REMARK_FIELD_DESC);
          oprot.writeString(struct.remark);
          oprot.writeFieldEnd();
        }
      }
      if (struct.idcardNumber != null) {
        if (struct.isSetIdcardNumber()) {
          oprot.writeFieldBegin(IDCARD_NUMBER_FIELD_DESC);
          oprot.writeString(struct.idcardNumber);
          oprot.writeFieldEnd();
        }
      }
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class ncTUsrmUserInfoTupleSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    public ncTUsrmUserInfoTupleScheme getScheme() {
      return new ncTUsrmUserInfoTupleScheme();
    }
  }

  private static class ncTUsrmUserInfoTupleScheme extends org.apache.thrift.scheme.TupleScheme<ncTUsrmUserInfo> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, ncTUsrmUserInfo struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol oprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      oprot.writeString(struct.loginName);
      {
        oprot.writeI32(struct.departmentIds.size());
        for (java.lang.String _iter28 : struct.departmentIds)
        {
          oprot.writeString(_iter28);
        }
      }
      oprot.writeBool(struct.pwdControl);
      java.util.BitSet optionals = new java.util.BitSet();
      if (struct.isSetDisplayName()) {
        optionals.set(0);
      }
      if (struct.isSetEmail()) {
        optionals.set(1);
      }
      if (struct.isSetSpace()) {
        optionals.set(2);
      }
      if (struct.isSetUserType()) {
        optionals.set(3);
      }
      if (struct.isSetDepartmentNames()) {
        optionals.set(4);
      }
      if (struct.isSetStatus()) {
        optionals.set(5);
      }
      if (struct.isSetUsedSize()) {
        optionals.set(6);
      }
      if (struct.isSetPriority()) {
        optionals.set(7);
      }
      if (struct.isSetCsfLevel()) {
        optionals.set(8);
      }
      if (struct.isSetOssInfo()) {
        optionals.set(9);
      }
      if (struct.isSetLimitSpaceInfo()) {
        optionals.set(10);
      }
      if (struct.isSetCreateTime()) {
        optionals.set(11);
      }
      if (struct.isSetFreezeStatus()) {
        optionals.set(12);
      }
      if (struct.isSetTelNumber()) {
        optionals.set(13);
      }
      if (struct.isSetRoles()) {
        optionals.set(14);
      }
      if (struct.isSetExpireTime()) {
        optionals.set(15);
      }
      if (struct.isSetRemark()) {
        optionals.set(16);
      }
      if (struct.isSetIdcardNumber()) {
        optionals.set(17);
      }
      oprot.writeBitSet(optionals, 18);
      if (struct.isSetDisplayName()) {
        oprot.writeString(struct.displayName);
      }
      if (struct.isSetEmail()) {
        oprot.writeString(struct.email);
      }
      if (struct.isSetSpace()) {
        oprot.writeI64(struct.space);
      }
      if (struct.isSetUserType()) {
        oprot.writeI32(struct.userType.getValue());
      }
      if (struct.isSetDepartmentNames()) {
        {
          oprot.writeI32(struct.departmentNames.size());
          for (java.lang.String _iter29 : struct.departmentNames)
          {
            oprot.writeString(_iter29);
          }
        }
      }
      if (struct.isSetStatus()) {
        oprot.writeI32(struct.status.getValue());
      }
      if (struct.isSetUsedSize()) {
        oprot.writeI64(struct.usedSize);
      }
      if (struct.isSetPriority()) {
        oprot.writeI32(struct.priority);
      }
      if (struct.isSetCsfLevel()) {
        oprot.writeI32(struct.csfLevel);
      }
      if (struct.isSetOssInfo()) {
        struct.ossInfo.write(oprot);
      }
      if (struct.isSetLimitSpaceInfo()) {
        struct.limitSpaceInfo.write(oprot);
      }
      if (struct.isSetCreateTime()) {
        oprot.writeI64(struct.createTime);
      }
      if (struct.isSetFreezeStatus()) {
        oprot.writeBool(struct.freezeStatus);
      }
      if (struct.isSetTelNumber()) {
        oprot.writeString(struct.telNumber);
      }
      if (struct.isSetRoles()) {
        {
          oprot.writeI32(struct.roles.size());
          for (ncTRoleInfo _iter30 : struct.roles)
          {
            _iter30.write(oprot);
          }
        }
      }
      if (struct.isSetExpireTime()) {
        oprot.writeI32(struct.expireTime);
      }
      if (struct.isSetRemark()) {
        oprot.writeString(struct.remark);
      }
      if (struct.isSetIdcardNumber()) {
        oprot.writeString(struct.idcardNumber);
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, ncTUsrmUserInfo struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol iprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      struct.loginName = iprot.readString();
      struct.setLoginNameIsSet(true);
      {
        org.apache.thrift.protocol.TList _list31 = iprot.readListBegin(org.apache.thrift.protocol.TType.STRING);
        struct.departmentIds = new java.util.ArrayList<java.lang.String>(_list31.size);
        @org.apache.thrift.annotation.Nullable java.lang.String _elem32;
        for (int _i33 = 0; _i33 < _list31.size; ++_i33)
        {
          _elem32 = iprot.readString();
          struct.departmentIds.add(_elem32);
        }
      }
      struct.setDepartmentIdsIsSet(true);
      struct.pwdControl = iprot.readBool();
      struct.setPwdControlIsSet(true);
      java.util.BitSet incoming = iprot.readBitSet(18);
      if (incoming.get(0)) {
        struct.displayName = iprot.readString();
        struct.setDisplayNameIsSet(true);
      }
      if (incoming.get(1)) {
        struct.email = iprot.readString();
        struct.setEmailIsSet(true);
      }
      if (incoming.get(2)) {
        struct.space = iprot.readI64();
        struct.setSpaceIsSet(true);
      }
      if (incoming.get(3)) {
        struct.userType = com.aishu.wf.core.thrift.sharemgnt.ncTUsrmUserType.findByValue(iprot.readI32());
        struct.setUserTypeIsSet(true);
      }
      if (incoming.get(4)) {
        {
          org.apache.thrift.protocol.TList _list34 = iprot.readListBegin(org.apache.thrift.protocol.TType.STRING);
          struct.departmentNames = new java.util.ArrayList<java.lang.String>(_list34.size);
          @org.apache.thrift.annotation.Nullable java.lang.String _elem35;
          for (int _i36 = 0; _i36 < _list34.size; ++_i36)
          {
            _elem35 = iprot.readString();
            struct.departmentNames.add(_elem35);
          }
        }
        struct.setDepartmentNamesIsSet(true);
      }
      if (incoming.get(5)) {
        struct.status = com.aishu.wf.core.thrift.sharemgnt.ncTUsrmUserStatus.findByValue(iprot.readI32());
        struct.setStatusIsSet(true);
      }
      if (incoming.get(6)) {
        struct.usedSize = iprot.readI64();
        struct.setUsedSizeIsSet(true);
      }
      if (incoming.get(7)) {
        struct.priority = iprot.readI32();
        struct.setPriorityIsSet(true);
      }
      if (incoming.get(8)) {
        struct.csfLevel = iprot.readI32();
        struct.setCsfLevelIsSet(true);
      }
      if (incoming.get(9)) {
        struct.ossInfo = new ncTUsrmOSSInfo();
        struct.ossInfo.read(iprot);
        struct.setOssInfoIsSet(true);
      }
      if (incoming.get(10)) {
        struct.limitSpaceInfo = new ncTLimitSpaceInfo();
        struct.limitSpaceInfo.read(iprot);
        struct.setLimitSpaceInfoIsSet(true);
      }
      if (incoming.get(11)) {
        struct.createTime = iprot.readI64();
        struct.setCreateTimeIsSet(true);
      }
      if (incoming.get(12)) {
        struct.freezeStatus = iprot.readBool();
        struct.setFreezeStatusIsSet(true);
      }
      if (incoming.get(13)) {
        struct.telNumber = iprot.readString();
        struct.setTelNumberIsSet(true);
      }
      if (incoming.get(14)) {
        {
          org.apache.thrift.protocol.TList _list37 = iprot.readListBegin(org.apache.thrift.protocol.TType.STRUCT);
          struct.roles = new java.util.ArrayList<ncTRoleInfo>(_list37.size);
          @org.apache.thrift.annotation.Nullable ncTRoleInfo _elem38;
          for (int _i39 = 0; _i39 < _list37.size; ++_i39)
          {
            _elem38 = new ncTRoleInfo();
            _elem38.read(iprot);
            struct.roles.add(_elem38);
          }
        }
        struct.setRolesIsSet(true);
      }
      if (incoming.get(15)) {
        struct.expireTime = iprot.readI32();
        struct.setExpireTimeIsSet(true);
      }
      if (incoming.get(16)) {
        struct.remark = iprot.readString();
        struct.setRemarkIsSet(true);
      }
      if (incoming.get(17)) {
        struct.idcardNumber = iprot.readString();
        struct.setIdcardNumberIsSet(true);
      }
    }
  }

  private static <S extends org.apache.thrift.scheme.IScheme> S scheme(org.apache.thrift.protocol.TProtocol proto) {
    return (org.apache.thrift.scheme.StandardScheme.class.equals(proto.getScheme()) ? STANDARD_SCHEME_FACTORY : TUPLE_SCHEME_FACTORY).getScheme();
  }
}

