/**
 * Autogenerated by Thrift Compiler (0.14.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.aishu.wf.core.thrift.evfs;

@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked", "unused"})
/**
 * 外链文件信息
 */
@javax.annotation.Generated(value = "Autogenerated by Thrift Compiler (0.14.2)", date = "2023-06-06")
public class ncTEVFSOutLinkFileInfo implements org.apache.thrift.TBase<ncTEVFSOutLinkFileInfo, ncTEVFSOutLinkFileInfo._Fields>, java.io.Serializable, Cloneable, Comparable<ncTEVFSOutLinkFileInfo> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("ncTEVFSOutLinkFileInfo");

  private static final org.apache.thrift.protocol.TField CREATOR_FIELD_DESC = new org.apache.thrift.protocol.TField("creator", org.apache.thrift.protocol.TType.STRING, (short)1);
  private static final org.apache.thrift.protocol.TField EDITOR_FIELD_DESC = new org.apache.thrift.protocol.TField("editor", org.apache.thrift.protocol.TType.STRING, (short)2);
  private static final org.apache.thrift.protocol.TField MODIFIED_FIELD_DESC = new org.apache.thrift.protocol.TField("modified", org.apache.thrift.protocol.TType.I64, (short)3);
  private static final org.apache.thrift.protocol.TField SHARER_FIELD_DESC = new org.apache.thrift.protocol.TField("sharer", org.apache.thrift.protocol.TType.STRING, (short)4);
  private static final org.apache.thrift.protocol.TField SHARED_OBJ_FIELD_DESC = new org.apache.thrift.protocol.TField("sharedObj", org.apache.thrift.protocol.TType.STRING, (short)5);

  private static final org.apache.thrift.scheme.SchemeFactory STANDARD_SCHEME_FACTORY = new ncTEVFSOutLinkFileInfoStandardSchemeFactory();
  private static final org.apache.thrift.scheme.SchemeFactory TUPLE_SCHEME_FACTORY = new ncTEVFSOutLinkFileInfoTupleSchemeFactory();

  public @org.apache.thrift.annotation.Nullable java.lang.String creator; // required
  public @org.apache.thrift.annotation.Nullable java.lang.String editor; // required
  public long modified; // required
  public @org.apache.thrift.annotation.Nullable java.lang.String sharer; // required
  public @org.apache.thrift.annotation.Nullable java.lang.String sharedObj; // required

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    CREATOR((short)1, "creator"),
    EDITOR((short)2, "editor"),
    MODIFIED((short)3, "modified"),
    SHARER((short)4, "sharer"),
    SHARED_OBJ((short)5, "sharedObj");

    private static final java.util.Map<java.lang.String, _Fields> byName = new java.util.HashMap<java.lang.String, _Fields>();

    static {
      for (_Fields field : java.util.EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    @org.apache.thrift.annotation.Nullable
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // CREATOR
          return CREATOR;
        case 2: // EDITOR
          return EDITOR;
        case 3: // MODIFIED
          return MODIFIED;
        case 4: // SHARER
          return SHARER;
        case 5: // SHARED_OBJ
          return SHARED_OBJ;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new java.lang.IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    @org.apache.thrift.annotation.Nullable
    public static _Fields findByName(java.lang.String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final java.lang.String _fieldName;

    _Fields(short thriftId, java.lang.String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public java.lang.String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  private static final int __MODIFIED_ISSET_ID = 0;
  private byte __isset_bitfield = 0;
  public static final java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new java.util.EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.CREATOR, new org.apache.thrift.meta_data.FieldMetaData("creator", org.apache.thrift.TFieldRequirementType.REQUIRED, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.EDITOR, new org.apache.thrift.meta_data.FieldMetaData("editor", org.apache.thrift.TFieldRequirementType.REQUIRED, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.MODIFIED, new org.apache.thrift.meta_data.FieldMetaData("modified", org.apache.thrift.TFieldRequirementType.REQUIRED, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I64)));
    tmpMap.put(_Fields.SHARER, new org.apache.thrift.meta_data.FieldMetaData("sharer", org.apache.thrift.TFieldRequirementType.REQUIRED, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.SHARED_OBJ, new org.apache.thrift.meta_data.FieldMetaData("sharedObj", org.apache.thrift.TFieldRequirementType.REQUIRED, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    metaDataMap = java.util.Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(ncTEVFSOutLinkFileInfo.class, metaDataMap);
  }

  public ncTEVFSOutLinkFileInfo() {
  }

  public ncTEVFSOutLinkFileInfo(
    java.lang.String creator,
    java.lang.String editor,
    long modified,
    java.lang.String sharer,
    java.lang.String sharedObj)
  {
    this();
    this.creator = creator;
    this.editor = editor;
    this.modified = modified;
    setModifiedIsSet(true);
    this.sharer = sharer;
    this.sharedObj = sharedObj;
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public ncTEVFSOutLinkFileInfo(ncTEVFSOutLinkFileInfo other) {
    __isset_bitfield = other.__isset_bitfield;
    if (other.isSetCreator()) {
      this.creator = other.creator;
    }
    if (other.isSetEditor()) {
      this.editor = other.editor;
    }
    this.modified = other.modified;
    if (other.isSetSharer()) {
      this.sharer = other.sharer;
    }
    if (other.isSetSharedObj()) {
      this.sharedObj = other.sharedObj;
    }
  }

  public ncTEVFSOutLinkFileInfo deepCopy() {
    return new ncTEVFSOutLinkFileInfo(this);
  }

  @Override
  public void clear() {
    this.creator = null;
    this.editor = null;
    setModifiedIsSet(false);
    this.modified = 0;
    this.sharer = null;
    this.sharedObj = null;
  }

  @org.apache.thrift.annotation.Nullable
  public java.lang.String getCreator() {
    return this.creator;
  }

  public ncTEVFSOutLinkFileInfo setCreator(@org.apache.thrift.annotation.Nullable java.lang.String creator) {
    this.creator = creator;
    return this;
  }

  public void unsetCreator() {
    this.creator = null;
  }

  /** Returns true if field creator is set (has been assigned a value) and false otherwise */
  public boolean isSetCreator() {
    return this.creator != null;
  }

  public void setCreatorIsSet(boolean value) {
    if (!value) {
      this.creator = null;
    }
  }

  @org.apache.thrift.annotation.Nullable
  public java.lang.String getEditor() {
    return this.editor;
  }

  public ncTEVFSOutLinkFileInfo setEditor(@org.apache.thrift.annotation.Nullable java.lang.String editor) {
    this.editor = editor;
    return this;
  }

  public void unsetEditor() {
    this.editor = null;
  }

  /** Returns true if field editor is set (has been assigned a value) and false otherwise */
  public boolean isSetEditor() {
    return this.editor != null;
  }

  public void setEditorIsSet(boolean value) {
    if (!value) {
      this.editor = null;
    }
  }

  public long getModified() {
    return this.modified;
  }

  public ncTEVFSOutLinkFileInfo setModified(long modified) {
    this.modified = modified;
    setModifiedIsSet(true);
    return this;
  }

  public void unsetModified() {
    __isset_bitfield = org.apache.thrift.EncodingUtils.clearBit(__isset_bitfield, __MODIFIED_ISSET_ID);
  }

  /** Returns true if field modified is set (has been assigned a value) and false otherwise */
  public boolean isSetModified() {
    return org.apache.thrift.EncodingUtils.testBit(__isset_bitfield, __MODIFIED_ISSET_ID);
  }

  public void setModifiedIsSet(boolean value) {
    __isset_bitfield = org.apache.thrift.EncodingUtils.setBit(__isset_bitfield, __MODIFIED_ISSET_ID, value);
  }

  @org.apache.thrift.annotation.Nullable
  public java.lang.String getSharer() {
    return this.sharer;
  }

  public ncTEVFSOutLinkFileInfo setSharer(@org.apache.thrift.annotation.Nullable java.lang.String sharer) {
    this.sharer = sharer;
    return this;
  }

  public void unsetSharer() {
    this.sharer = null;
  }

  /** Returns true if field sharer is set (has been assigned a value) and false otherwise */
  public boolean isSetSharer() {
    return this.sharer != null;
  }

  public void setSharerIsSet(boolean value) {
    if (!value) {
      this.sharer = null;
    }
  }

  @org.apache.thrift.annotation.Nullable
  public java.lang.String getSharedObj() {
    return this.sharedObj;
  }

  public ncTEVFSOutLinkFileInfo setSharedObj(@org.apache.thrift.annotation.Nullable java.lang.String sharedObj) {
    this.sharedObj = sharedObj;
    return this;
  }

  public void unsetSharedObj() {
    this.sharedObj = null;
  }

  /** Returns true if field sharedObj is set (has been assigned a value) and false otherwise */
  public boolean isSetSharedObj() {
    return this.sharedObj != null;
  }

  public void setSharedObjIsSet(boolean value) {
    if (!value) {
      this.sharedObj = null;
    }
  }

  public void setFieldValue(_Fields field, @org.apache.thrift.annotation.Nullable java.lang.Object value) {
    switch (field) {
    case CREATOR:
      if (value == null) {
        unsetCreator();
      } else {
        setCreator((java.lang.String)value);
      }
      break;

    case EDITOR:
      if (value == null) {
        unsetEditor();
      } else {
        setEditor((java.lang.String)value);
      }
      break;

    case MODIFIED:
      if (value == null) {
        unsetModified();
      } else {
        setModified((java.lang.Long)value);
      }
      break;

    case SHARER:
      if (value == null) {
        unsetSharer();
      } else {
        setSharer((java.lang.String)value);
      }
      break;

    case SHARED_OBJ:
      if (value == null) {
        unsetSharedObj();
      } else {
        setSharedObj((java.lang.String)value);
      }
      break;

    }
  }

  @org.apache.thrift.annotation.Nullable
  public java.lang.Object getFieldValue(_Fields field) {
    switch (field) {
    case CREATOR:
      return getCreator();

    case EDITOR:
      return getEditor();

    case MODIFIED:
      return getModified();

    case SHARER:
      return getSharer();

    case SHARED_OBJ:
      return getSharedObj();

    }
    throw new java.lang.IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new java.lang.IllegalArgumentException();
    }

    switch (field) {
    case CREATOR:
      return isSetCreator();
    case EDITOR:
      return isSetEditor();
    case MODIFIED:
      return isSetModified();
    case SHARER:
      return isSetSharer();
    case SHARED_OBJ:
      return isSetSharedObj();
    }
    throw new java.lang.IllegalStateException();
  }

  @Override
  public boolean equals(java.lang.Object that) {
    if (that instanceof ncTEVFSOutLinkFileInfo)
      return this.equals((ncTEVFSOutLinkFileInfo)that);
    return false;
  }

  public boolean equals(ncTEVFSOutLinkFileInfo that) {
    if (that == null)
      return false;
    if (this == that)
      return true;

    boolean this_present_creator = true && this.isSetCreator();
    boolean that_present_creator = true && that.isSetCreator();
    if (this_present_creator || that_present_creator) {
      if (!(this_present_creator && that_present_creator))
        return false;
      if (!this.creator.equals(that.creator))
        return false;
    }

    boolean this_present_editor = true && this.isSetEditor();
    boolean that_present_editor = true && that.isSetEditor();
    if (this_present_editor || that_present_editor) {
      if (!(this_present_editor && that_present_editor))
        return false;
      if (!this.editor.equals(that.editor))
        return false;
    }

    boolean this_present_modified = true;
    boolean that_present_modified = true;
    if (this_present_modified || that_present_modified) {
      if (!(this_present_modified && that_present_modified))
        return false;
      if (this.modified != that.modified)
        return false;
    }

    boolean this_present_sharer = true && this.isSetSharer();
    boolean that_present_sharer = true && that.isSetSharer();
    if (this_present_sharer || that_present_sharer) {
      if (!(this_present_sharer && that_present_sharer))
        return false;
      if (!this.sharer.equals(that.sharer))
        return false;
    }

    boolean this_present_sharedObj = true && this.isSetSharedObj();
    boolean that_present_sharedObj = true && that.isSetSharedObj();
    if (this_present_sharedObj || that_present_sharedObj) {
      if (!(this_present_sharedObj && that_present_sharedObj))
        return false;
      if (!this.sharedObj.equals(that.sharedObj))
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    int hashCode = 1;

    hashCode = hashCode * 8191 + ((isSetCreator()) ? 131071 : 524287);
    if (isSetCreator())
      hashCode = hashCode * 8191 + creator.hashCode();

    hashCode = hashCode * 8191 + ((isSetEditor()) ? 131071 : 524287);
    if (isSetEditor())
      hashCode = hashCode * 8191 + editor.hashCode();

    hashCode = hashCode * 8191 + org.apache.thrift.TBaseHelper.hashCode(modified);

    hashCode = hashCode * 8191 + ((isSetSharer()) ? 131071 : 524287);
    if (isSetSharer())
      hashCode = hashCode * 8191 + sharer.hashCode();

    hashCode = hashCode * 8191 + ((isSetSharedObj()) ? 131071 : 524287);
    if (isSetSharedObj())
      hashCode = hashCode * 8191 + sharedObj.hashCode();

    return hashCode;
  }

  @Override
  public int compareTo(ncTEVFSOutLinkFileInfo other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = java.lang.Boolean.compare(isSetCreator(), other.isSetCreator());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetCreator()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.creator, other.creator);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.compare(isSetEditor(), other.isSetEditor());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetEditor()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.editor, other.editor);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.compare(isSetModified(), other.isSetModified());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetModified()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.modified, other.modified);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.compare(isSetSharer(), other.isSetSharer());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetSharer()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.sharer, other.sharer);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.compare(isSetSharedObj(), other.isSetSharedObj());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetSharedObj()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.sharedObj, other.sharedObj);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  @org.apache.thrift.annotation.Nullable
  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    scheme(iprot).read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    scheme(oprot).write(oprot, this);
  }

  @Override
  public java.lang.String toString() {
    java.lang.StringBuilder sb = new java.lang.StringBuilder("ncTEVFSOutLinkFileInfo(");
    boolean first = true;

    sb.append("creator:");
    if (this.creator == null) {
      sb.append("null");
    } else {
      sb.append(this.creator);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("editor:");
    if (this.editor == null) {
      sb.append("null");
    } else {
      sb.append(this.editor);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("modified:");
    sb.append(this.modified);
    first = false;
    if (!first) sb.append(", ");
    sb.append("sharer:");
    if (this.sharer == null) {
      sb.append("null");
    } else {
      sb.append(this.sharer);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("sharedObj:");
    if (this.sharedObj == null) {
      sb.append("null");
    } else {
      sb.append(this.sharedObj);
    }
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    if (creator == null) {
      throw new org.apache.thrift.protocol.TProtocolException("Required field 'creator' was not present! Struct: " + toString());
    }
    if (editor == null) {
      throw new org.apache.thrift.protocol.TProtocolException("Required field 'editor' was not present! Struct: " + toString());
    }
    // alas, we cannot check 'modified' because it's a primitive and you chose the non-beans generator.
    if (sharer == null) {
      throw new org.apache.thrift.protocol.TProtocolException("Required field 'sharer' was not present! Struct: " + toString());
    }
    if (sharedObj == null) {
      throw new org.apache.thrift.protocol.TProtocolException("Required field 'sharedObj' was not present! Struct: " + toString());
    }
    // check for sub-struct validity
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, java.lang.ClassNotFoundException {
    try {
      // it doesn't seem like you should have to do this, but java serialization is wacky, and doesn't call the default constructor.
      __isset_bitfield = 0;
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class ncTEVFSOutLinkFileInfoStandardSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    public ncTEVFSOutLinkFileInfoStandardScheme getScheme() {
      return new ncTEVFSOutLinkFileInfoStandardScheme();
    }
  }

  private static class ncTEVFSOutLinkFileInfoStandardScheme extends org.apache.thrift.scheme.StandardScheme<ncTEVFSOutLinkFileInfo> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, ncTEVFSOutLinkFileInfo struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // CREATOR
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.creator = iprot.readString();
              struct.setCreatorIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 2: // EDITOR
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.editor = iprot.readString();
              struct.setEditorIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 3: // MODIFIED
            if (schemeField.type == org.apache.thrift.protocol.TType.I64) {
              struct.modified = iprot.readI64();
              struct.setModifiedIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 4: // SHARER
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.sharer = iprot.readString();
              struct.setSharerIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 5: // SHARED_OBJ
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.sharedObj = iprot.readString();
              struct.setSharedObjIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      if (!struct.isSetModified()) {
        throw new org.apache.thrift.protocol.TProtocolException("Required field 'modified' was not found in serialized data! Struct: " + toString());
      }
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, ncTEVFSOutLinkFileInfo struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      if (struct.creator != null) {
        oprot.writeFieldBegin(CREATOR_FIELD_DESC);
        oprot.writeString(struct.creator);
        oprot.writeFieldEnd();
      }
      if (struct.editor != null) {
        oprot.writeFieldBegin(EDITOR_FIELD_DESC);
        oprot.writeString(struct.editor);
        oprot.writeFieldEnd();
      }
      oprot.writeFieldBegin(MODIFIED_FIELD_DESC);
      oprot.writeI64(struct.modified);
      oprot.writeFieldEnd();
      if (struct.sharer != null) {
        oprot.writeFieldBegin(SHARER_FIELD_DESC);
        oprot.writeString(struct.sharer);
        oprot.writeFieldEnd();
      }
      if (struct.sharedObj != null) {
        oprot.writeFieldBegin(SHARED_OBJ_FIELD_DESC);
        oprot.writeString(struct.sharedObj);
        oprot.writeFieldEnd();
      }
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class ncTEVFSOutLinkFileInfoTupleSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    public ncTEVFSOutLinkFileInfoTupleScheme getScheme() {
      return new ncTEVFSOutLinkFileInfoTupleScheme();
    }
  }

  private static class ncTEVFSOutLinkFileInfoTupleScheme extends org.apache.thrift.scheme.TupleScheme<ncTEVFSOutLinkFileInfo> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, ncTEVFSOutLinkFileInfo struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol oprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      oprot.writeString(struct.creator);
      oprot.writeString(struct.editor);
      oprot.writeI64(struct.modified);
      oprot.writeString(struct.sharer);
      oprot.writeString(struct.sharedObj);
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, ncTEVFSOutLinkFileInfo struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol iprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      struct.creator = iprot.readString();
      struct.setCreatorIsSet(true);
      struct.editor = iprot.readString();
      struct.setEditorIsSet(true);
      struct.modified = iprot.readI64();
      struct.setModifiedIsSet(true);
      struct.sharer = iprot.readString();
      struct.setSharerIsSet(true);
      struct.sharedObj = iprot.readString();
      struct.setSharedObjIsSet(true);
    }
  }

  private static <S extends org.apache.thrift.scheme.IScheme> S scheme(org.apache.thrift.protocol.TProtocol proto) {
    return (org.apache.thrift.scheme.StandardScheme.class.equals(proto.getScheme()) ? STANDARD_SCHEME_FACTORY : TUPLE_SCHEME_FACTORY).getScheme();
  }
}

