/**
 * Autogenerated by Thrift Compiler (0.14.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.aishu.wf.core.thrift.evfs;

@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked", "unused"})
/**
 * 文件统计-标识文件数量的结构体
 */
@javax.annotation.Generated(value = "Autogenerated by Thrift Compiler (0.14.2)", date = "2023-06-06")
public class ncTEVFSFilesCount implements org.apache.thrift.TBase<ncTEVFSFilesCount, ncTEVFSFilesCount._Fields>, java.io.Serializable, Cloneable, Comparable<ncTEVFSFilesCount> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("ncTEVFSFilesCount");

  private static final org.apache.thrift.protocol.TField DOC_NUM_FIELD_DESC = new org.apache.thrift.protocol.TField("docNum", org.apache.thrift.protocol.TType.I64, (short)1);
  private static final org.apache.thrift.protocol.TField PIC_NUM_FIELD_DESC = new org.apache.thrift.protocol.TField("picNum", org.apache.thrift.protocol.TType.I64, (short)2);
  private static final org.apache.thrift.protocol.TField VID_NUM_FIELD_DESC = new org.apache.thrift.protocol.TField("vidNum", org.apache.thrift.protocol.TType.I64, (short)3);
  private static final org.apache.thrift.protocol.TField OTH_NUM_FIELD_DESC = new org.apache.thrift.protocol.TField("othNum", org.apache.thrift.protocol.TType.I64, (short)4);
  private static final org.apache.thrift.protocol.TField TOTAL_FIELD_DESC = new org.apache.thrift.protocol.TField("total", org.apache.thrift.protocol.TType.I64, (short)5);

  private static final org.apache.thrift.scheme.SchemeFactory STANDARD_SCHEME_FACTORY = new ncTEVFSFilesCountStandardSchemeFactory();
  private static final org.apache.thrift.scheme.SchemeFactory TUPLE_SCHEME_FACTORY = new ncTEVFSFilesCountTupleSchemeFactory();

  public long docNum; // required
  public long picNum; // required
  public long vidNum; // required
  public long othNum; // required
  public long total; // required

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    DOC_NUM((short)1, "docNum"),
    PIC_NUM((short)2, "picNum"),
    VID_NUM((short)3, "vidNum"),
    OTH_NUM((short)4, "othNum"),
    TOTAL((short)5, "total");

    private static final java.util.Map<java.lang.String, _Fields> byName = new java.util.HashMap<java.lang.String, _Fields>();

    static {
      for (_Fields field : java.util.EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    @org.apache.thrift.annotation.Nullable
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // DOC_NUM
          return DOC_NUM;
        case 2: // PIC_NUM
          return PIC_NUM;
        case 3: // VID_NUM
          return VID_NUM;
        case 4: // OTH_NUM
          return OTH_NUM;
        case 5: // TOTAL
          return TOTAL;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new java.lang.IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    @org.apache.thrift.annotation.Nullable
    public static _Fields findByName(java.lang.String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final java.lang.String _fieldName;

    _Fields(short thriftId, java.lang.String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public java.lang.String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  private static final int __DOCNUM_ISSET_ID = 0;
  private static final int __PICNUM_ISSET_ID = 1;
  private static final int __VIDNUM_ISSET_ID = 2;
  private static final int __OTHNUM_ISSET_ID = 3;
  private static final int __TOTAL_ISSET_ID = 4;
  private byte __isset_bitfield = 0;
  public static final java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new java.util.EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.DOC_NUM, new org.apache.thrift.meta_data.FieldMetaData("docNum", org.apache.thrift.TFieldRequirementType.REQUIRED, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I64)));
    tmpMap.put(_Fields.PIC_NUM, new org.apache.thrift.meta_data.FieldMetaData("picNum", org.apache.thrift.TFieldRequirementType.REQUIRED, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I64)));
    tmpMap.put(_Fields.VID_NUM, new org.apache.thrift.meta_data.FieldMetaData("vidNum", org.apache.thrift.TFieldRequirementType.REQUIRED, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I64)));
    tmpMap.put(_Fields.OTH_NUM, new org.apache.thrift.meta_data.FieldMetaData("othNum", org.apache.thrift.TFieldRequirementType.REQUIRED, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I64)));
    tmpMap.put(_Fields.TOTAL, new org.apache.thrift.meta_data.FieldMetaData("total", org.apache.thrift.TFieldRequirementType.REQUIRED, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.I64)));
    metaDataMap = java.util.Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(ncTEVFSFilesCount.class, metaDataMap);
  }

  public ncTEVFSFilesCount() {
  }

  public ncTEVFSFilesCount(
    long docNum,
    long picNum,
    long vidNum,
    long othNum,
    long total)
  {
    this();
    this.docNum = docNum;
    setDocNumIsSet(true);
    this.picNum = picNum;
    setPicNumIsSet(true);
    this.vidNum = vidNum;
    setVidNumIsSet(true);
    this.othNum = othNum;
    setOthNumIsSet(true);
    this.total = total;
    setTotalIsSet(true);
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public ncTEVFSFilesCount(ncTEVFSFilesCount other) {
    __isset_bitfield = other.__isset_bitfield;
    this.docNum = other.docNum;
    this.picNum = other.picNum;
    this.vidNum = other.vidNum;
    this.othNum = other.othNum;
    this.total = other.total;
  }

  public ncTEVFSFilesCount deepCopy() {
    return new ncTEVFSFilesCount(this);
  }

  @Override
  public void clear() {
    setDocNumIsSet(false);
    this.docNum = 0;
    setPicNumIsSet(false);
    this.picNum = 0;
    setVidNumIsSet(false);
    this.vidNum = 0;
    setOthNumIsSet(false);
    this.othNum = 0;
    setTotalIsSet(false);
    this.total = 0;
  }

  public long getDocNum() {
    return this.docNum;
  }

  public ncTEVFSFilesCount setDocNum(long docNum) {
    this.docNum = docNum;
    setDocNumIsSet(true);
    return this;
  }

  public void unsetDocNum() {
    __isset_bitfield = org.apache.thrift.EncodingUtils.clearBit(__isset_bitfield, __DOCNUM_ISSET_ID);
  }

  /** Returns true if field docNum is set (has been assigned a value) and false otherwise */
  public boolean isSetDocNum() {
    return org.apache.thrift.EncodingUtils.testBit(__isset_bitfield, __DOCNUM_ISSET_ID);
  }

  public void setDocNumIsSet(boolean value) {
    __isset_bitfield = org.apache.thrift.EncodingUtils.setBit(__isset_bitfield, __DOCNUM_ISSET_ID, value);
  }

  public long getPicNum() {
    return this.picNum;
  }

  public ncTEVFSFilesCount setPicNum(long picNum) {
    this.picNum = picNum;
    setPicNumIsSet(true);
    return this;
  }

  public void unsetPicNum() {
    __isset_bitfield = org.apache.thrift.EncodingUtils.clearBit(__isset_bitfield, __PICNUM_ISSET_ID);
  }

  /** Returns true if field picNum is set (has been assigned a value) and false otherwise */
  public boolean isSetPicNum() {
    return org.apache.thrift.EncodingUtils.testBit(__isset_bitfield, __PICNUM_ISSET_ID);
  }

  public void setPicNumIsSet(boolean value) {
    __isset_bitfield = org.apache.thrift.EncodingUtils.setBit(__isset_bitfield, __PICNUM_ISSET_ID, value);
  }

  public long getVidNum() {
    return this.vidNum;
  }

  public ncTEVFSFilesCount setVidNum(long vidNum) {
    this.vidNum = vidNum;
    setVidNumIsSet(true);
    return this;
  }

  public void unsetVidNum() {
    __isset_bitfield = org.apache.thrift.EncodingUtils.clearBit(__isset_bitfield, __VIDNUM_ISSET_ID);
  }

  /** Returns true if field vidNum is set (has been assigned a value) and false otherwise */
  public boolean isSetVidNum() {
    return org.apache.thrift.EncodingUtils.testBit(__isset_bitfield, __VIDNUM_ISSET_ID);
  }

  public void setVidNumIsSet(boolean value) {
    __isset_bitfield = org.apache.thrift.EncodingUtils.setBit(__isset_bitfield, __VIDNUM_ISSET_ID, value);
  }

  public long getOthNum() {
    return this.othNum;
  }

  public ncTEVFSFilesCount setOthNum(long othNum) {
    this.othNum = othNum;
    setOthNumIsSet(true);
    return this;
  }

  public void unsetOthNum() {
    __isset_bitfield = org.apache.thrift.EncodingUtils.clearBit(__isset_bitfield, __OTHNUM_ISSET_ID);
  }

  /** Returns true if field othNum is set (has been assigned a value) and false otherwise */
  public boolean isSetOthNum() {
    return org.apache.thrift.EncodingUtils.testBit(__isset_bitfield, __OTHNUM_ISSET_ID);
  }

  public void setOthNumIsSet(boolean value) {
    __isset_bitfield = org.apache.thrift.EncodingUtils.setBit(__isset_bitfield, __OTHNUM_ISSET_ID, value);
  }

  public long getTotal() {
    return this.total;
  }

  public ncTEVFSFilesCount setTotal(long total) {
    this.total = total;
    setTotalIsSet(true);
    return this;
  }

  public void unsetTotal() {
    __isset_bitfield = org.apache.thrift.EncodingUtils.clearBit(__isset_bitfield, __TOTAL_ISSET_ID);
  }

  /** Returns true if field total is set (has been assigned a value) and false otherwise */
  public boolean isSetTotal() {
    return org.apache.thrift.EncodingUtils.testBit(__isset_bitfield, __TOTAL_ISSET_ID);
  }

  public void setTotalIsSet(boolean value) {
    __isset_bitfield = org.apache.thrift.EncodingUtils.setBit(__isset_bitfield, __TOTAL_ISSET_ID, value);
  }

  public void setFieldValue(_Fields field, @org.apache.thrift.annotation.Nullable java.lang.Object value) {
    switch (field) {
    case DOC_NUM:
      if (value == null) {
        unsetDocNum();
      } else {
        setDocNum((java.lang.Long)value);
      }
      break;

    case PIC_NUM:
      if (value == null) {
        unsetPicNum();
      } else {
        setPicNum((java.lang.Long)value);
      }
      break;

    case VID_NUM:
      if (value == null) {
        unsetVidNum();
      } else {
        setVidNum((java.lang.Long)value);
      }
      break;

    case OTH_NUM:
      if (value == null) {
        unsetOthNum();
      } else {
        setOthNum((java.lang.Long)value);
      }
      break;

    case TOTAL:
      if (value == null) {
        unsetTotal();
      } else {
        setTotal((java.lang.Long)value);
      }
      break;

    }
  }

  @org.apache.thrift.annotation.Nullable
  public java.lang.Object getFieldValue(_Fields field) {
    switch (field) {
    case DOC_NUM:
      return getDocNum();

    case PIC_NUM:
      return getPicNum();

    case VID_NUM:
      return getVidNum();

    case OTH_NUM:
      return getOthNum();

    case TOTAL:
      return getTotal();

    }
    throw new java.lang.IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new java.lang.IllegalArgumentException();
    }

    switch (field) {
    case DOC_NUM:
      return isSetDocNum();
    case PIC_NUM:
      return isSetPicNum();
    case VID_NUM:
      return isSetVidNum();
    case OTH_NUM:
      return isSetOthNum();
    case TOTAL:
      return isSetTotal();
    }
    throw new java.lang.IllegalStateException();
  }

  @Override
  public boolean equals(java.lang.Object that) {
    if (that instanceof ncTEVFSFilesCount)
      return this.equals((ncTEVFSFilesCount)that);
    return false;
  }

  public boolean equals(ncTEVFSFilesCount that) {
    if (that == null)
      return false;
    if (this == that)
      return true;

    boolean this_present_docNum = true;
    boolean that_present_docNum = true;
    if (this_present_docNum || that_present_docNum) {
      if (!(this_present_docNum && that_present_docNum))
        return false;
      if (this.docNum != that.docNum)
        return false;
    }

    boolean this_present_picNum = true;
    boolean that_present_picNum = true;
    if (this_present_picNum || that_present_picNum) {
      if (!(this_present_picNum && that_present_picNum))
        return false;
      if (this.picNum != that.picNum)
        return false;
    }

    boolean this_present_vidNum = true;
    boolean that_present_vidNum = true;
    if (this_present_vidNum || that_present_vidNum) {
      if (!(this_present_vidNum && that_present_vidNum))
        return false;
      if (this.vidNum != that.vidNum)
        return false;
    }

    boolean this_present_othNum = true;
    boolean that_present_othNum = true;
    if (this_present_othNum || that_present_othNum) {
      if (!(this_present_othNum && that_present_othNum))
        return false;
      if (this.othNum != that.othNum)
        return false;
    }

    boolean this_present_total = true;
    boolean that_present_total = true;
    if (this_present_total || that_present_total) {
      if (!(this_present_total && that_present_total))
        return false;
      if (this.total != that.total)
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    int hashCode = 1;

    hashCode = hashCode * 8191 + org.apache.thrift.TBaseHelper.hashCode(docNum);

    hashCode = hashCode * 8191 + org.apache.thrift.TBaseHelper.hashCode(picNum);

    hashCode = hashCode * 8191 + org.apache.thrift.TBaseHelper.hashCode(vidNum);

    hashCode = hashCode * 8191 + org.apache.thrift.TBaseHelper.hashCode(othNum);

    hashCode = hashCode * 8191 + org.apache.thrift.TBaseHelper.hashCode(total);

    return hashCode;
  }

  @Override
  public int compareTo(ncTEVFSFilesCount other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = java.lang.Boolean.compare(isSetDocNum(), other.isSetDocNum());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetDocNum()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.docNum, other.docNum);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.compare(isSetPicNum(), other.isSetPicNum());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetPicNum()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.picNum, other.picNum);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.compare(isSetVidNum(), other.isSetVidNum());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetVidNum()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.vidNum, other.vidNum);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.compare(isSetOthNum(), other.isSetOthNum());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetOthNum()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.othNum, other.othNum);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.compare(isSetTotal(), other.isSetTotal());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetTotal()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.total, other.total);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  @org.apache.thrift.annotation.Nullable
  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    scheme(iprot).read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    scheme(oprot).write(oprot, this);
  }

  @Override
  public java.lang.String toString() {
    java.lang.StringBuilder sb = new java.lang.StringBuilder("ncTEVFSFilesCount(");
    boolean first = true;

    sb.append("docNum:");
    sb.append(this.docNum);
    first = false;
    if (!first) sb.append(", ");
    sb.append("picNum:");
    sb.append(this.picNum);
    first = false;
    if (!first) sb.append(", ");
    sb.append("vidNum:");
    sb.append(this.vidNum);
    first = false;
    if (!first) sb.append(", ");
    sb.append("othNum:");
    sb.append(this.othNum);
    first = false;
    if (!first) sb.append(", ");
    sb.append("total:");
    sb.append(this.total);
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    // alas, we cannot check 'docNum' because it's a primitive and you chose the non-beans generator.
    // alas, we cannot check 'picNum' because it's a primitive and you chose the non-beans generator.
    // alas, we cannot check 'vidNum' because it's a primitive and you chose the non-beans generator.
    // alas, we cannot check 'othNum' because it's a primitive and you chose the non-beans generator.
    // alas, we cannot check 'total' because it's a primitive and you chose the non-beans generator.
    // check for sub-struct validity
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, java.lang.ClassNotFoundException {
    try {
      // it doesn't seem like you should have to do this, but java serialization is wacky, and doesn't call the default constructor.
      __isset_bitfield = 0;
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class ncTEVFSFilesCountStandardSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    public ncTEVFSFilesCountStandardScheme getScheme() {
      return new ncTEVFSFilesCountStandardScheme();
    }
  }

  private static class ncTEVFSFilesCountStandardScheme extends org.apache.thrift.scheme.StandardScheme<ncTEVFSFilesCount> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, ncTEVFSFilesCount struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // DOC_NUM
            if (schemeField.type == org.apache.thrift.protocol.TType.I64) {
              struct.docNum = iprot.readI64();
              struct.setDocNumIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 2: // PIC_NUM
            if (schemeField.type == org.apache.thrift.protocol.TType.I64) {
              struct.picNum = iprot.readI64();
              struct.setPicNumIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 3: // VID_NUM
            if (schemeField.type == org.apache.thrift.protocol.TType.I64) {
              struct.vidNum = iprot.readI64();
              struct.setVidNumIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 4: // OTH_NUM
            if (schemeField.type == org.apache.thrift.protocol.TType.I64) {
              struct.othNum = iprot.readI64();
              struct.setOthNumIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 5: // TOTAL
            if (schemeField.type == org.apache.thrift.protocol.TType.I64) {
              struct.total = iprot.readI64();
              struct.setTotalIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      if (!struct.isSetDocNum()) {
        throw new org.apache.thrift.protocol.TProtocolException("Required field 'docNum' was not found in serialized data! Struct: " + toString());
      }
      if (!struct.isSetPicNum()) {
        throw new org.apache.thrift.protocol.TProtocolException("Required field 'picNum' was not found in serialized data! Struct: " + toString());
      }
      if (!struct.isSetVidNum()) {
        throw new org.apache.thrift.protocol.TProtocolException("Required field 'vidNum' was not found in serialized data! Struct: " + toString());
      }
      if (!struct.isSetOthNum()) {
        throw new org.apache.thrift.protocol.TProtocolException("Required field 'othNum' was not found in serialized data! Struct: " + toString());
      }
      if (!struct.isSetTotal()) {
        throw new org.apache.thrift.protocol.TProtocolException("Required field 'total' was not found in serialized data! Struct: " + toString());
      }
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, ncTEVFSFilesCount struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      oprot.writeFieldBegin(DOC_NUM_FIELD_DESC);
      oprot.writeI64(struct.docNum);
      oprot.writeFieldEnd();
      oprot.writeFieldBegin(PIC_NUM_FIELD_DESC);
      oprot.writeI64(struct.picNum);
      oprot.writeFieldEnd();
      oprot.writeFieldBegin(VID_NUM_FIELD_DESC);
      oprot.writeI64(struct.vidNum);
      oprot.writeFieldEnd();
      oprot.writeFieldBegin(OTH_NUM_FIELD_DESC);
      oprot.writeI64(struct.othNum);
      oprot.writeFieldEnd();
      oprot.writeFieldBegin(TOTAL_FIELD_DESC);
      oprot.writeI64(struct.total);
      oprot.writeFieldEnd();
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class ncTEVFSFilesCountTupleSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    public ncTEVFSFilesCountTupleScheme getScheme() {
      return new ncTEVFSFilesCountTupleScheme();
    }
  }

  private static class ncTEVFSFilesCountTupleScheme extends org.apache.thrift.scheme.TupleScheme<ncTEVFSFilesCount> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, ncTEVFSFilesCount struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol oprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      oprot.writeI64(struct.docNum);
      oprot.writeI64(struct.picNum);
      oprot.writeI64(struct.vidNum);
      oprot.writeI64(struct.othNum);
      oprot.writeI64(struct.total);
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, ncTEVFSFilesCount struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol iprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      struct.docNum = iprot.readI64();
      struct.setDocNumIsSet(true);
      struct.picNum = iprot.readI64();
      struct.setPicNumIsSet(true);
      struct.vidNum = iprot.readI64();
      struct.setVidNumIsSet(true);
      struct.othNum = iprot.readI64();
      struct.setOthNumIsSet(true);
      struct.total = iprot.readI64();
      struct.setTotalIsSet(true);
    }
  }

  private static <S extends org.apache.thrift.scheme.IScheme> S scheme(org.apache.thrift.protocol.TProtocol proto) {
    return (org.apache.thrift.scheme.StandardScheme.class.equals(proto.getScheme()) ? STANDARD_SCHEME_FACTORY : TUPLE_SCHEME_FACTORY).getScheme();
  }
}

