/**
 * Autogenerated by Thrift Compiler (0.14.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.aishu.wf.core.thrift.evfs;


/**
 * IP版本
 */
@javax.annotation.Generated(value = "Autogenerated by Thrift Compiler (0.14.2)", date = "2023-06-06")
public enum ncTIPVersion implements org.apache.thrift.TEnum {
  NC_IPv4(4),
  NC_IPv6(6);

  private final int value;

  private ncTIPVersion(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  @org.apache.thrift.annotation.Nullable
  public static ncTIPVersion findByValue(int value) { 
    switch (value) {
      case 4:
        return NC_IPv4;
      case 6:
        return NC_IPv6;
      default:
        return null;
    }
  }
}
