/**
 * Autogenerated by Thrift Compiler (0.14.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.aishu.wf.core.thrift.eacplog;


@javax.annotation.Generated(value = "Autogenerated by Thrift Compiler (0.14.2)", date = "2023-06-06")
public enum ncTLogType implements org.apache.thrift.TEnum {
  NCT_LT_LOGIN(10),
  NCT_LT_MANAGEMENT(11),
  NCT_LT_OPEARTION(12);

  private final int value;

  private ncTLogType(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  @org.apache.thrift.annotation.Nullable
  public static ncTLogType findByValue(int value) { 
    switch (value) {
      case 10:
        return NCT_LT_LOGIN;
      case 11:
        return NCT_LT_MANAGEMENT;
      case 12:
        return NCT_LT_OPEARTION;
      default:
        return null;
    }
  }
}
