/**
 * Autogenerated by Thrift Compiler (0.14.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.aishu.wf.core.thrift.eacplog;


@javax.annotation.Generated(value = "Autogenerated by Thrift Compiler (0.14.2)", date = "2023-06-06")
public enum ncTLoginType implements org.apache.thrift.TEnum {
  NCT_CLT_ALL(0),
  NCT_CLT_LOGIN_IN(1),
  NCT_CLT_LOGIN_OUT(2),
  NCT_CLT_AUTHENICATION(3),
  NCT_CLT_OTHER(127);

  private final int value;

  private ncTLoginType(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  @org.apache.thrift.annotation.Nullable
  public static ncTLoginType findByValue(int value) { 
    switch (value) {
      case 0:
        return NCT_CLT_ALL;
      case 1:
        return NCT_CLT_LOGIN_IN;
      case 2:
        return NCT_CLT_LOGIN_OUT;
      case 3:
        return NCT_CLT_AUTHENICATION;
      case 127:
        return NCT_CLT_OTHER;
      default:
        return null;
    }
  }
}
