/**
 * Autogenerated by Thrift Compiler (0.14.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.aishu.wf.core.thrift.exception;


/**
 * 异常类型枚举类型
 */
@javax.annotation.Generated(value = "Autogenerated by Thrift Compiler (0.14.2)", date = "2023-06-06")
public enum ncTExpType implements org.apache.thrift.TEnum {
  NCT_FATAL(0),
  NCT_CRITICAL(1),
  NCT_WARN(2),
  NCT_INFO(3);

  private final int value;

  private ncTExpType(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  @org.apache.thrift.annotation.Nullable
  public static ncTExpType findByValue(int value) { 
    switch (value) {
      case 0:
        return NCT_FATAL;
      case 1:
        return NCT_CRITICAL;
      case 2:
        return NCT_WARN;
      case 3:
        return NCT_INFO;
      default:
        return null;
    }
  }
}
