// Code generated by MockGen. DO NOT EDIT.
// Source: api_metadata.go
//
// Generated by this command:
//
//	mockgen -source=api_metadata.go -destination=../mocks/api_metadata.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	interfaces "devops.aishu.cn/AISHUDevOps/DIP/_git/agent-operator-integration/server/interfaces"
	gomock "go.uber.org/mock/gomock"
)

// MockIOpenAPIParser is a mock of IOpenAPIParser interface.
type MockIOpenAPIParser struct {
	ctrl     *gomock.Controller
	recorder *MockIOpenAPIParserMockRecorder
	isgomock struct{}
}

// MockIOpenAPIParserMockRecorder is the mock recorder for MockIOpenAPIParser.
type MockIOpenAPIParserMockRecorder struct {
	mock *MockIOpenAPIParser
}

// NewMockIOpenAPIParser creates a new mock instance.
func NewMockIOpenAPIParser(ctrl *gomock.Controller) *MockIOpenAPIParser {
	mock := &MockIOpenAPIParser{ctrl: ctrl}
	mock.recorder = &MockIOpenAPIParserMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIOpenAPIParser) EXPECT() *MockIOpenAPIParserMockRecorder {
	return m.recorder
}

// GetAllContent mocks base method.
func (m *MockIOpenAPIParser) GetAllContent(ctx context.Context, data []byte) (*interfaces.OpenAPIContent, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllContent", ctx, data)
	ret0, _ := ret[0].(*interfaces.OpenAPIContent)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllContent indicates an expected call of GetAllContent.
func (mr *MockIOpenAPIParserMockRecorder) GetAllContent(ctx, data any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllContent", reflect.TypeOf((*MockIOpenAPIParser)(nil).GetAllContent), ctx, data)
}

// GetPathItemContent mocks base method.
func (m *MockIOpenAPIParser) GetPathItemContent(ctx context.Context, data []byte, path, method string) (*interfaces.PathItemContent, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPathItemContent", ctx, data, path, method)
	ret0, _ := ret[0].(*interfaces.PathItemContent)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPathItemContent indicates an expected call of GetPathItemContent.
func (mr *MockIOpenAPIParserMockRecorder) GetPathItemContent(ctx, data, path, method any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPathItemContent", reflect.TypeOf((*MockIOpenAPIParser)(nil).GetPathItemContent), ctx, data, path, method)
}

// GetPathItems mocks base method.
func (m *MockIOpenAPIParser) GetPathItems(ctx context.Context, data []byte) ([]*interfaces.PathItemContent, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPathItems", ctx, data)
	ret0, _ := ret[0].([]*interfaces.PathItemContent)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPathItems indicates an expected call of GetPathItems.
func (mr *MockIOpenAPIParserMockRecorder) GetPathItems(ctx, data any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPathItems", reflect.TypeOf((*MockIOpenAPIParser)(nil).GetPathItems), ctx, data)
}
