// Code generated by MockGen. DO NOT EDIT.
// Source: ./ds_svc.go
//
// Generated by this command:
//
//	mockgen -source=./ds_svc.go -destination ./v3portdrivermock/ds_svc.go -package v3portdrivermock
//

// Package v3portdrivermock is a generated GoMock package.
package v3portdrivermock

import (
	context "context"
	sql "database/sql"
	reflect "reflect"

	dsdto "devops.aishu.cn/AISHUDevOps/DIP/_git/agent-factory/src/domain/types/dto/daconfigdto/dsdto"
	docindexobj "devops.aishu.cn/AISHUDevOps/DIP/_git/agent-factory/src/domain/valueobject/docindexobj"
	gomock "go.uber.org/mock/gomock"
)

// MockIDsSvc is a mock of IDsSvc interface.
type MockIDsSvc struct {
	ctrl     *gomock.Controller
	recorder *MockIDsSvcMockRecorder
	isgomock struct{}
}

// MockIDsSvcMockRecorder is the mock recorder for MockIDsSvc.
type MockIDsSvcMockRecorder struct {
	mock *MockIDsSvc
}

// NewMockIDsSvc creates a new mock instance.
func NewMockIDsSvc(ctrl *gomock.Controller) *MockIDsSvc {
	mock := &MockIDsSvc{ctrl: ctrl}
	mock.recorder = &MockIDsSvcMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIDsSvc) EXPECT() *MockIDsSvcMockRecorder {
	return m.recorder
}

// AddIndex mocks base method.
func (m *MockIDsSvc) AddIndex(ctx context.Context, dto *dsdto.DsComDto, datasetID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddIndex", ctx, dto, datasetID)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddIndex indicates an expected call of AddIndex.
func (mr *MockIDsSvcMockRecorder) AddIndex(ctx, dto, datasetID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddIndex", reflect.TypeOf((*MockIDsSvc)(nil).AddIndex), ctx, dto, datasetID)
}

// BatchGetDsIndexStatus mocks base method.
func (m *MockIDsSvc) BatchGetDsIndexStatus(ctx context.Context, req *dsdto.BatchCheckIndexStatusReq) ([]*docindexobj.AgentDocIndexStatusInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BatchGetDsIndexStatus", ctx, req)
	ret0, _ := ret[0].([]*docindexobj.AgentDocIndexStatusInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BatchGetDsIndexStatus indicates an expected call of BatchGetDsIndexStatus.
func (mr *MockIDsSvcMockRecorder) BatchGetDsIndexStatus(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BatchGetDsIndexStatus", reflect.TypeOf((*MockIDsSvc)(nil).BatchGetDsIndexStatus), ctx, req)
}

// Create mocks base method.
func (m *MockIDsSvc) Create(ctx context.Context, tx *sql.Tx, dto *dsdto.DsComDto) (string, bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, tx, dto)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(bool)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// Create indicates an expected call of Create.
func (mr *MockIDsSvcMockRecorder) Create(ctx, tx, dto any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockIDsSvc)(nil).Create), ctx, tx, dto)
}

// CreateAssocOnly mocks base method.
func (m *MockIDsSvc) CreateAssocOnly(ctx context.Context, tx *sql.Tx, dto *dsdto.DsUniqDto, datasetId string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateAssocOnly", ctx, tx, dto, datasetId)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateAssocOnly indicates an expected call of CreateAssocOnly.
func (mr *MockIDsSvcMockRecorder) CreateAssocOnly(ctx, tx, dto, datasetId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateAssocOnly", reflect.TypeOf((*MockIDsSvc)(nil).CreateAssocOnly), ctx, tx, dto, datasetId)
}

// Delete mocks base method.
func (m *MockIDsSvc) Delete(ctx context.Context, tx *sql.Tx, dto *dsdto.DsComDto) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, tx, dto)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockIDsSvcMockRecorder) Delete(ctx, tx, dto any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockIDsSvc)(nil).Delete), ctx, tx, dto)
}

// GetAgentDatasetID mocks base method.
func (m *MockIDsSvc) GetAgentDatasetID(ctx context.Context, req *dsdto.DsUniqDto) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAgentDatasetID", ctx, req)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAgentDatasetID indicates an expected call of GetAgentDatasetID.
func (mr *MockIDsSvcMockRecorder) GetAgentDatasetID(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAgentDatasetID", reflect.TypeOf((*MockIDsSvc)(nil).GetAgentDatasetID), ctx, req)
}

// GetDsIndexStatus mocks base method.
func (m *MockIDsSvc) GetDsIndexStatus(ctx context.Context, req *dsdto.DsUniqWithDatasetIDDto, isShowFailInfos bool) (*docindexobj.AgentDocIndexStatusInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDsIndexStatus", ctx, req, isShowFailInfos)
	ret0, _ := ret[0].(*docindexobj.AgentDocIndexStatusInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDsIndexStatus indicates an expected call of GetDsIndexStatus.
func (mr *MockIDsSvcMockRecorder) GetDsIndexStatus(ctx, req, isShowFailInfos any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDsIndexStatus", reflect.TypeOf((*MockIDsSvc)(nil).GetDsIndexStatus), ctx, req, isShowFailInfos)
}

// Update mocks base method.
func (m *MockIDsSvc) Update(ctx context.Context, tx *sql.Tx, dto *dsdto.DsUpdateDto) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, tx, dto)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update.
func (mr *MockIDsSvcMockRecorder) Update(ctx, tx, dto any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockIDsSvc)(nil).Update), ctx, tx, dto)
}

// MockiDsIndex is a mock of iDsIndex interface.
type MockiDsIndex struct {
	ctrl     *gomock.Controller
	recorder *MockiDsIndexMockRecorder
	isgomock struct{}
}

// MockiDsIndexMockRecorder is the mock recorder for MockiDsIndex.
type MockiDsIndexMockRecorder struct {
	mock *MockiDsIndex
}

// NewMockiDsIndex creates a new mock instance.
func NewMockiDsIndex(ctrl *gomock.Controller) *MockiDsIndex {
	mock := &MockiDsIndex{ctrl: ctrl}
	mock.recorder = &MockiDsIndexMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockiDsIndex) EXPECT() *MockiDsIndexMockRecorder {
	return m.recorder
}

// AddIndex mocks base method.
func (m *MockiDsIndex) AddIndex(ctx context.Context, dto *dsdto.DsComDto, datasetID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddIndex", ctx, dto, datasetID)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddIndex indicates an expected call of AddIndex.
func (mr *MockiDsIndexMockRecorder) AddIndex(ctx, dto, datasetID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddIndex", reflect.TypeOf((*MockiDsIndex)(nil).AddIndex), ctx, dto, datasetID)
}

// BatchGetDsIndexStatus mocks base method.
func (m *MockiDsIndex) BatchGetDsIndexStatus(ctx context.Context, req *dsdto.BatchCheckIndexStatusReq) ([]*docindexobj.AgentDocIndexStatusInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BatchGetDsIndexStatus", ctx, req)
	ret0, _ := ret[0].([]*docindexobj.AgentDocIndexStatusInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BatchGetDsIndexStatus indicates an expected call of BatchGetDsIndexStatus.
func (mr *MockiDsIndexMockRecorder) BatchGetDsIndexStatus(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BatchGetDsIndexStatus", reflect.TypeOf((*MockiDsIndex)(nil).BatchGetDsIndexStatus), ctx, req)
}

// GetDsIndexStatus mocks base method.
func (m *MockiDsIndex) GetDsIndexStatus(ctx context.Context, req *dsdto.DsUniqWithDatasetIDDto, isShowFailInfos bool) (*docindexobj.AgentDocIndexStatusInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDsIndexStatus", ctx, req, isShowFailInfos)
	ret0, _ := ret[0].(*docindexobj.AgentDocIndexStatusInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDsIndexStatus indicates an expected call of GetDsIndexStatus.
func (mr *MockiDsIndexMockRecorder) GetDsIndexStatus(ctx, req, isShowFailInfos any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDsIndexStatus", reflect.TypeOf((*MockiDsIndex)(nil).GetDsIndexStatus), ctx, req, isShowFailInfos)
}
