/**
 * Autogenerated by Thrift Compiler (0.14.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.aishu.wf.core.thrift.evfs;

@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked", "unused"})
@javax.annotation.Generated(value = "Autogenerated by Thrift Compiler (0.14.2)", date = "2023-06-06")
public class ncTEVFSSiteAccelerateInfo implements org.apache.thrift.TBase<ncTEVFSSiteAccelerateInfo, ncTEVFSSiteAccelerateInfo._Fields>, java.io.Serializable, Cloneable, Comparable<ncTEVFSSiteAccelerateInfo> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("ncTEVFSSiteAccelerateInfo");

  private static final org.apache.thrift.protocol.TField ACCELERATE_NAME_FIELD_DESC = new org.apache.thrift.protocol.TField("accelerateName", org.apache.thrift.protocol.TType.STRING, (short)1);
  private static final org.apache.thrift.protocol.TField SITE_ID_FIELD_DESC = new org.apache.thrift.protocol.TField("siteId", org.apache.thrift.protocol.TType.STRING, (short)2);
  private static final org.apache.thrift.protocol.TField OSS_ID_FIELD_DESC = new org.apache.thrift.protocol.TField("ossId", org.apache.thrift.protocol.TType.LIST, (short)3);
  private static final org.apache.thrift.protocol.TField ENABLED_FIELD_DESC = new org.apache.thrift.protocol.TField("enabled", org.apache.thrift.protocol.TType.BOOL, (short)4);
  private static final org.apache.thrift.protocol.TField ACCELERATED_SITE_ID_FIELD_DESC = new org.apache.thrift.protocol.TField("acceleratedSiteId", org.apache.thrift.protocol.TType.STRING, (short)5);
  private static final org.apache.thrift.protocol.TField ACCELERATED_OSS_ID_FIELD_DESC = new org.apache.thrift.protocol.TField("acceleratedOssId", org.apache.thrift.protocol.TType.LIST, (short)6);

  private static final org.apache.thrift.scheme.SchemeFactory STANDARD_SCHEME_FACTORY = new ncTEVFSSiteAccelerateInfoStandardSchemeFactory();
  private static final org.apache.thrift.scheme.SchemeFactory TUPLE_SCHEME_FACTORY = new ncTEVFSSiteAccelerateInfoTupleSchemeFactory();

  public @org.apache.thrift.annotation.Nullable java.lang.String accelerateName; // required
  public @org.apache.thrift.annotation.Nullable java.lang.String siteId; // required
  public @org.apache.thrift.annotation.Nullable java.util.List<java.lang.String> ossId; // required
  public boolean enabled; // required
  public @org.apache.thrift.annotation.Nullable java.lang.String acceleratedSiteId; // required
  public @org.apache.thrift.annotation.Nullable java.util.List<java.lang.String> acceleratedOssId; // required

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    ACCELERATE_NAME((short)1, "accelerateName"),
    SITE_ID((short)2, "siteId"),
    OSS_ID((short)3, "ossId"),
    ENABLED((short)4, "enabled"),
    ACCELERATED_SITE_ID((short)5, "acceleratedSiteId"),
    ACCELERATED_OSS_ID((short)6, "acceleratedOssId");

    private static final java.util.Map<java.lang.String, _Fields> byName = new java.util.HashMap<java.lang.String, _Fields>();

    static {
      for (_Fields field : java.util.EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    @org.apache.thrift.annotation.Nullable
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // ACCELERATE_NAME
          return ACCELERATE_NAME;
        case 2: // SITE_ID
          return SITE_ID;
        case 3: // OSS_ID
          return OSS_ID;
        case 4: // ENABLED
          return ENABLED;
        case 5: // ACCELERATED_SITE_ID
          return ACCELERATED_SITE_ID;
        case 6: // ACCELERATED_OSS_ID
          return ACCELERATED_OSS_ID;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new java.lang.IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    @org.apache.thrift.annotation.Nullable
    public static _Fields findByName(java.lang.String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final java.lang.String _fieldName;

    _Fields(short thriftId, java.lang.String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public java.lang.String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  private static final int __ENABLED_ISSET_ID = 0;
  private byte __isset_bitfield = 0;
  public static final java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new java.util.EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.ACCELERATE_NAME, new org.apache.thrift.meta_data.FieldMetaData("accelerateName", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.SITE_ID, new org.apache.thrift.meta_data.FieldMetaData("siteId", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.OSS_ID, new org.apache.thrift.meta_data.FieldMetaData("ossId", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.ListMetaData(org.apache.thrift.protocol.TType.LIST, 
            new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING))));
    tmpMap.put(_Fields.ENABLED, new org.apache.thrift.meta_data.FieldMetaData("enabled", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.BOOL)));
    tmpMap.put(_Fields.ACCELERATED_SITE_ID, new org.apache.thrift.meta_data.FieldMetaData("acceleratedSiteId", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.ACCELERATED_OSS_ID, new org.apache.thrift.meta_data.FieldMetaData("acceleratedOssId", org.apache.thrift.TFieldRequirementType.DEFAULT, 
        new org.apache.thrift.meta_data.ListMetaData(org.apache.thrift.protocol.TType.LIST, 
            new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING))));
    metaDataMap = java.util.Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(ncTEVFSSiteAccelerateInfo.class, metaDataMap);
  }

  public ncTEVFSSiteAccelerateInfo() {
  }

  public ncTEVFSSiteAccelerateInfo(
    java.lang.String accelerateName,
    java.lang.String siteId,
    java.util.List<java.lang.String> ossId,
    boolean enabled,
    java.lang.String acceleratedSiteId,
    java.util.List<java.lang.String> acceleratedOssId)
  {
    this();
    this.accelerateName = accelerateName;
    this.siteId = siteId;
    this.ossId = ossId;
    this.enabled = enabled;
    setEnabledIsSet(true);
    this.acceleratedSiteId = acceleratedSiteId;
    this.acceleratedOssId = acceleratedOssId;
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public ncTEVFSSiteAccelerateInfo(ncTEVFSSiteAccelerateInfo other) {
    __isset_bitfield = other.__isset_bitfield;
    if (other.isSetAccelerateName()) {
      this.accelerateName = other.accelerateName;
    }
    if (other.isSetSiteId()) {
      this.siteId = other.siteId;
    }
    if (other.isSetOssId()) {
      java.util.List<java.lang.String> __this__ossId = new java.util.ArrayList<java.lang.String>(other.ossId);
      this.ossId = __this__ossId;
    }
    this.enabled = other.enabled;
    if (other.isSetAcceleratedSiteId()) {
      this.acceleratedSiteId = other.acceleratedSiteId;
    }
    if (other.isSetAcceleratedOssId()) {
      java.util.List<java.lang.String> __this__acceleratedOssId = new java.util.ArrayList<java.lang.String>(other.acceleratedOssId);
      this.acceleratedOssId = __this__acceleratedOssId;
    }
  }

  public ncTEVFSSiteAccelerateInfo deepCopy() {
    return new ncTEVFSSiteAccelerateInfo(this);
  }

  @Override
  public void clear() {
    this.accelerateName = null;
    this.siteId = null;
    this.ossId = null;
    setEnabledIsSet(false);
    this.enabled = false;
    this.acceleratedSiteId = null;
    this.acceleratedOssId = null;
  }

  @org.apache.thrift.annotation.Nullable
  public java.lang.String getAccelerateName() {
    return this.accelerateName;
  }

  public ncTEVFSSiteAccelerateInfo setAccelerateName(@org.apache.thrift.annotation.Nullable java.lang.String accelerateName) {
    this.accelerateName = accelerateName;
    return this;
  }

  public void unsetAccelerateName() {
    this.accelerateName = null;
  }

  /** Returns true if field accelerateName is set (has been assigned a value) and false otherwise */
  public boolean isSetAccelerateName() {
    return this.accelerateName != null;
  }

  public void setAccelerateNameIsSet(boolean value) {
    if (!value) {
      this.accelerateName = null;
    }
  }

  @org.apache.thrift.annotation.Nullable
  public java.lang.String getSiteId() {
    return this.siteId;
  }

  public ncTEVFSSiteAccelerateInfo setSiteId(@org.apache.thrift.annotation.Nullable java.lang.String siteId) {
    this.siteId = siteId;
    return this;
  }

  public void unsetSiteId() {
    this.siteId = null;
  }

  /** Returns true if field siteId is set (has been assigned a value) and false otherwise */
  public boolean isSetSiteId() {
    return this.siteId != null;
  }

  public void setSiteIdIsSet(boolean value) {
    if (!value) {
      this.siteId = null;
    }
  }

  public int getOssIdSize() {
    return (this.ossId == null) ? 0 : this.ossId.size();
  }

  @org.apache.thrift.annotation.Nullable
  public java.util.Iterator<java.lang.String> getOssIdIterator() {
    return (this.ossId == null) ? null : this.ossId.iterator();
  }

  public void addToOssId(java.lang.String elem) {
    if (this.ossId == null) {
      this.ossId = new java.util.ArrayList<java.lang.String>();
    }
    this.ossId.add(elem);
  }

  @org.apache.thrift.annotation.Nullable
  public java.util.List<java.lang.String> getOssId() {
    return this.ossId;
  }

  public ncTEVFSSiteAccelerateInfo setOssId(@org.apache.thrift.annotation.Nullable java.util.List<java.lang.String> ossId) {
    this.ossId = ossId;
    return this;
  }

  public void unsetOssId() {
    this.ossId = null;
  }

  /** Returns true if field ossId is set (has been assigned a value) and false otherwise */
  public boolean isSetOssId() {
    return this.ossId != null;
  }

  public void setOssIdIsSet(boolean value) {
    if (!value) {
      this.ossId = null;
    }
  }

  public boolean isEnabled() {
    return this.enabled;
  }

  public ncTEVFSSiteAccelerateInfo setEnabled(boolean enabled) {
    this.enabled = enabled;
    setEnabledIsSet(true);
    return this;
  }

  public void unsetEnabled() {
    __isset_bitfield = org.apache.thrift.EncodingUtils.clearBit(__isset_bitfield, __ENABLED_ISSET_ID);
  }

  /** Returns true if field enabled is set (has been assigned a value) and false otherwise */
  public boolean isSetEnabled() {
    return org.apache.thrift.EncodingUtils.testBit(__isset_bitfield, __ENABLED_ISSET_ID);
  }

  public void setEnabledIsSet(boolean value) {
    __isset_bitfield = org.apache.thrift.EncodingUtils.setBit(__isset_bitfield, __ENABLED_ISSET_ID, value);
  }

  @org.apache.thrift.annotation.Nullable
  public java.lang.String getAcceleratedSiteId() {
    return this.acceleratedSiteId;
  }

  public ncTEVFSSiteAccelerateInfo setAcceleratedSiteId(@org.apache.thrift.annotation.Nullable java.lang.String acceleratedSiteId) {
    this.acceleratedSiteId = acceleratedSiteId;
    return this;
  }

  public void unsetAcceleratedSiteId() {
    this.acceleratedSiteId = null;
  }

  /** Returns true if field acceleratedSiteId is set (has been assigned a value) and false otherwise */
  public boolean isSetAcceleratedSiteId() {
    return this.acceleratedSiteId != null;
  }

  public void setAcceleratedSiteIdIsSet(boolean value) {
    if (!value) {
      this.acceleratedSiteId = null;
    }
  }

  public int getAcceleratedOssIdSize() {
    return (this.acceleratedOssId == null) ? 0 : this.acceleratedOssId.size();
  }

  @org.apache.thrift.annotation.Nullable
  public java.util.Iterator<java.lang.String> getAcceleratedOssIdIterator() {
    return (this.acceleratedOssId == null) ? null : this.acceleratedOssId.iterator();
  }

  public void addToAcceleratedOssId(java.lang.String elem) {
    if (this.acceleratedOssId == null) {
      this.acceleratedOssId = new java.util.ArrayList<java.lang.String>();
    }
    this.acceleratedOssId.add(elem);
  }

  @org.apache.thrift.annotation.Nullable
  public java.util.List<java.lang.String> getAcceleratedOssId() {
    return this.acceleratedOssId;
  }

  public ncTEVFSSiteAccelerateInfo setAcceleratedOssId(@org.apache.thrift.annotation.Nullable java.util.List<java.lang.String> acceleratedOssId) {
    this.acceleratedOssId = acceleratedOssId;
    return this;
  }

  public void unsetAcceleratedOssId() {
    this.acceleratedOssId = null;
  }

  /** Returns true if field acceleratedOssId is set (has been assigned a value) and false otherwise */
  public boolean isSetAcceleratedOssId() {
    return this.acceleratedOssId != null;
  }

  public void setAcceleratedOssIdIsSet(boolean value) {
    if (!value) {
      this.acceleratedOssId = null;
    }
  }

  public void setFieldValue(_Fields field, @org.apache.thrift.annotation.Nullable java.lang.Object value) {
    switch (field) {
    case ACCELERATE_NAME:
      if (value == null) {
        unsetAccelerateName();
      } else {
        setAccelerateName((java.lang.String)value);
      }
      break;

    case SITE_ID:
      if (value == null) {
        unsetSiteId();
      } else {
        setSiteId((java.lang.String)value);
      }
      break;

    case OSS_ID:
      if (value == null) {
        unsetOssId();
      } else {
        setOssId((java.util.List<java.lang.String>)value);
      }
      break;

    case ENABLED:
      if (value == null) {
        unsetEnabled();
      } else {
        setEnabled((java.lang.Boolean)value);
      }
      break;

    case ACCELERATED_SITE_ID:
      if (value == null) {
        unsetAcceleratedSiteId();
      } else {
        setAcceleratedSiteId((java.lang.String)value);
      }
      break;

    case ACCELERATED_OSS_ID:
      if (value == null) {
        unsetAcceleratedOssId();
      } else {
        setAcceleratedOssId((java.util.List<java.lang.String>)value);
      }
      break;

    }
  }

  @org.apache.thrift.annotation.Nullable
  public java.lang.Object getFieldValue(_Fields field) {
    switch (field) {
    case ACCELERATE_NAME:
      return getAccelerateName();

    case SITE_ID:
      return getSiteId();

    case OSS_ID:
      return getOssId();

    case ENABLED:
      return isEnabled();

    case ACCELERATED_SITE_ID:
      return getAcceleratedSiteId();

    case ACCELERATED_OSS_ID:
      return getAcceleratedOssId();

    }
    throw new java.lang.IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new java.lang.IllegalArgumentException();
    }

    switch (field) {
    case ACCELERATE_NAME:
      return isSetAccelerateName();
    case SITE_ID:
      return isSetSiteId();
    case OSS_ID:
      return isSetOssId();
    case ENABLED:
      return isSetEnabled();
    case ACCELERATED_SITE_ID:
      return isSetAcceleratedSiteId();
    case ACCELERATED_OSS_ID:
      return isSetAcceleratedOssId();
    }
    throw new java.lang.IllegalStateException();
  }

  @Override
  public boolean equals(java.lang.Object that) {
    if (that instanceof ncTEVFSSiteAccelerateInfo)
      return this.equals((ncTEVFSSiteAccelerateInfo)that);
    return false;
  }

  public boolean equals(ncTEVFSSiteAccelerateInfo that) {
    if (that == null)
      return false;
    if (this == that)
      return true;

    boolean this_present_accelerateName = true && this.isSetAccelerateName();
    boolean that_present_accelerateName = true && that.isSetAccelerateName();
    if (this_present_accelerateName || that_present_accelerateName) {
      if (!(this_present_accelerateName && that_present_accelerateName))
        return false;
      if (!this.accelerateName.equals(that.accelerateName))
        return false;
    }

    boolean this_present_siteId = true && this.isSetSiteId();
    boolean that_present_siteId = true && that.isSetSiteId();
    if (this_present_siteId || that_present_siteId) {
      if (!(this_present_siteId && that_present_siteId))
        return false;
      if (!this.siteId.equals(that.siteId))
        return false;
    }

    boolean this_present_ossId = true && this.isSetOssId();
    boolean that_present_ossId = true && that.isSetOssId();
    if (this_present_ossId || that_present_ossId) {
      if (!(this_present_ossId && that_present_ossId))
        return false;
      if (!this.ossId.equals(that.ossId))
        return false;
    }

    boolean this_present_enabled = true;
    boolean that_present_enabled = true;
    if (this_present_enabled || that_present_enabled) {
      if (!(this_present_enabled && that_present_enabled))
        return false;
      if (this.enabled != that.enabled)
        return false;
    }

    boolean this_present_acceleratedSiteId = true && this.isSetAcceleratedSiteId();
    boolean that_present_acceleratedSiteId = true && that.isSetAcceleratedSiteId();
    if (this_present_acceleratedSiteId || that_present_acceleratedSiteId) {
      if (!(this_present_acceleratedSiteId && that_present_acceleratedSiteId))
        return false;
      if (!this.acceleratedSiteId.equals(that.acceleratedSiteId))
        return false;
    }

    boolean this_present_acceleratedOssId = true && this.isSetAcceleratedOssId();
    boolean that_present_acceleratedOssId = true && that.isSetAcceleratedOssId();
    if (this_present_acceleratedOssId || that_present_acceleratedOssId) {
      if (!(this_present_acceleratedOssId && that_present_acceleratedOssId))
        return false;
      if (!this.acceleratedOssId.equals(that.acceleratedOssId))
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    int hashCode = 1;

    hashCode = hashCode * 8191 + ((isSetAccelerateName()) ? 131071 : 524287);
    if (isSetAccelerateName())
      hashCode = hashCode * 8191 + accelerateName.hashCode();

    hashCode = hashCode * 8191 + ((isSetSiteId()) ? 131071 : 524287);
    if (isSetSiteId())
      hashCode = hashCode * 8191 + siteId.hashCode();

    hashCode = hashCode * 8191 + ((isSetOssId()) ? 131071 : 524287);
    if (isSetOssId())
      hashCode = hashCode * 8191 + ossId.hashCode();

    hashCode = hashCode * 8191 + ((enabled) ? 131071 : 524287);

    hashCode = hashCode * 8191 + ((isSetAcceleratedSiteId()) ? 131071 : 524287);
    if (isSetAcceleratedSiteId())
      hashCode = hashCode * 8191 + acceleratedSiteId.hashCode();

    hashCode = hashCode * 8191 + ((isSetAcceleratedOssId()) ? 131071 : 524287);
    if (isSetAcceleratedOssId())
      hashCode = hashCode * 8191 + acceleratedOssId.hashCode();

    return hashCode;
  }

  @Override
  public int compareTo(ncTEVFSSiteAccelerateInfo other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = java.lang.Boolean.compare(isSetAccelerateName(), other.isSetAccelerateName());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetAccelerateName()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.accelerateName, other.accelerateName);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.compare(isSetSiteId(), other.isSetSiteId());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetSiteId()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.siteId, other.siteId);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.compare(isSetOssId(), other.isSetOssId());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetOssId()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.ossId, other.ossId);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.compare(isSetEnabled(), other.isSetEnabled());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetEnabled()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.enabled, other.enabled);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.compare(isSetAcceleratedSiteId(), other.isSetAcceleratedSiteId());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetAcceleratedSiteId()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.acceleratedSiteId, other.acceleratedSiteId);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.compare(isSetAcceleratedOssId(), other.isSetAcceleratedOssId());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetAcceleratedOssId()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.acceleratedOssId, other.acceleratedOssId);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  @org.apache.thrift.annotation.Nullable
  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    scheme(iprot).read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    scheme(oprot).write(oprot, this);
  }

  @Override
  public java.lang.String toString() {
    java.lang.StringBuilder sb = new java.lang.StringBuilder("ncTEVFSSiteAccelerateInfo(");
    boolean first = true;

    sb.append("accelerateName:");
    if (this.accelerateName == null) {
      sb.append("null");
    } else {
      sb.append(this.accelerateName);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("siteId:");
    if (this.siteId == null) {
      sb.append("null");
    } else {
      sb.append(this.siteId);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("ossId:");
    if (this.ossId == null) {
      sb.append("null");
    } else {
      sb.append(this.ossId);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("enabled:");
    sb.append(this.enabled);
    first = false;
    if (!first) sb.append(", ");
    sb.append("acceleratedSiteId:");
    if (this.acceleratedSiteId == null) {
      sb.append("null");
    } else {
      sb.append(this.acceleratedSiteId);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("acceleratedOssId:");
    if (this.acceleratedOssId == null) {
      sb.append("null");
    } else {
      sb.append(this.acceleratedOssId);
    }
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    // check for sub-struct validity
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, java.lang.ClassNotFoundException {
    try {
      // it doesn't seem like you should have to do this, but java serialization is wacky, and doesn't call the default constructor.
      __isset_bitfield = 0;
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class ncTEVFSSiteAccelerateInfoStandardSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    public ncTEVFSSiteAccelerateInfoStandardScheme getScheme() {
      return new ncTEVFSSiteAccelerateInfoStandardScheme();
    }
  }

  private static class ncTEVFSSiteAccelerateInfoStandardScheme extends org.apache.thrift.scheme.StandardScheme<ncTEVFSSiteAccelerateInfo> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, ncTEVFSSiteAccelerateInfo struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // ACCELERATE_NAME
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.accelerateName = iprot.readString();
              struct.setAccelerateNameIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 2: // SITE_ID
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.siteId = iprot.readString();
              struct.setSiteIdIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 3: // OSS_ID
            if (schemeField.type == org.apache.thrift.protocol.TType.LIST) {
              {
                org.apache.thrift.protocol.TList _list24 = iprot.readListBegin();
                struct.ossId = new java.util.ArrayList<java.lang.String>(_list24.size);
                @org.apache.thrift.annotation.Nullable java.lang.String _elem25;
                for (int _i26 = 0; _i26 < _list24.size; ++_i26)
                {
                  _elem25 = iprot.readString();
                  struct.ossId.add(_elem25);
                }
                iprot.readListEnd();
              }
              struct.setOssIdIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 4: // ENABLED
            if (schemeField.type == org.apache.thrift.protocol.TType.BOOL) {
              struct.enabled = iprot.readBool();
              struct.setEnabledIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 5: // ACCELERATED_SITE_ID
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.acceleratedSiteId = iprot.readString();
              struct.setAcceleratedSiteIdIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 6: // ACCELERATED_OSS_ID
            if (schemeField.type == org.apache.thrift.protocol.TType.LIST) {
              {
                org.apache.thrift.protocol.TList _list27 = iprot.readListBegin();
                struct.acceleratedOssId = new java.util.ArrayList<java.lang.String>(_list27.size);
                @org.apache.thrift.annotation.Nullable java.lang.String _elem28;
                for (int _i29 = 0; _i29 < _list27.size; ++_i29)
                {
                  _elem28 = iprot.readString();
                  struct.acceleratedOssId.add(_elem28);
                }
                iprot.readListEnd();
              }
              struct.setAcceleratedOssIdIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, ncTEVFSSiteAccelerateInfo struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      if (struct.accelerateName != null) {
        oprot.writeFieldBegin(ACCELERATE_NAME_FIELD_DESC);
        oprot.writeString(struct.accelerateName);
        oprot.writeFieldEnd();
      }
      if (struct.siteId != null) {
        oprot.writeFieldBegin(SITE_ID_FIELD_DESC);
        oprot.writeString(struct.siteId);
        oprot.writeFieldEnd();
      }
      if (struct.ossId != null) {
        oprot.writeFieldBegin(OSS_ID_FIELD_DESC);
        {
          oprot.writeListBegin(new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.STRING, struct.ossId.size()));
          for (java.lang.String _iter30 : struct.ossId)
          {
            oprot.writeString(_iter30);
          }
          oprot.writeListEnd();
        }
        oprot.writeFieldEnd();
      }
      oprot.writeFieldBegin(ENABLED_FIELD_DESC);
      oprot.writeBool(struct.enabled);
      oprot.writeFieldEnd();
      if (struct.acceleratedSiteId != null) {
        oprot.writeFieldBegin(ACCELERATED_SITE_ID_FIELD_DESC);
        oprot.writeString(struct.acceleratedSiteId);
        oprot.writeFieldEnd();
      }
      if (struct.acceleratedOssId != null) {
        oprot.writeFieldBegin(ACCELERATED_OSS_ID_FIELD_DESC);
        {
          oprot.writeListBegin(new org.apache.thrift.protocol.TList(org.apache.thrift.protocol.TType.STRING, struct.acceleratedOssId.size()));
          for (java.lang.String _iter31 : struct.acceleratedOssId)
          {
            oprot.writeString(_iter31);
          }
          oprot.writeListEnd();
        }
        oprot.writeFieldEnd();
      }
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class ncTEVFSSiteAccelerateInfoTupleSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    public ncTEVFSSiteAccelerateInfoTupleScheme getScheme() {
      return new ncTEVFSSiteAccelerateInfoTupleScheme();
    }
  }

  private static class ncTEVFSSiteAccelerateInfoTupleScheme extends org.apache.thrift.scheme.TupleScheme<ncTEVFSSiteAccelerateInfo> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, ncTEVFSSiteAccelerateInfo struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol oprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      java.util.BitSet optionals = new java.util.BitSet();
      if (struct.isSetAccelerateName()) {
        optionals.set(0);
      }
      if (struct.isSetSiteId()) {
        optionals.set(1);
      }
      if (struct.isSetOssId()) {
        optionals.set(2);
      }
      if (struct.isSetEnabled()) {
        optionals.set(3);
      }
      if (struct.isSetAcceleratedSiteId()) {
        optionals.set(4);
      }
      if (struct.isSetAcceleratedOssId()) {
        optionals.set(5);
      }
      oprot.writeBitSet(optionals, 6);
      if (struct.isSetAccelerateName()) {
        oprot.writeString(struct.accelerateName);
      }
      if (struct.isSetSiteId()) {
        oprot.writeString(struct.siteId);
      }
      if (struct.isSetOssId()) {
        {
          oprot.writeI32(struct.ossId.size());
          for (java.lang.String _iter32 : struct.ossId)
          {
            oprot.writeString(_iter32);
          }
        }
      }
      if (struct.isSetEnabled()) {
        oprot.writeBool(struct.enabled);
      }
      if (struct.isSetAcceleratedSiteId()) {
        oprot.writeString(struct.acceleratedSiteId);
      }
      if (struct.isSetAcceleratedOssId()) {
        {
          oprot.writeI32(struct.acceleratedOssId.size());
          for (java.lang.String _iter33 : struct.acceleratedOssId)
          {
            oprot.writeString(_iter33);
          }
        }
      }
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, ncTEVFSSiteAccelerateInfo struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol iprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      java.util.BitSet incoming = iprot.readBitSet(6);
      if (incoming.get(0)) {
        struct.accelerateName = iprot.readString();
        struct.setAccelerateNameIsSet(true);
      }
      if (incoming.get(1)) {
        struct.siteId = iprot.readString();
        struct.setSiteIdIsSet(true);
      }
      if (incoming.get(2)) {
        {
          org.apache.thrift.protocol.TList _list34 = iprot.readListBegin(org.apache.thrift.protocol.TType.STRING);
          struct.ossId = new java.util.ArrayList<java.lang.String>(_list34.size);
          @org.apache.thrift.annotation.Nullable java.lang.String _elem35;
          for (int _i36 = 0; _i36 < _list34.size; ++_i36)
          {
            _elem35 = iprot.readString();
            struct.ossId.add(_elem35);
          }
        }
        struct.setOssIdIsSet(true);
      }
      if (incoming.get(3)) {
        struct.enabled = iprot.readBool();
        struct.setEnabledIsSet(true);
      }
      if (incoming.get(4)) {
        struct.acceleratedSiteId = iprot.readString();
        struct.setAcceleratedSiteIdIsSet(true);
      }
      if (incoming.get(5)) {
        {
          org.apache.thrift.protocol.TList _list37 = iprot.readListBegin(org.apache.thrift.protocol.TType.STRING);
          struct.acceleratedOssId = new java.util.ArrayList<java.lang.String>(_list37.size);
          @org.apache.thrift.annotation.Nullable java.lang.String _elem38;
          for (int _i39 = 0; _i39 < _list37.size; ++_i39)
          {
            _elem38 = iprot.readString();
            struct.acceleratedOssId.add(_elem38);
          }
        }
        struct.setAcceleratedOssIdIsSet(true);
      }
    }
  }

  private static <S extends org.apache.thrift.scheme.IScheme> S scheme(org.apache.thrift.protocol.TProtocol proto) {
    return (org.apache.thrift.scheme.StandardScheme.class.equals(proto.getScheme()) ? STANDARD_SCHEME_FACTORY : TUPLE_SCHEME_FACTORY).getScheme();
  }
}

