/**
 * Autogenerated by Thrift Compiler (0.14.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.aishu.wf.core.thrift.evfs;

@SuppressWarnings({"cast", "rawtypes", "serial", "unchecked", "unused"})
/**
 * 文件和最新元数据信息
 */
@javax.annotation.Generated(value = "Autogenerated by Thrift Compiler (0.14.2)", date = "2023-06-06")
public class ncTEVFSFileInfo implements org.apache.thrift.TBase<ncTEVFSFileInfo, ncTEVFSFileInfo._Fields>, java.io.Serializable, Cloneable, Comparable<ncTEVFSFileInfo> {
  private static final org.apache.thrift.protocol.TStruct STRUCT_DESC = new org.apache.thrift.protocol.TStruct("ncTEVFSFileInfo");

  private static final org.apache.thrift.protocol.TField DOC_ID_FIELD_DESC = new org.apache.thrift.protocol.TField("docId", org.apache.thrift.protocol.TType.STRING, (short)1);
  private static final org.apache.thrift.protocol.TField PATH_FIELD_DESC = new org.apache.thrift.protocol.TField("path", org.apache.thrift.protocol.TType.STRING, (short)2);
  private static final org.apache.thrift.protocol.TField RETAINED_FIELD_DESC = new org.apache.thrift.protocol.TField("retained", org.apache.thrift.protocol.TType.BOOL, (short)3);
  private static final org.apache.thrift.protocol.TField ATTRIBUTE_FIELD_DESC = new org.apache.thrift.protocol.TField("attribute", org.apache.thrift.protocol.TType.STRUCT, (short)4);
  private static final org.apache.thrift.protocol.TField METADATA_FIELD_DESC = new org.apache.thrift.protocol.TField("metadata", org.apache.thrift.protocol.TType.STRUCT, (short)5);

  private static final org.apache.thrift.scheme.SchemeFactory STANDARD_SCHEME_FACTORY = new ncTEVFSFileInfoStandardSchemeFactory();
  private static final org.apache.thrift.scheme.SchemeFactory TUPLE_SCHEME_FACTORY = new ncTEVFSFileInfoTupleSchemeFactory();

  public @org.apache.thrift.annotation.Nullable java.lang.String docId; // required
  public @org.apache.thrift.annotation.Nullable java.lang.String path; // required
  public boolean retained; // required
  public @org.apache.thrift.annotation.Nullable ncTEVFSFileAttribute attribute; // required
  public @org.apache.thrift.annotation.Nullable ncTEVFSFileMetadata metadata; // required

  /** The set of fields this struct contains, along with convenience methods for finding and manipulating them. */
  public enum _Fields implements org.apache.thrift.TFieldIdEnum {
    DOC_ID((short)1, "docId"),
    PATH((short)2, "path"),
    RETAINED((short)3, "retained"),
    ATTRIBUTE((short)4, "attribute"),
    METADATA((short)5, "metadata");

    private static final java.util.Map<java.lang.String, _Fields> byName = new java.util.HashMap<java.lang.String, _Fields>();

    static {
      for (_Fields field : java.util.EnumSet.allOf(_Fields.class)) {
        byName.put(field.getFieldName(), field);
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, or null if its not found.
     */
    @org.apache.thrift.annotation.Nullable
    public static _Fields findByThriftId(int fieldId) {
      switch(fieldId) {
        case 1: // DOC_ID
          return DOC_ID;
        case 2: // PATH
          return PATH;
        case 3: // RETAINED
          return RETAINED;
        case 4: // ATTRIBUTE
          return ATTRIBUTE;
        case 5: // METADATA
          return METADATA;
        default:
          return null;
      }
    }

    /**
     * Find the _Fields constant that matches fieldId, throwing an exception
     * if it is not found.
     */
    public static _Fields findByThriftIdOrThrow(int fieldId) {
      _Fields fields = findByThriftId(fieldId);
      if (fields == null) throw new java.lang.IllegalArgumentException("Field " + fieldId + " doesn't exist!");
      return fields;
    }

    /**
     * Find the _Fields constant that matches name, or null if its not found.
     */
    @org.apache.thrift.annotation.Nullable
    public static _Fields findByName(java.lang.String name) {
      return byName.get(name);
    }

    private final short _thriftId;
    private final java.lang.String _fieldName;

    _Fields(short thriftId, java.lang.String fieldName) {
      _thriftId = thriftId;
      _fieldName = fieldName;
    }

    public short getThriftFieldId() {
      return _thriftId;
    }

    public java.lang.String getFieldName() {
      return _fieldName;
    }
  }

  // isset id assignments
  private static final int __RETAINED_ISSET_ID = 0;
  private byte __isset_bitfield = 0;
  public static final java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> metaDataMap;
  static {
    java.util.Map<_Fields, org.apache.thrift.meta_data.FieldMetaData> tmpMap = new java.util.EnumMap<_Fields, org.apache.thrift.meta_data.FieldMetaData>(_Fields.class);
    tmpMap.put(_Fields.DOC_ID, new org.apache.thrift.meta_data.FieldMetaData("docId", org.apache.thrift.TFieldRequirementType.REQUIRED, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.PATH, new org.apache.thrift.meta_data.FieldMetaData("path", org.apache.thrift.TFieldRequirementType.REQUIRED, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.STRING)));
    tmpMap.put(_Fields.RETAINED, new org.apache.thrift.meta_data.FieldMetaData("retained", org.apache.thrift.TFieldRequirementType.REQUIRED, 
        new org.apache.thrift.meta_data.FieldValueMetaData(org.apache.thrift.protocol.TType.BOOL)));
    tmpMap.put(_Fields.ATTRIBUTE, new org.apache.thrift.meta_data.FieldMetaData("attribute", org.apache.thrift.TFieldRequirementType.REQUIRED, 
        new org.apache.thrift.meta_data.StructMetaData(org.apache.thrift.protocol.TType.STRUCT, ncTEVFSFileAttribute.class)));
    tmpMap.put(_Fields.METADATA, new org.apache.thrift.meta_data.FieldMetaData("metadata", org.apache.thrift.TFieldRequirementType.REQUIRED, 
        new org.apache.thrift.meta_data.StructMetaData(org.apache.thrift.protocol.TType.STRUCT, ncTEVFSFileMetadata.class)));
    metaDataMap = java.util.Collections.unmodifiableMap(tmpMap);
    org.apache.thrift.meta_data.FieldMetaData.addStructMetaDataMap(ncTEVFSFileInfo.class, metaDataMap);
  }

  public ncTEVFSFileInfo() {
  }

  public ncTEVFSFileInfo(
    java.lang.String docId,
    java.lang.String path,
    boolean retained,
    ncTEVFSFileAttribute attribute,
    ncTEVFSFileMetadata metadata)
  {
    this();
    this.docId = docId;
    this.path = path;
    this.retained = retained;
    setRetainedIsSet(true);
    this.attribute = attribute;
    this.metadata = metadata;
  }

  /**
   * Performs a deep copy on <i>other</i>.
   */
  public ncTEVFSFileInfo(ncTEVFSFileInfo other) {
    __isset_bitfield = other.__isset_bitfield;
    if (other.isSetDocId()) {
      this.docId = other.docId;
    }
    if (other.isSetPath()) {
      this.path = other.path;
    }
    this.retained = other.retained;
    if (other.isSetAttribute()) {
      this.attribute = new ncTEVFSFileAttribute(other.attribute);
    }
    if (other.isSetMetadata()) {
      this.metadata = new ncTEVFSFileMetadata(other.metadata);
    }
  }

  public ncTEVFSFileInfo deepCopy() {
    return new ncTEVFSFileInfo(this);
  }

  @Override
  public void clear() {
    this.docId = null;
    this.path = null;
    setRetainedIsSet(false);
    this.retained = false;
    this.attribute = null;
    this.metadata = null;
  }

  @org.apache.thrift.annotation.Nullable
  public java.lang.String getDocId() {
    return this.docId;
  }

  public ncTEVFSFileInfo setDocId(@org.apache.thrift.annotation.Nullable java.lang.String docId) {
    this.docId = docId;
    return this;
  }

  public void unsetDocId() {
    this.docId = null;
  }

  /** Returns true if field docId is set (has been assigned a value) and false otherwise */
  public boolean isSetDocId() {
    return this.docId != null;
  }

  public void setDocIdIsSet(boolean value) {
    if (!value) {
      this.docId = null;
    }
  }

  @org.apache.thrift.annotation.Nullable
  public java.lang.String getPath() {
    return this.path;
  }

  public ncTEVFSFileInfo setPath(@org.apache.thrift.annotation.Nullable java.lang.String path) {
    this.path = path;
    return this;
  }

  public void unsetPath() {
    this.path = null;
  }

  /** Returns true if field path is set (has been assigned a value) and false otherwise */
  public boolean isSetPath() {
    return this.path != null;
  }

  public void setPathIsSet(boolean value) {
    if (!value) {
      this.path = null;
    }
  }

  public boolean isRetained() {
    return this.retained;
  }

  public ncTEVFSFileInfo setRetained(boolean retained) {
    this.retained = retained;
    setRetainedIsSet(true);
    return this;
  }

  public void unsetRetained() {
    __isset_bitfield = org.apache.thrift.EncodingUtils.clearBit(__isset_bitfield, __RETAINED_ISSET_ID);
  }

  /** Returns true if field retained is set (has been assigned a value) and false otherwise */
  public boolean isSetRetained() {
    return org.apache.thrift.EncodingUtils.testBit(__isset_bitfield, __RETAINED_ISSET_ID);
  }

  public void setRetainedIsSet(boolean value) {
    __isset_bitfield = org.apache.thrift.EncodingUtils.setBit(__isset_bitfield, __RETAINED_ISSET_ID, value);
  }

  @org.apache.thrift.annotation.Nullable
  public ncTEVFSFileAttribute getAttribute() {
    return this.attribute;
  }

  public ncTEVFSFileInfo setAttribute(@org.apache.thrift.annotation.Nullable ncTEVFSFileAttribute attribute) {
    this.attribute = attribute;
    return this;
  }

  public void unsetAttribute() {
    this.attribute = null;
  }

  /** Returns true if field attribute is set (has been assigned a value) and false otherwise */
  public boolean isSetAttribute() {
    return this.attribute != null;
  }

  public void setAttributeIsSet(boolean value) {
    if (!value) {
      this.attribute = null;
    }
  }

  @org.apache.thrift.annotation.Nullable
  public ncTEVFSFileMetadata getMetadata() {
    return this.metadata;
  }

  public ncTEVFSFileInfo setMetadata(@org.apache.thrift.annotation.Nullable ncTEVFSFileMetadata metadata) {
    this.metadata = metadata;
    return this;
  }

  public void unsetMetadata() {
    this.metadata = null;
  }

  /** Returns true if field metadata is set (has been assigned a value) and false otherwise */
  public boolean isSetMetadata() {
    return this.metadata != null;
  }

  public void setMetadataIsSet(boolean value) {
    if (!value) {
      this.metadata = null;
    }
  }

  public void setFieldValue(_Fields field, @org.apache.thrift.annotation.Nullable java.lang.Object value) {
    switch (field) {
    case DOC_ID:
      if (value == null) {
        unsetDocId();
      } else {
        setDocId((java.lang.String)value);
      }
      break;

    case PATH:
      if (value == null) {
        unsetPath();
      } else {
        setPath((java.lang.String)value);
      }
      break;

    case RETAINED:
      if (value == null) {
        unsetRetained();
      } else {
        setRetained((java.lang.Boolean)value);
      }
      break;

    case ATTRIBUTE:
      if (value == null) {
        unsetAttribute();
      } else {
        setAttribute((ncTEVFSFileAttribute)value);
      }
      break;

    case METADATA:
      if (value == null) {
        unsetMetadata();
      } else {
        setMetadata((ncTEVFSFileMetadata)value);
      }
      break;

    }
  }

  @org.apache.thrift.annotation.Nullable
  public java.lang.Object getFieldValue(_Fields field) {
    switch (field) {
    case DOC_ID:
      return getDocId();

    case PATH:
      return getPath();

    case RETAINED:
      return isRetained();

    case ATTRIBUTE:
      return getAttribute();

    case METADATA:
      return getMetadata();

    }
    throw new java.lang.IllegalStateException();
  }

  /** Returns true if field corresponding to fieldID is set (has been assigned a value) and false otherwise */
  public boolean isSet(_Fields field) {
    if (field == null) {
      throw new java.lang.IllegalArgumentException();
    }

    switch (field) {
    case DOC_ID:
      return isSetDocId();
    case PATH:
      return isSetPath();
    case RETAINED:
      return isSetRetained();
    case ATTRIBUTE:
      return isSetAttribute();
    case METADATA:
      return isSetMetadata();
    }
    throw new java.lang.IllegalStateException();
  }

  @Override
  public boolean equals(java.lang.Object that) {
    if (that instanceof ncTEVFSFileInfo)
      return this.equals((ncTEVFSFileInfo)that);
    return false;
  }

  public boolean equals(ncTEVFSFileInfo that) {
    if (that == null)
      return false;
    if (this == that)
      return true;

    boolean this_present_docId = true && this.isSetDocId();
    boolean that_present_docId = true && that.isSetDocId();
    if (this_present_docId || that_present_docId) {
      if (!(this_present_docId && that_present_docId))
        return false;
      if (!this.docId.equals(that.docId))
        return false;
    }

    boolean this_present_path = true && this.isSetPath();
    boolean that_present_path = true && that.isSetPath();
    if (this_present_path || that_present_path) {
      if (!(this_present_path && that_present_path))
        return false;
      if (!this.path.equals(that.path))
        return false;
    }

    boolean this_present_retained = true;
    boolean that_present_retained = true;
    if (this_present_retained || that_present_retained) {
      if (!(this_present_retained && that_present_retained))
        return false;
      if (this.retained != that.retained)
        return false;
    }

    boolean this_present_attribute = true && this.isSetAttribute();
    boolean that_present_attribute = true && that.isSetAttribute();
    if (this_present_attribute || that_present_attribute) {
      if (!(this_present_attribute && that_present_attribute))
        return false;
      if (!this.attribute.equals(that.attribute))
        return false;
    }

    boolean this_present_metadata = true && this.isSetMetadata();
    boolean that_present_metadata = true && that.isSetMetadata();
    if (this_present_metadata || that_present_metadata) {
      if (!(this_present_metadata && that_present_metadata))
        return false;
      if (!this.metadata.equals(that.metadata))
        return false;
    }

    return true;
  }

  @Override
  public int hashCode() {
    int hashCode = 1;

    hashCode = hashCode * 8191 + ((isSetDocId()) ? 131071 : 524287);
    if (isSetDocId())
      hashCode = hashCode * 8191 + docId.hashCode();

    hashCode = hashCode * 8191 + ((isSetPath()) ? 131071 : 524287);
    if (isSetPath())
      hashCode = hashCode * 8191 + path.hashCode();

    hashCode = hashCode * 8191 + ((retained) ? 131071 : 524287);

    hashCode = hashCode * 8191 + ((isSetAttribute()) ? 131071 : 524287);
    if (isSetAttribute())
      hashCode = hashCode * 8191 + attribute.hashCode();

    hashCode = hashCode * 8191 + ((isSetMetadata()) ? 131071 : 524287);
    if (isSetMetadata())
      hashCode = hashCode * 8191 + metadata.hashCode();

    return hashCode;
  }

  @Override
  public int compareTo(ncTEVFSFileInfo other) {
    if (!getClass().equals(other.getClass())) {
      return getClass().getName().compareTo(other.getClass().getName());
    }

    int lastComparison = 0;

    lastComparison = java.lang.Boolean.compare(isSetDocId(), other.isSetDocId());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetDocId()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.docId, other.docId);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.compare(isSetPath(), other.isSetPath());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetPath()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.path, other.path);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.compare(isSetRetained(), other.isSetRetained());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetRetained()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.retained, other.retained);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.compare(isSetAttribute(), other.isSetAttribute());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetAttribute()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.attribute, other.attribute);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    lastComparison = java.lang.Boolean.compare(isSetMetadata(), other.isSetMetadata());
    if (lastComparison != 0) {
      return lastComparison;
    }
    if (isSetMetadata()) {
      lastComparison = org.apache.thrift.TBaseHelper.compareTo(this.metadata, other.metadata);
      if (lastComparison != 0) {
        return lastComparison;
      }
    }
    return 0;
  }

  @org.apache.thrift.annotation.Nullable
  public _Fields fieldForId(int fieldId) {
    return _Fields.findByThriftId(fieldId);
  }

  public void read(org.apache.thrift.protocol.TProtocol iprot) throws org.apache.thrift.TException {
    scheme(iprot).read(iprot, this);
  }

  public void write(org.apache.thrift.protocol.TProtocol oprot) throws org.apache.thrift.TException {
    scheme(oprot).write(oprot, this);
  }

  @Override
  public java.lang.String toString() {
    java.lang.StringBuilder sb = new java.lang.StringBuilder("ncTEVFSFileInfo(");
    boolean first = true;

    sb.append("docId:");
    if (this.docId == null) {
      sb.append("null");
    } else {
      sb.append(this.docId);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("path:");
    if (this.path == null) {
      sb.append("null");
    } else {
      sb.append(this.path);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("retained:");
    sb.append(this.retained);
    first = false;
    if (!first) sb.append(", ");
    sb.append("attribute:");
    if (this.attribute == null) {
      sb.append("null");
    } else {
      sb.append(this.attribute);
    }
    first = false;
    if (!first) sb.append(", ");
    sb.append("metadata:");
    if (this.metadata == null) {
      sb.append("null");
    } else {
      sb.append(this.metadata);
    }
    first = false;
    sb.append(")");
    return sb.toString();
  }

  public void validate() throws org.apache.thrift.TException {
    // check for required fields
    if (docId == null) {
      throw new org.apache.thrift.protocol.TProtocolException("Required field 'docId' was not present! Struct: " + toString());
    }
    if (path == null) {
      throw new org.apache.thrift.protocol.TProtocolException("Required field 'path' was not present! Struct: " + toString());
    }
    // alas, we cannot check 'retained' because it's a primitive and you chose the non-beans generator.
    if (attribute == null) {
      throw new org.apache.thrift.protocol.TProtocolException("Required field 'attribute' was not present! Struct: " + toString());
    }
    if (metadata == null) {
      throw new org.apache.thrift.protocol.TProtocolException("Required field 'metadata' was not present! Struct: " + toString());
    }
    // check for sub-struct validity
    if (attribute != null) {
      attribute.validate();
    }
    if (metadata != null) {
      metadata.validate();
    }
  }

  private void writeObject(java.io.ObjectOutputStream out) throws java.io.IOException {
    try {
      write(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(out)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private void readObject(java.io.ObjectInputStream in) throws java.io.IOException, java.lang.ClassNotFoundException {
    try {
      // it doesn't seem like you should have to do this, but java serialization is wacky, and doesn't call the default constructor.
      __isset_bitfield = 0;
      read(new org.apache.thrift.protocol.TCompactProtocol(new org.apache.thrift.transport.TIOStreamTransport(in)));
    } catch (org.apache.thrift.TException te) {
      throw new java.io.IOException(te);
    }
  }

  private static class ncTEVFSFileInfoStandardSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    public ncTEVFSFileInfoStandardScheme getScheme() {
      return new ncTEVFSFileInfoStandardScheme();
    }
  }

  private static class ncTEVFSFileInfoStandardScheme extends org.apache.thrift.scheme.StandardScheme<ncTEVFSFileInfo> {

    public void read(org.apache.thrift.protocol.TProtocol iprot, ncTEVFSFileInfo struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TField schemeField;
      iprot.readStructBegin();
      while (true)
      {
        schemeField = iprot.readFieldBegin();
        if (schemeField.type == org.apache.thrift.protocol.TType.STOP) { 
          break;
        }
        switch (schemeField.id) {
          case 1: // DOC_ID
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.docId = iprot.readString();
              struct.setDocIdIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 2: // PATH
            if (schemeField.type == org.apache.thrift.protocol.TType.STRING) {
              struct.path = iprot.readString();
              struct.setPathIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 3: // RETAINED
            if (schemeField.type == org.apache.thrift.protocol.TType.BOOL) {
              struct.retained = iprot.readBool();
              struct.setRetainedIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 4: // ATTRIBUTE
            if (schemeField.type == org.apache.thrift.protocol.TType.STRUCT) {
              struct.attribute = new ncTEVFSFileAttribute();
              struct.attribute.read(iprot);
              struct.setAttributeIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          case 5: // METADATA
            if (schemeField.type == org.apache.thrift.protocol.TType.STRUCT) {
              struct.metadata = new ncTEVFSFileMetadata();
              struct.metadata.read(iprot);
              struct.setMetadataIsSet(true);
            } else { 
              org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
            }
            break;
          default:
            org.apache.thrift.protocol.TProtocolUtil.skip(iprot, schemeField.type);
        }
        iprot.readFieldEnd();
      }
      iprot.readStructEnd();

      // check for required fields of primitive type, which can't be checked in the validate method
      if (!struct.isSetRetained()) {
        throw new org.apache.thrift.protocol.TProtocolException("Required field 'retained' was not found in serialized data! Struct: " + toString());
      }
      struct.validate();
    }

    public void write(org.apache.thrift.protocol.TProtocol oprot, ncTEVFSFileInfo struct) throws org.apache.thrift.TException {
      struct.validate();

      oprot.writeStructBegin(STRUCT_DESC);
      if (struct.docId != null) {
        oprot.writeFieldBegin(DOC_ID_FIELD_DESC);
        oprot.writeString(struct.docId);
        oprot.writeFieldEnd();
      }
      if (struct.path != null) {
        oprot.writeFieldBegin(PATH_FIELD_DESC);
        oprot.writeString(struct.path);
        oprot.writeFieldEnd();
      }
      oprot.writeFieldBegin(RETAINED_FIELD_DESC);
      oprot.writeBool(struct.retained);
      oprot.writeFieldEnd();
      if (struct.attribute != null) {
        oprot.writeFieldBegin(ATTRIBUTE_FIELD_DESC);
        struct.attribute.write(oprot);
        oprot.writeFieldEnd();
      }
      if (struct.metadata != null) {
        oprot.writeFieldBegin(METADATA_FIELD_DESC);
        struct.metadata.write(oprot);
        oprot.writeFieldEnd();
      }
      oprot.writeFieldStop();
      oprot.writeStructEnd();
    }

  }

  private static class ncTEVFSFileInfoTupleSchemeFactory implements org.apache.thrift.scheme.SchemeFactory {
    public ncTEVFSFileInfoTupleScheme getScheme() {
      return new ncTEVFSFileInfoTupleScheme();
    }
  }

  private static class ncTEVFSFileInfoTupleScheme extends org.apache.thrift.scheme.TupleScheme<ncTEVFSFileInfo> {

    @Override
    public void write(org.apache.thrift.protocol.TProtocol prot, ncTEVFSFileInfo struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol oprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      oprot.writeString(struct.docId);
      oprot.writeString(struct.path);
      oprot.writeBool(struct.retained);
      struct.attribute.write(oprot);
      struct.metadata.write(oprot);
    }

    @Override
    public void read(org.apache.thrift.protocol.TProtocol prot, ncTEVFSFileInfo struct) throws org.apache.thrift.TException {
      org.apache.thrift.protocol.TTupleProtocol iprot = (org.apache.thrift.protocol.TTupleProtocol) prot;
      struct.docId = iprot.readString();
      struct.setDocIdIsSet(true);
      struct.path = iprot.readString();
      struct.setPathIsSet(true);
      struct.retained = iprot.readBool();
      struct.setRetainedIsSet(true);
      struct.attribute = new ncTEVFSFileAttribute();
      struct.attribute.read(iprot);
      struct.setAttributeIsSet(true);
      struct.metadata = new ncTEVFSFileMetadata();
      struct.metadata.read(iprot);
      struct.setMetadataIsSet(true);
    }
  }

  private static <S extends org.apache.thrift.scheme.IScheme> S scheme(org.apache.thrift.protocol.TProtocol proto) {
    return (org.apache.thrift.scheme.StandardScheme.class.equals(proto.getScheme()) ? STANDARD_SCHEME_FACTORY : TUPLE_SCHEME_FACTORY).getScheme();
  }
}

