/**
 * Autogenerated by Thrift Compiler (0.14.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.aishu.wf.core.thrift.evfs;


/**
 * 操作统计中的操作类型
 */
@javax.annotation.Generated(value = "Autogenerated by Thrift Compiler (0.14.2)", date = "2023-06-06")
public enum ncTEVFSOperatedType implements org.apache.thrift.TEnum {
  NCT_EVFS_OP_UNKNOWN(0),
  NCT_EVFS_OP_DIR_CREATED(1),
  NCT_EVFS_OP_DIR_DEL_TO_RECYCLE(2),
  NCT_EVFS_OP_DIR_LIST(3),
  NCT_EVFS_OP_DIR_RENAME(4),
  NCT_EVFS_OP_DIR_RESOTRE(5),
  NCT_EVFS_OP_DIR_DELETE(6),
  NCT_EVFS_OP_DIR_MOVE(7),
  NCT_EVFS_OP_DIR_COPY(8),
  NCT_EVFS_OP_FILE_CREATED(11),
  NCT_EVFS_OP_FILE_MODIFY(12),
  NCT_EVFS_OP_FILE_DEL_TO_RECYCLE(13),
  NCT_EVFS_OP_FILE_DOWNLOAD(14),
  NCT_EVFS_OP_FILE_RAPID_SUCCEE(15),
  NCT_EVFS_OP_FILE_RAPID_FAIL(16),
  NCT_EVFS_OP_FILE_RENAME(17),
  NCT_EVFS_OP_FILE_RESTORE(18),
  NCT_EVFS_OP_FILE_DELETE(19),
  NCT_EVFS_OP_FILE_COPY(20),
  NCT_EVFS_OP_FILE_MOVE(21);

  private final int value;

  private ncTEVFSOperatedType(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  @org.apache.thrift.annotation.Nullable
  public static ncTEVFSOperatedType findByValue(int value) { 
    switch (value) {
      case 0:
        return NCT_EVFS_OP_UNKNOWN;
      case 1:
        return NCT_EVFS_OP_DIR_CREATED;
      case 2:
        return NCT_EVFS_OP_DIR_DEL_TO_RECYCLE;
      case 3:
        return NCT_EVFS_OP_DIR_LIST;
      case 4:
        return NCT_EVFS_OP_DIR_RENAME;
      case 5:
        return NCT_EVFS_OP_DIR_RESOTRE;
      case 6:
        return NCT_EVFS_OP_DIR_DELETE;
      case 7:
        return NCT_EVFS_OP_DIR_MOVE;
      case 8:
        return NCT_EVFS_OP_DIR_COPY;
      case 11:
        return NCT_EVFS_OP_FILE_CREATED;
      case 12:
        return NCT_EVFS_OP_FILE_MODIFY;
      case 13:
        return NCT_EVFS_OP_FILE_DEL_TO_RECYCLE;
      case 14:
        return NCT_EVFS_OP_FILE_DOWNLOAD;
      case 15:
        return NCT_EVFS_OP_FILE_RAPID_SUCCEE;
      case 16:
        return NCT_EVFS_OP_FILE_RAPID_FAIL;
      case 17:
        return NCT_EVFS_OP_FILE_RENAME;
      case 18:
        return NCT_EVFS_OP_FILE_RESTORE;
      case 19:
        return NCT_EVFS_OP_FILE_DELETE;
      case 20:
        return NCT_EVFS_OP_FILE_COPY;
      case 21:
        return NCT_EVFS_OP_FILE_MOVE;
      default:
        return null;
    }
  }
}
