/**
 * Autogenerated by Thrift Compiler (0.14.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.aishu.wf.core.thrift.evfs;


/**
 * 支持的对象存储服务
 * ASU   : AnyShare Universal
 * CEPH  : Ceph
 * OSS   : 阿里云
 * BOS   : 百度开放云
 * QINIU : 七牛云存储
 * AWS   : 亚马逊
 * AWSCN : 亚马逊中国
 * AZURE : 微软Azure
 * HCPS3 : 日立
 * UCLOUD: UCLOUD UFile对象存储
 */
@javax.annotation.Generated(value = "Autogenerated by Thrift Compiler (0.14.2)", date = "2023-06-06")
public enum ncTOSSBucketStyle implements org.apache.thrift.TEnum {
  NCT_PATH_STYLE(0),
  NCT_VIRTUAL_HOSTING_STYLE(1);

  private final int value;

  private ncTOSSBucketStyle(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  @org.apache.thrift.annotation.Nullable
  public static ncTOSSBucketStyle findByValue(int value) { 
    switch (value) {
      case 0:
        return NCT_PATH_STYLE;
      case 1:
        return NCT_VIRTUAL_HOSTING_STYLE;
      default:
        return null;
    }
  }
}
