// Code generated by MockGen. DO NOT EDIT.
// Source: ./release.go
//
// Generated by this command:
//
//	mockgen -source=./release.go -destination ./idbaccessmock/release.go -package idbaccessmock
//

// Package idbaccessmock is a generated GoMock package.
package idbaccessmock

import (
	context "context"
	sql "database/sql"
	reflect "reflect"

	squarereq "devops.aishu.cn/AISHUDevOps/DIP/_git/agent-factory/src/driveradapter/api/rdto/square/squarereq"
	dapo "devops.aishu.cn/AISHUDevOps/DIP/_git/agent-factory/src/infra/persistence/dapo"
	comvalobj "devops.aishu.cn/AISHUDevOps/DIP/_git/agent-go-common-pkg/src/domain/valueobject/comvalobj"
	sqlx "devops.aishu.cn/AISHUDevOps/ONE-Architecture/_git/proton-rds-sdk-go/sqlx"
	gomock "go.uber.org/mock/gomock"
)

// MockIReleaseRepo is a mock of IReleaseRepo interface.
type MockIReleaseRepo struct {
	ctrl     *gomock.Controller
	recorder *MockIReleaseRepoMockRecorder
	isgomock struct{}
}

// MockIReleaseRepoMockRecorder is the mock recorder for MockIReleaseRepo.
type MockIReleaseRepoMockRecorder struct {
	mock *MockIReleaseRepo
}

// NewMockIReleaseRepo creates a new mock instance.
func NewMockIReleaseRepo(ctrl *gomock.Controller) *MockIReleaseRepo {
	mock := &MockIReleaseRepo{ctrl: ctrl}
	mock.recorder = &MockIReleaseRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIReleaseRepo) EXPECT() *MockIReleaseRepoMockRecorder {
	return m.recorder
}

// BeginTx mocks base method.
func (m *MockIReleaseRepo) BeginTx(ctx context.Context) (*sql.Tx, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BeginTx", ctx)
	ret0, _ := ret[0].(*sql.Tx)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BeginTx indicates an expected call of BeginTx.
func (mr *MockIReleaseRepoMockRecorder) BeginTx(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BeginTx", reflect.TypeOf((*MockIReleaseRepo)(nil).BeginTx), ctx)
}

// Create mocks base method.
func (m *MockIReleaseRepo) Create(ctx context.Context, tx *sql.Tx, po *dapo.ReleasePO) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, tx, po)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockIReleaseRepoMockRecorder) Create(ctx, tx, po any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockIReleaseRepo)(nil).Create), ctx, tx, po)
}

// DeleteByAgentID mocks base method.
func (m *MockIReleaseRepo) DeleteByAgentID(ctx context.Context, tx *sql.Tx, agentID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteByAgentID", ctx, tx, agentID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteByAgentID indicates an expected call of DeleteByAgentID.
func (mr *MockIReleaseRepoMockRecorder) DeleteByAgentID(ctx, tx, agentID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteByAgentID", reflect.TypeOf((*MockIReleaseRepo)(nil).DeleteByAgentID), ctx, tx, agentID)
}

// GetByAgentID mocks base method.
func (m *MockIReleaseRepo) GetByAgentID(ctx context.Context, agentID string) (*dapo.ReleasePO, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByAgentID", ctx, agentID)
	ret0, _ := ret[0].(*dapo.ReleasePO)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByAgentID indicates an expected call of GetByAgentID.
func (mr *MockIReleaseRepoMockRecorder) GetByAgentID(ctx, agentID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByAgentID", reflect.TypeOf((*MockIReleaseRepo)(nil).GetByAgentID), ctx, agentID)
}

// GetDB mocks base method.
func (m *MockIReleaseRepo) GetDB() *sqlx.DB {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDB")
	ret0, _ := ret[0].(*sqlx.DB)
	return ret0
}

// GetDB indicates an expected call of GetDB.
func (mr *MockIReleaseRepoMockRecorder) GetDB() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDB", reflect.TypeOf((*MockIReleaseRepo)(nil).GetDB))
}

// GetMapByAgentIDs mocks base method.
func (m *MockIReleaseRepo) GetMapByAgentIDs(ctx context.Context, agentIDS []string) (map[string]*dapo.ReleasePO, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMapByAgentIDs", ctx, agentIDS)
	ret0, _ := ret[0].(map[string]*dapo.ReleasePO)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMapByAgentIDs indicates an expected call of GetMapByAgentIDs.
func (mr *MockIReleaseRepoMockRecorder) GetMapByAgentIDs(ctx, agentIDS any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMapByAgentIDs", reflect.TypeOf((*MockIReleaseRepo)(nil).GetMapByAgentIDs), ctx, agentIDS)
}

// GetMapByUniqFlags mocks base method.
func (m *MockIReleaseRepo) GetMapByUniqFlags(ctx context.Context, uniqFlags []*comvalobj.DataAgentUniqFlag) (map[string]*dapo.ReleasePO, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMapByUniqFlags", ctx, uniqFlags)
	ret0, _ := ret[0].(map[string]*dapo.ReleasePO)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMapByUniqFlags indicates an expected call of GetMapByUniqFlags.
func (mr *MockIReleaseRepoMockRecorder) GetMapByUniqFlags(ctx, uniqFlags any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMapByUniqFlags", reflect.TypeOf((*MockIReleaseRepo)(nil).GetMapByUniqFlags), ctx, uniqFlags)
}

// ListRecentAgentForMarket mocks base method.
func (m *MockIReleaseRepo) ListRecentAgentForMarket(ctx context.Context, req squarereq.AgentSquareRecentAgentReq) ([]*dapo.RecentVisitAgentPO, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListRecentAgentForMarket", ctx, req)
	ret0, _ := ret[0].([]*dapo.RecentVisitAgentPO)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListRecentAgentForMarket indicates an expected call of ListRecentAgentForMarket.
func (mr *MockIReleaseRepoMockRecorder) ListRecentAgentForMarket(ctx, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListRecentAgentForMarket", reflect.TypeOf((*MockIReleaseRepo)(nil).ListRecentAgentForMarket), ctx, req)
}

// Update mocks base method.
func (m *MockIReleaseRepo) Update(ctx context.Context, tx *sql.Tx, po *dapo.ReleasePO) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, tx, po)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockIReleaseRepoMockRecorder) Update(ctx, tx, po any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockIReleaseRepo)(nil).Update), ctx, tx, po)
}

// MockIReleaseHistoryRepo is a mock of IReleaseHistoryRepo interface.
type MockIReleaseHistoryRepo struct {
	ctrl     *gomock.Controller
	recorder *MockIReleaseHistoryRepoMockRecorder
	isgomock struct{}
}

// MockIReleaseHistoryRepoMockRecorder is the mock recorder for MockIReleaseHistoryRepo.
type MockIReleaseHistoryRepoMockRecorder struct {
	mock *MockIReleaseHistoryRepo
}

// NewMockIReleaseHistoryRepo creates a new mock instance.
func NewMockIReleaseHistoryRepo(ctrl *gomock.Controller) *MockIReleaseHistoryRepo {
	mock := &MockIReleaseHistoryRepo{ctrl: ctrl}
	mock.recorder = &MockIReleaseHistoryRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIReleaseHistoryRepo) EXPECT() *MockIReleaseHistoryRepoMockRecorder {
	return m.recorder
}

// BeginTx mocks base method.
func (m *MockIReleaseHistoryRepo) BeginTx(ctx context.Context) (*sql.Tx, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BeginTx", ctx)
	ret0, _ := ret[0].(*sql.Tx)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BeginTx indicates an expected call of BeginTx.
func (mr *MockIReleaseHistoryRepoMockRecorder) BeginTx(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BeginTx", reflect.TypeOf((*MockIReleaseHistoryRepo)(nil).BeginTx), ctx)
}

// Create mocks base method.
func (m *MockIReleaseHistoryRepo) Create(ctx context.Context, tx *sql.Tx, po *dapo.ReleaseHistoryPO) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, tx, po)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockIReleaseHistoryRepoMockRecorder) Create(ctx, tx, po any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockIReleaseHistoryRepo)(nil).Create), ctx, tx, po)
}

// GetByAgentIdVersion mocks base method.
func (m *MockIReleaseHistoryRepo) GetByAgentIdVersion(ctx context.Context, agentID, version string) (*dapo.ReleaseHistoryPO, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByAgentIdVersion", ctx, agentID, version)
	ret0, _ := ret[0].(*dapo.ReleaseHistoryPO)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByAgentIdVersion indicates an expected call of GetByAgentIdVersion.
func (mr *MockIReleaseHistoryRepoMockRecorder) GetByAgentIdVersion(ctx, agentID, version any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByAgentIdVersion", reflect.TypeOf((*MockIReleaseHistoryRepo)(nil).GetByAgentIdVersion), ctx, agentID, version)
}

// GetDB mocks base method.
func (m *MockIReleaseHistoryRepo) GetDB() *sqlx.DB {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDB")
	ret0, _ := ret[0].(*sqlx.DB)
	return ret0
}

// GetDB indicates an expected call of GetDB.
func (mr *MockIReleaseHistoryRepoMockRecorder) GetDB() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDB", reflect.TypeOf((*MockIReleaseHistoryRepo)(nil).GetDB))
}

// GetLatestVersionByAgentID mocks base method.
func (m *MockIReleaseHistoryRepo) GetLatestVersionByAgentID(ctx context.Context, agentID string) (*dapo.ReleaseHistoryPO, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLatestVersionByAgentID", ctx, agentID)
	ret0, _ := ret[0].(*dapo.ReleaseHistoryPO)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetLatestVersionByAgentID indicates an expected call of GetLatestVersionByAgentID.
func (mr *MockIReleaseHistoryRepoMockRecorder) GetLatestVersionByAgentID(ctx, agentID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLatestVersionByAgentID", reflect.TypeOf((*MockIReleaseHistoryRepo)(nil).GetLatestVersionByAgentID), ctx, agentID)
}

// ListByAgentID mocks base method.
func (m *MockIReleaseHistoryRepo) ListByAgentID(ctx context.Context, agentID string) ([]*dapo.ReleaseHistoryPO, int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByAgentID", ctx, agentID)
	ret0, _ := ret[0].([]*dapo.ReleaseHistoryPO)
	ret1, _ := ret[1].(int64)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ListByAgentID indicates an expected call of ListByAgentID.
func (mr *MockIReleaseHistoryRepoMockRecorder) ListByAgentID(ctx, agentID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByAgentID", reflect.TypeOf((*MockIReleaseHistoryRepo)(nil).ListByAgentID), ctx, agentID)
}

// MockIReleaseCategoryRelRepo is a mock of IReleaseCategoryRelRepo interface.
type MockIReleaseCategoryRelRepo struct {
	ctrl     *gomock.Controller
	recorder *MockIReleaseCategoryRelRepoMockRecorder
	isgomock struct{}
}

// MockIReleaseCategoryRelRepoMockRecorder is the mock recorder for MockIReleaseCategoryRelRepo.
type MockIReleaseCategoryRelRepoMockRecorder struct {
	mock *MockIReleaseCategoryRelRepo
}

// NewMockIReleaseCategoryRelRepo creates a new mock instance.
func NewMockIReleaseCategoryRelRepo(ctrl *gomock.Controller) *MockIReleaseCategoryRelRepo {
	mock := &MockIReleaseCategoryRelRepo{ctrl: ctrl}
	mock.recorder = &MockIReleaseCategoryRelRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIReleaseCategoryRelRepo) EXPECT() *MockIReleaseCategoryRelRepoMockRecorder {
	return m.recorder
}

// BatchCreate mocks base method.
func (m *MockIReleaseCategoryRelRepo) BatchCreate(ctx context.Context, tx *sql.Tx, pos []*dapo.ReleaseCategoryRelPO) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BatchCreate", ctx, tx, pos)
	ret0, _ := ret[0].(error)
	return ret0
}

// BatchCreate indicates an expected call of BatchCreate.
func (mr *MockIReleaseCategoryRelRepoMockRecorder) BatchCreate(ctx, tx, pos any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BatchCreate", reflect.TypeOf((*MockIReleaseCategoryRelRepo)(nil).BatchCreate), ctx, tx, pos)
}

// BeginTx mocks base method.
func (m *MockIReleaseCategoryRelRepo) BeginTx(ctx context.Context) (*sql.Tx, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BeginTx", ctx)
	ret0, _ := ret[0].(*sql.Tx)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BeginTx indicates an expected call of BeginTx.
func (mr *MockIReleaseCategoryRelRepoMockRecorder) BeginTx(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BeginTx", reflect.TypeOf((*MockIReleaseCategoryRelRepo)(nil).BeginTx), ctx)
}

// Create mocks base method.
func (m *MockIReleaseCategoryRelRepo) Create(ctx context.Context, tx *sql.Tx, po *dapo.ReleaseCategoryRelPO) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, tx, po)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockIReleaseCategoryRelRepoMockRecorder) Create(ctx, tx, po any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockIReleaseCategoryRelRepo)(nil).Create), ctx, tx, po)
}

// DelByReleaseID mocks base method.
func (m *MockIReleaseCategoryRelRepo) DelByReleaseID(ctx context.Context, tx *sql.Tx, release string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DelByReleaseID", ctx, tx, release)
	ret0, _ := ret[0].(error)
	return ret0
}

// DelByReleaseID indicates an expected call of DelByReleaseID.
func (mr *MockIReleaseCategoryRelRepoMockRecorder) DelByReleaseID(ctx, tx, release any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DelByReleaseID", reflect.TypeOf((*MockIReleaseCategoryRelRepo)(nil).DelByReleaseID), ctx, tx, release)
}

// GetByCategoryID mocks base method.
func (m *MockIReleaseCategoryRelRepo) GetByCategoryID(ctx context.Context, categoryID string) ([]*dapo.ReleaseCategoryRelPO, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByCategoryID", ctx, categoryID)
	ret0, _ := ret[0].([]*dapo.ReleaseCategoryRelPO)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByCategoryID indicates an expected call of GetByCategoryID.
func (mr *MockIReleaseCategoryRelRepoMockRecorder) GetByCategoryID(ctx, categoryID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByCategoryID", reflect.TypeOf((*MockIReleaseCategoryRelRepo)(nil).GetByCategoryID), ctx, categoryID)
}

// GetByReleaseID mocks base method.
func (m *MockIReleaseCategoryRelRepo) GetByReleaseID(ctx context.Context, release string) ([]*dapo.ReleaseCategoryRelPO, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByReleaseID", ctx, release)
	ret0, _ := ret[0].([]*dapo.ReleaseCategoryRelPO)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByReleaseID indicates an expected call of GetByReleaseID.
func (mr *MockIReleaseCategoryRelRepoMockRecorder) GetByReleaseID(ctx, release any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByReleaseID", reflect.TypeOf((*MockIReleaseCategoryRelRepo)(nil).GetByReleaseID), ctx, release)
}

// GetDB mocks base method.
func (m *MockIReleaseCategoryRelRepo) GetDB() *sqlx.DB {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDB")
	ret0, _ := ret[0].(*sqlx.DB)
	return ret0
}

// GetDB indicates an expected call of GetDB.
func (mr *MockIReleaseCategoryRelRepoMockRecorder) GetDB() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDB", reflect.TypeOf((*MockIReleaseCategoryRelRepo)(nil).GetDB))
}

// MockIReleasePermissionRepo is a mock of IReleasePermissionRepo interface.
type MockIReleasePermissionRepo struct {
	ctrl     *gomock.Controller
	recorder *MockIReleasePermissionRepoMockRecorder
	isgomock struct{}
}

// MockIReleasePermissionRepoMockRecorder is the mock recorder for MockIReleasePermissionRepo.
type MockIReleasePermissionRepoMockRecorder struct {
	mock *MockIReleasePermissionRepo
}

// NewMockIReleasePermissionRepo creates a new mock instance.
func NewMockIReleasePermissionRepo(ctrl *gomock.Controller) *MockIReleasePermissionRepo {
	mock := &MockIReleasePermissionRepo{ctrl: ctrl}
	mock.recorder = &MockIReleasePermissionRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIReleasePermissionRepo) EXPECT() *MockIReleasePermissionRepoMockRecorder {
	return m.recorder
}

// BatchCreate mocks base method.
func (m *MockIReleasePermissionRepo) BatchCreate(ctx context.Context, tx *sql.Tx, pos []*dapo.ReleasePermissionPO) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BatchCreate", ctx, tx, pos)
	ret0, _ := ret[0].(error)
	return ret0
}

// BatchCreate indicates an expected call of BatchCreate.
func (mr *MockIReleasePermissionRepoMockRecorder) BatchCreate(ctx, tx, pos any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BatchCreate", reflect.TypeOf((*MockIReleasePermissionRepo)(nil).BatchCreate), ctx, tx, pos)
}

// BeginTx mocks base method.
func (m *MockIReleasePermissionRepo) BeginTx(ctx context.Context) (*sql.Tx, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "BeginTx", ctx)
	ret0, _ := ret[0].(*sql.Tx)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// BeginTx indicates an expected call of BeginTx.
func (mr *MockIReleasePermissionRepoMockRecorder) BeginTx(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BeginTx", reflect.TypeOf((*MockIReleasePermissionRepo)(nil).BeginTx), ctx)
}

// Create mocks base method.
func (m *MockIReleasePermissionRepo) Create(ctx context.Context, tx *sql.Tx, po *dapo.ReleasePermissionPO) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, tx, po)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockIReleasePermissionRepoMockRecorder) Create(ctx, tx, po any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockIReleasePermissionRepo)(nil).Create), ctx, tx, po)
}

// DelByReleaseID mocks base method.
func (m *MockIReleasePermissionRepo) DelByReleaseID(ctx context.Context, tx *sql.Tx, release string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DelByReleaseID", ctx, tx, release)
	ret0, _ := ret[0].(error)
	return ret0
}

// DelByReleaseID indicates an expected call of DelByReleaseID.
func (mr *MockIReleasePermissionRepoMockRecorder) DelByReleaseID(ctx, tx, release any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DelByReleaseID", reflect.TypeOf((*MockIReleasePermissionRepo)(nil).DelByReleaseID), ctx, tx, release)
}

// GetByReleaseID mocks base method.
func (m *MockIReleasePermissionRepo) GetByReleaseID(ctx context.Context, release string) ([]*dapo.ReleasePermissionPO, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByReleaseID", ctx, release)
	ret0, _ := ret[0].([]*dapo.ReleasePermissionPO)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByReleaseID indicates an expected call of GetByReleaseID.
func (mr *MockIReleasePermissionRepoMockRecorder) GetByReleaseID(ctx, release any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByReleaseID", reflect.TypeOf((*MockIReleasePermissionRepo)(nil).GetByReleaseID), ctx, release)
}

// GetDB mocks base method.
func (m *MockIReleasePermissionRepo) GetDB() *sqlx.DB {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDB")
	ret0, _ := ret[0].(*sqlx.DB)
	return ret0
}

// GetDB indicates an expected call of GetDB.
func (mr *MockIReleasePermissionRepoMockRecorder) GetDB() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDB", reflect.TypeOf((*MockIReleasePermissionRepo)(nil).GetDB))
}

// MockIConversationHistoryRepo is a mock of IConversationHistoryRepo interface.
type MockIConversationHistoryRepo struct {
	ctrl     *gomock.Controller
	recorder *MockIConversationHistoryRepoMockRecorder
	isgomock struct{}
}

// MockIConversationHistoryRepoMockRecorder is the mock recorder for MockIConversationHistoryRepo.
type MockIConversationHistoryRepoMockRecorder struct {
	mock *MockIConversationHistoryRepo
}

// NewMockIConversationHistoryRepo creates a new mock instance.
func NewMockIConversationHistoryRepo(ctrl *gomock.Controller) *MockIConversationHistoryRepo {
	mock := &MockIConversationHistoryRepo{ctrl: ctrl}
	mock.recorder = &MockIConversationHistoryRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIConversationHistoryRepo) EXPECT() *MockIConversationHistoryRepoMockRecorder {
	return m.recorder
}

// GetLatestVisitAgentIds mocks base method.
func (m *MockIConversationHistoryRepo) GetLatestVisitAgentIds(ctx context.Context, userId string) ([]*dapo.ConversationHistoryLatestVisitAgentPO, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLatestVisitAgentIds", ctx, userId)
	ret0, _ := ret[0].([]*dapo.ConversationHistoryLatestVisitAgentPO)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetLatestVisitAgentIds indicates an expected call of GetLatestVisitAgentIds.
func (mr *MockIConversationHistoryRepoMockRecorder) GetLatestVisitAgentIds(ctx, userId any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLatestVisitAgentIds", reflect.TypeOf((*MockIConversationHistoryRepo)(nil).GetLatestVisitAgentIds), ctx, userId)
}
