/**
 * Autogenerated by Thrift Compiler (0.14.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.aishu.wf.core.thrift.eacplog;


@javax.annotation.Generated(value = "Autogenerated by Thrift Compiler (0.14.2)", date = "2023-06-06")
public enum ncTLogLevel implements org.apache.thrift.TEnum {
  NCT_LL_ALL(0),
  NCT_LL_INFO(1),
  NCT_LL_WARN(2);

  private final int value;

  private ncTLogLevel(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  @org.apache.thrift.annotation.Nullable
  public static ncTLogLevel findByValue(int value) { 
    switch (value) {
      case 0:
        return NCT_LL_ALL;
      case 1:
        return NCT_LL_INFO;
      case 2:
        return NCT_LL_WARN;
      default:
        return null;
    }
  }
}
